### ISSUE TITLE
Windows: Java2D simulations are paused at the 1st step until resizing the view

### ISSUE THREAD

**Issue by tcquang** [gama-platform/gama#1898] opened 2016-06-24 18:00 UTC
I have a little issue with the display of simulation with BDI models
### Steps to reproduce
1.Open an BDI model in the library: the Firefighters_BDI model in the BDI plugin model\BDI Archhitecture for example 

2.Launch the simulation

### Expected behavior
Tell us what should happen (include all relevant expectations)
Agent moving 

### Actual behavior
Tell us what happens instead (include relevant information, like logs, snapshots, etc.)
Agent were not moving, the simulations are paused at the 1st step until resizing the GAMA window
![not_working_before_resize](https://cloud.githubusercontent.com/assets/11825516/16345104/4b02bb7e-3a6a-11e6-872e-ebfb1f45d8f6.png)

In my BDI model: It does not show the simulation map until I resize the window
![bdi_farmer](https://cloud.githubusercontent.com/assets/11825516/16345306/718b95b2-3a6b-11e6-857f-075820cc308d.png)

For others models, it works well.

### System and version 
Which version of GAMA, JDK, OS ... (if necessary, copy Help>Installation Details>Configuration in GAMA)
Version Git, Windows 64bit

**Comment by AlexisDrogoul** [comment] 2016-06-25 19:01
Hmmm... Have you tried setting one of the displays to OpenGL ? It seems to me this bug is another version of the various "pausing" bugs we have had on Windows + Java2D.

**Comment by tcquang** [comment] 2016-06-26 02:47
Dear Mr. Drogoul,
Yes, It works well with an OpenGL setting. 
But I am keeping an exported version on 14 June, 2016. That version is working well with the Java 2D setting. I am sorry that I just cleaned the most recent exported versions. 
Best regards,

**Comment by AlexisDrogoul** [comment] 2016-06-27 06:51
Sorry I dont get it. Which version is running, which is not ? Are you saying that it was working on the 14th of June and that it is not working now ? Am I correct ?

**Comment by AlexisDrogoul** [comment] 2016-06-28 14:23
Almost a duplicate of #1594, but not quite.

**Comment by AlexisDrogoul** [comment] 2016-07-03 07:45
I have pushed a fix that makes Java2D usable, again, on Windows. Note that the new occurence of this error is due to updates to the JDK, which have broken the AWT_SWT bridge...

**Closed by AlexisDrogoul** 2016-07-03 07:45 UTC
Labels: > Bug, Affects Usability, Concerns Interface, Concerns Simulation, Display Java2D, OS Windows

**Comment by tcquang** [comment] 2016-07-03 08:13
It works fine!
Thank you!

2016-07-03 14:45 GMT+07:00 Alexis Drogoul <notifications@github.com>:

> Closed #1898 <https://github.com/gama-platform/gama/issues/1898>.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/gama-platform/gama/issues/1898#event-711346458>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ALRxbB2gTfY1lugMxB3k_hR46rBOD-q0ks5qR2iAgaJpZM4I9_Wb>
> .
>



-- 
Quang Chi TRUONG
Tel: 0939388153
