### ISSUE TITLE
Inspectors are broken ?

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#2104] opened 2017-01-29 21:34 UTC
### Steps to reproduce
1. Launch Boids with flock model (form the model library) 

2. Run the model.

3. Pause and click on a boid to inspect it.

### Expected behavior
The inspector of the agent opens.

### Actual behavior
I get an exception in the GAMA console : 
GAMA Caught a workbench message : Unhandled event loop exception org.eclipse.swt.SWTException: Failed to execute runnable (java.lang.NullPointerException)
org.eclipse.swt.SWTException: Failed to execute runnable (java.lang.NullPointerException)
	at org.eclipse.swt.SWT.error(SWT.java:4491)
	at org.eclipse.swt.SWT.error(SWT.java:4406)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:138)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4024)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3700)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1127)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1018)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:694)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:606)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at msi.gama.application.Application.start(Application.java:42)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:669)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1515)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1488)
Caused by: java.lang.NullPointerException
	at msi.gama.util.GAML.compileExpression(GAML.java:380)
	at msi.gama.util.GAML.compileExpression(GAML.java:358)
	at msi.gama.outputs.InspectDisplayOutput.<init>(InspectDisplayOutput.java:246)
	at ummisco.gama.ui.utils.SwtGui.lambda$7(SwtGui.java:351)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:135)
	... 24 more

### System and version 
GAMA Git, MACOSX

**Comment by AlexisDrogoul** [comment] 2017-01-30 04:05
Seems to be a regression caused by d7390cb1b42fc1f287abddd9271d88612a45f090 (committed to fix #2089 !).

**Comment by agrignard** [comment] 2017-02-02 14:55
I confirm a problem with the inspection on windows 10. I can select an agent but when I click on inspect nothing happens.

(Lastest Build so no console log)

**Closed** 2017-02-06 03:15 UTC
Labels: > Bug, Affects Usability, Concerns Simulation, OS OSX, OS Windows, Priority High, Version Git
