### ISSUE TITLE
ASC file error

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#1582] opened 2016-02-25 04:40 UTC
In the model library, the model Data Importation / models / ASC file import.gaml does not work.
We get the error: 
The format of hab10.asc is not correct. Error: ImageRead: No OperationDescriptor is registered in the current operation registry under this name.

**Comment by ptaillandier** [comment] 2016-02-25 10:00
With which version of GAMA? Because I tested it with the current GIT version (and a new workspace to be sure to have the right version of the model) and it works perfectly...

**Comment by AlexisDrogoul** [comment] 2016-02-25 10:08
Same here. Works without a hitch in the latest revision.

**Comment by benoitgaudou** [comment] 2016-02-26 05:58
Hi,
Gama Git up to date, with a fresh workspace.
I get this error .
Benoit

****************************************************

Thread [Worker-5] | Resource set [4 resources]

'ASC%20file%20Import.gaml' validated in 5.276 ms [ ~488 kb used ]

****************************************************

Initial seed: 0.9825502638885051; normalized seed: 9062426628753518592

Initial seed: 0.9825502638885051; normalized seed: 9062426628753518592

Initial seed: 0.9825502638885051; normalized seed: 9062426628753518592

Initial seed: 0.9825502638885051; normalized seed: 9062426628753518592

févr. 26, 2016 6:47:51 AM org.geotools.gce.arcgrid.ArcGridReader <init>

AVERTISSEMENT: Using default coordinate reference system


!ENTRY GAMA Caught a workbench message : GamaRuntimeException The format of
hab10.asc is incorrect. Attempting to read it anyway.

GAMA Caught a workbench message : GamaRuntimeException The format of
hab10.asc is incorrect. Attempting to read it anyway.

org.eclipse.ui 4 4 2016-02-26 06:47:51.664

!MESSAGE GamaRuntimeException The format of hab10.asc is incorrect.
Attempting to read it anyway.


!ENTRY org.eclipse.ui 4 4 2016-02-26 06:47:51.665

!MESSAGE GamaRuntimeException The format of hab10.asc is incorrect.
Attempting to read it anyway.

!STACK 0

The format of hab10.asc is incorrect. Attempting to read it anyway.

at msi.gama.runtime.exceptions.GamaRuntimeException.warning(
GamaRuntimeException.java:84)

at msi.gama.util.file.GamaGridFile.createReader(GamaGridFile.java:68)

at msi.gama.util.file.GamaGridFile.fillBuffer(GamaGridFile.java:251)

at msi.gama.util.file.GamaGridFile.computeEnvelope(GamaGridFile.java:235)

at msi.gama.common.util.GeometryUtils.computeEnvelopeFrom(
GeometryUtils.java:870)

at msi.gaml.operators.Spatial$Creation.envelope(Spatial.java:801)

at gaml.additions.GamlAdditions$700.run(GamlAdditions.java:742)

at gaml.additions.GamlAdditions$700.run(GamlAdditions.java:1)

at msi.gaml.expressions.UnaryOperator.value(UnaryOperator.java:65)

at msi.gama.runtime.AbstractScope.evaluate(AbstractScope.java:473)

at msi.gaml.variables.Variable.initializeWith(Variable.java:359)

at msi.gama.metamodel.population.GamaPopulation.createAndUpdateVariablesFor(
GamaPopulation.java:371)

at msi.gama.metamodel.population.GamaPopulation.createVariablesFor(
GamaPopulation.java:326)

at msi.gama.kernel.simulation.SimulationPopulation.createAgents(
SimulationPopulation.java:104)

at msi.gama.kernel.experiment.ExperimentAgent.createSimulation(
ExperimentAgent.java:208)

at msi.gama.kernel.experiment.ExperimentAgent._init_(
ExperimentAgent.java:177)

at msi.gama.metamodel.agent.MinimalAgent.init(MinimalAgent.java:170)

at msi.gama.runtime.AbstractScope.init(AbstractScope.java:511)

at msi.gama.kernel.experiment.ExperimentScheduler.schedule(
ExperimentScheduler.java:154)

at msi.gama.kernel.experiment.ExperimentAgent.schedule(
ExperimentAgent.java:238)

at msi.gama.kernel.experiment.ExperimentPlan.open(ExperimentPlan.java:313)

at msi.gama.kernel.experiment.ExperimentController$1.run(
ExperimentController.java:94)

at java.lang.Thread.run(Thread.java:745)

févr. 26, 2016 6:47:51 AM org.geotools.gce.arcgrid.ArcGridReader <init>

AVERTISSEMENT: Using default coordinate reference system


!ENTRY org.eclipse.ui 4 4 2016-02-26 06:47:51.721

!MESSAGE GamaRuntimeException The format of hab10.asc is not correct.
Error: ImageRead: No OperationDescriptor is registered in the current
operation registry under this name.

GAMA Caught a workbench message : GamaRuntimeException The format of
hab10.asc is not correct. Error: ImageRead: No OperationDescriptor is
registered in the current operation registry under this name.


!ENTRY org.eclipse.ui 4 4 2016-02-26 06:47:51.721

!MESSAGE GamaRuntimeException The format of hab10.asc is not correct.
Error: ImageRead: No OperationDescriptor is registered in the current
operation registry under this name.

!STACK 0

The format of hab10.asc is not correct. Error: ImageRead: No
OperationDescriptor is registered in the current operation registry under
this name.

at msi.gama.runtime.exceptions.GamaRuntimeException.error(
GamaRuntimeException.java:74)

at msi.gama.util.file.GamaGridFile$GamaGridReader.<init>(
GamaGridFile.java:206)

at msi.gama.util.file.GamaGridFile.createReader(GamaGridFile.java:102)

at msi.gama.util.file.GamaGridFile.fillBuffer(GamaGridFile.java:251)

at msi.gama.util.file.GamaGridFile.computeEnvelope(GamaGridFile.java:235)

at msi.gama.common.util.GeometryUtils.computeEnvelopeFrom(
GeometryUtils.java:870)

at msi.gaml.operators.Spatial$Creation.envelope(Spatial.java:801)

at gaml.additions.GamlAdditions$700.run(GamlAdditions.java:742)

at gaml.additions.GamlAdditions$700.run(GamlAdditions.java:1)

at msi.gaml.expressions.UnaryOperator.value(UnaryOperator.java:65)

at msi.gama.runtime.AbstractScope.evaluate(AbstractScope.java:473)

at msi.gaml.variables.Variable.initializeWith(Variable.java:359)

at msi.gama.metamodel.population.GamaPopulation.createAndUpdateVariablesFor(
GamaPopulation.java:371)

at msi.gama.metamodel.population.GamaPopulation.createVariablesFor(
GamaPopulation.java:326)

at msi.gama.kernel.simulation.SimulationPopulation.createAgents(
SimulationPopulation.java:104)

at msi.gama.kernel.experiment.ExperimentAgent.createSimulation(
ExperimentAgent.java:208)

at msi.gama.kernel.experiment.ExperimentAgent._init_(
ExperimentAgent.java:177)

at msi.gama.metamodel.agent.MinimalAgent.init(MinimalAgent.java:170)

at msi.gama.runtime.AbstractScope.init(AbstractScope.java:511)

at msi.gama.kernel.experiment.ExperimentScheduler.schedule(
ExperimentScheduler.java:154)

at msi.gama.kernel.experiment.ExperimentAgent.schedule(
ExperimentAgent.java:238)

at msi.gama.kernel.experiment.ExperimentPlan.open(ExperimentPlan.java:313)

at msi.gama.kernel.experiment.ExperimentController$1.run(
ExperimentController.java:94)

at java.lang.Thread.run(Thread.java:745)

GAMA Caught a workbench message : GamaRuntimeException The format of
hab10.asc is not correct. Error: ImageRead: No OperationDescriptor is
registered in the current operation registry under this name.

2016-02-25 11:08 GMT+01:00 Alexis Drogoul <notifications@github.com>:

**Comment by AlexisDrogoul** [comment] 2016-02-26 06:11
If the workspace is fresh, if the Git version is the latest, the only possibility is that you have different preferences. Are all the GIS related preferences set to True ? 

If yes, then the only solution will be to dig in the settings of GeoTools.

**Comment by benoitgaudou** [comment] 2016-02-26 06:36
Hi,
In the preferences, considering GIS related ones, all this to be to true
(cf picture).
In addition (perhaps not related to the previous one), I have an NPE in the
model loading TIFF data (GEOTIFF file Import.gaml).

Benoit



!ENTRY org.eclipse.ui 4 4 2016-02-26 07:30:58.034

!MESSAGE GamaRuntimeException java.lang.NullPointerException

GAMA Caught a workbench message : GamaRuntimeException
java.lang.NullPointerException


!ENTRY org.eclipse.ui 4 4 2016-02-26 07:30:58.034

!MESSAGE GamaRuntimeException java.lang.NullPointerException

!STACK 0

java.lang.NullPointerException

at msi.gama.util.file.GamaGridFile.getNbRows(GamaGridFile.java:261)

at msi.gama.metamodel.topology.grid.GamaSpatialMatrix.<init>(
GamaSpatialMatrix.java:126)

at msi.gama.metamodel.topology.grid.GridTopology.<init>(GridTopology.java:71
)

at msi.gama.metamodel.population.GamaPopulation.buildGridTopology(
GamaPopulation.java:506)

at msi.gama.metamodel.population.GamaPopulation.createPopulation(
GamaPopulation.java:55)

at msi.gama.metamodel.agent.GamlAgent.initializeMicroPopulation(
GamlAgent.java:177)

at msi.gaml.descriptions.SpeciesDescription$3.run(
SpeciesDescription.java:779)

at msi.gaml.variables.Variable.initializeWith(Variable.java:361)

at msi.gama.metamodel.population.GamaPopulation.createAndUpdateVariablesFor(
GamaPopulation.java:371)

at msi.gama.metamodel.population.GamaPopulation.createVariablesFor(
GamaPopulation.java:326)

at msi.gama.kernel.simulation.SimulationPopulation.createAgents(
SimulationPopulation.java:104)

at msi.gama.kernel.experiment.ExperimentAgent.createSimulation(
ExperimentAgent.java:208)

at msi.gama.kernel.experiment.ExperimentAgent._init_(
ExperimentAgent.java:177)

at msi.gama.metamodel.agent.MinimalAgent.init(MinimalAgent.java:170)

at msi.gama.runtime.AbstractScope.init(AbstractScope.java:511)

at msi.gama.kernel.experiment.ExperimentScheduler.schedule(
ExperimentScheduler.java:154)

at msi.gama.kernel.experiment.ExperimentAgent.schedule(
ExperimentAgent.java:238)

at msi.gama.kernel.experiment.ExperimentPlan.open(ExperimentPlan.java:313)

at msi.gama.kernel.experiment.ExperimentController$1.run(
ExperimentController.java:94)

at java.lang.Thread.run(Thread.java:745)

GAMA Caught a workbench message : GamaRuntimeException
java.lang.NullPointerException


2016-02-26 7:11 GMT+01:00 Alexis Drogoul <notifications@github.com>:

**Comment by AlexisDrogoul** [comment] 2016-02-26 06:55
I definitely can't reproduce it. GeoTiff loading is fine, too. The only explanation I can have is one related to your previous problems with displays, etc… Or maybe your environment ? Do you run GAMA on Java 1.7 or 1.8 ? And how much memory is allocated to it ?

**Comment by benoitgaudou** [comment] 2016-02-26 07:18
Hi Alexis,
You are right, it was a matter of Java version.
I fix it by changing the Run configurations, and using Java 1.8 as
Execution Environment.

Notice that by default, Eclipse creates this file with Gama 1.7

Cheers

Benoit


2016-02-26 7:55 GMT+01:00 Alexis Drogoul <notifications@github.com>:

**Comment by AlexisDrogoul** [comment] 2016-02-26 07:29
OK. So we can close the issue, but this means that GAMA (at least on MacOS X) needs Java 1.8 to run…

**Closed by AlexisDrogoul** 2016-02-26 07:29 UTC
Labels: Affects Datafiles, Affects Stability, In Models Library, OS OSX, Priority Low, Version Git
