### ISSUE TITLE
Anisotropic Diffusion (Cycle length)

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#1454] opened 2016-01-19 19:05 UTC
Run the model.
When the model is running, a column appears at the center . It disappears when the model is paused.

**Comment by AlexisDrogoul** [comment] 2016-02-13 07:00
Solved thanks to the work of @mazarsju and the changes in the OpenGL displays

**Comment by mazarsju** [comment] 2016-03-01 06:41
I reopen this issue : the column is still present when we run the simulation. We have to do an openGL action to make it disappear (ex : click on "rotate scene").

**Comment by AlexisDrogoul** [comment] 2016-03-10 12:16
Hi,

I have modified one thing (i.e. separate the "update" of the outputs — computation of the different facets, things to draw, etc., which runs in the simulation thread—  and the "update" of their views — OpenGL or Java2D rendering, which runs in a different thread — and I cannot  observe this behavior anymore: the column in the center is "normal", as it represents the value of 10.0 provided each step to the center cell, and it doesn't appear/disappear anymore. 

When the patch will be committed, can you test it and close the issue if it works ?

**Comment by mazarsju** [comment] 2016-03-11 03:55
No, still the same problem...

**Comment by AlexisDrogoul** [comment] 2016-03-11 06:23
Can you make and attach a small movie?  I can't reproduce it....

**Comment by mazarsju** [comment] 2016-03-11 06:36
[video_diffusion.zip](https://github.com/gama-platform/gama/files/168571/video_diffusion.zip)

**Comment by AlexisDrogoul** [comment] 2016-03-11 07:41
No, I dont have the same attenuation of the peak at the end, even switching back and forth FreeFly & ArcBall camera. But we agree, given the values of the model, that this peak is normal, isn't it ?

**Comment by mazarsju** [comment] 2016-03-11 08:08
The peak is not normal according to me. I can understand the small peak in the cycle_length = 1, since the value of the cell is turned to "1", but for the display with cycle_length > 1, there is no reason having this huge peak...

**Comment by AlexisDrogoul** [comment] 2016-03-11 08:14
But the value of phero is set to 10.0 and multiplied by 100. So for me it
is quite normal. The z of the environment is around 100, I think.

**Comment by mazarsju** [comment] 2016-03-11 08:16
Oh right sorry, I forgot that the phero was set to 10, my bad... Ok, so the behavior is normal, I close the issue.

**Closed by mazarsju** 2016-03-11 08:16 UTC
Labels: > Bug, Display OpenGL, OS All, Priority High, Version Git
