### ISSUE TITLE
Exception in eclipse if we try to popup the list menu of agents when running simulation

### ISSUE THREAD

**Issue by hqnghi88** [gama-platform/gama#1662] opened 2016-04-06 03:52 UTC
1. Launch experiment frmo Ants model.
2. Click Run button.
3. Try to right click on any ants
4. Exception in eclipse console:

GAMA Caught a workbench message : Unhandled event loop exception org.eclipse.swt.SWTException: Failed to execute runnable (java.util.ConcurrentModificationException)
org.eclipse.swt.SWTException: Failed to execute runnable (java.util.ConcurrentModificationException)
	at org.eclipse.swt.SWT.error(SWT.java:4491)
	at org.eclipse.swt.SWT.error(SWT.java:4406)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:138)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4155)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3772)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1127)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1018)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:654)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:598)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at msi.gama.application.Application.start(Application.java:124)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:669)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1515)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1488)
Caused by: java.util.ConcurrentModificationException
	at gnu.trove.impl.hash.THashIterator.nextIndex(THashIterator.java:156)
	at gnu.trove.impl.hash.THashIterator.hasNext(THashIterator.java:103)
	at gnu.trove.map.hash.THashMap$MapBackedView.toArray(THashMap.java:725)
	at java.util.ArrayList.<init>(ArrayList.java:177)
	at msi.gama.gui.views.actions.DisplayedAgentsMenu.fill(DisplayedAgentsMenu.java:121)
	at msi.gama.gui.views.actions.DisplayedAgentsMenu.getMenu(DisplayedAgentsMenu.java:56)
	at msi.gama.gui.displays.awt.DisplaySurfaceMenu$1.run(DisplaySurfaceMenu.java:79)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:135)
	... 24 more

**Comment by AlexisDrogoul** [comment] 2016-04-06 04:07
Marked as a duplicate of #1649

**Closed by AlexisDrogoul** 2016-04-06 04:07 UTC
