### ISSUE TITLE
Can't create a subspecies stored in a list of type of its abstract parent

### ISSUE THREAD

**Issue by Damapproject** [gama-platform/gama#2621] opened 2019-04-11 08:37 UTC
**Describe the bug**

I have an abstract species and I create two subspecies.
```
species Animal {
	action my_action virtual: true;
}
species Cat parent: Animal{
	action my_action {
	}
}
species Dog parent: Animal{
	action my_action {
	}
}
```
Then I create a list to store all my subspecies
`list<species<Animal>> animals <- [Cat, Dog];`

If I loop over my list of species, GAMA recognizes the type of my subspecies (Cat, Dog), but doesn't allow to create it saying it's abstract !
```
loop a over: animals{
    write a;
    write species_of(a);
    create a {}  // error
 } 
```

**Expected behavior**
Normally, I should be allowed to create cats and dogs even if they are stored in a list (in a variable) of their abstract parent species.
N.B : it works if we delete "virtual: true".

**Desktop (please complete the following information):**
 - OS: Windows 10
 - GAMA version: 1.8
 - Java version: 1.8

**Comment by hqnghi88** [comment] 2019-04-11 09:00
Hello,
I dont understand what do you want in create a? a cat, a dog or an animal? As specified in https://gama-platform.github.io/wiki/Inheritance.html and also your list is list of species Animal, so the error is clear, a contains an abstract action (virtual) that cannot be instanciated.  Removing "virtual:true" will do the job but i think it will create an Animal, not cat, nor dog. 
One workaround if i get your idea of put the "species" in list (i did not test in gama):
loop a over: animals{
    write a;
    write species_of(a);
    if(species_of(a)=Cat){ create Cat(a);}
    if(species_of(a)=Dog){ create Dog(a);}
 }

**Comment by AlexisDrogoul** [comment] 2019-04-11 09:06
@hqnghi88: the code which exhibits this issue is correct. It is actually a duplicate of #2611 -- well, not exactly a duplicate but it concerns the same behaviour. Basically, it amounts to accepting a potentially wrong species as an argument to `create`. And I must say I am a bit ambivalent about this, as it will require to add a good number of runtime checks in addition to the compilation checks.

**Comment by Damapproject** [comment] 2019-04-11 09:08
@hqnghi88 
1) In create a, I want to create the appropriate subspecies. So in the first time, it will be a Cat, then a Dog.
2) When removing "virtual : true", it creates a Cat the a Dog (I tested it). This is what GAMA is supposed to do, in my opinion, with or without "virtual : true".
3) Your workaround is a good solution if we have a few number of subspecies.

**Closed** 2019-04-13 14:55 UTC
