### ISSUE TITLE
Maximum memory value in Preferences is wrong and not written back to Gama.ini

### ISSUE THREAD

**Issue by tcquang** [gama-platform/gama#2990] opened 2020-05-26 07:52 UTC
Dear developers,
I have a small issue with configuration the maximum memory in GAMA.
When I downloaded a new version, the maximum memory value remained in the reference window of the new version but does not seem to be recognized in simulation time.
For fixing it, I had to change the maximum value to a another value.
Thank you very much for reading.
Quang

### Expected behavior
Don't need to change the maximum memory values if it is set in the references.

### Actual behavior
Tell us what happens instead (include relevant information, like logs, snapshots, etc.)

### System and version 
Which version of GAMA, JDK, OS ... (if necessary, copy Help>Installation Details>Configuration in GAMA): GAMA 1.8 Continuous built, Windows 10.

**Comment by hqnghi88** [comment] 2020-05-26 13:59
Hi Quang,
The fact is that the max mem amount is not saved in preference/registry of OS, it is in the ini file (gama.ini or eclipse.ini) so there is no way to automatically change it if you made a new package download. 
But yes, may be we should save it in registry and rewrite it in the ini file when first launch of gama. But it still needs a gama restart to take the effect.

**Comment by AlexisDrogoul** [comment] 2020-07-07 07:59
I'm not completely sure I understand this issue : is it because the default memory is too low ? Or because it is impossible to set it from the preferences ? In the first case, I think we can safely put the default parameters: `-Xms1024m -Xmx4096m` in the `.ini` files. Tell me what you had in mind !

**Comment by hqnghi88** [comment] 2020-07-09 13:34
Dear Alexis,
As discussed with Quang, i think the problem is : the number of memory in the preference is not written to the ini file when we download a new gama version. 

For ex, using an old gama version, we changed to 4096 in pref, restart gama and the ini is updated to 4096, BUT when we download a new version (the ini has default value), at the first start of this new version, when we go to preference, we see 4096 but in fact the ini still has default value. Quang must change the value in preference to trigger the rewrite to the ini file.

**Comment by AlexisDrogoul** [comment] 2020-07-09 14:39
Ok. Understood. Thank you. I will see what can be done in that respect.

**Comment by AlexisDrogoul** [comment] 2021-09-24 17:30
This issue should be fixed, by the way. I addressed it when fixing #3203

**Closed by AlexisDrogoul** 2021-09-24 17:30 UTC
Labels: >> 😱 Bug, Version All, OS All, 🙅🏻‍♂️ Affects Usability, ❗️ Priority High
