### ISSUE TITLE
Add predefined position for the camera

### ISSUE THREAD

**Issue by mazarsju** [gama-platform/gama#1553] opened 2016-02-17 08:07 UTC
The facet "camera_pos" should be used also with predefined constants (pair of constants vector / position) to make the placement of the camera easier. Here are some example of basics constants which would be nice to define :
#fromTop : vector (0,0,-1) + position (computed according to the world envelope)
#fromLeft : vector (1,0,0) + position (computed according to the world envelope)
#fromLeftWithElevation : vector (1,0,-1) + position (computed according to the world envelope)
#fromRight : vector (-1,0,0) + position (computed according to the world envelope)
#fromRightWithElevation : vector (-1,0,-1) + position (computed according to the world envelope)
#fromFont : vector (0,-1,0) + position (computed according to the world envelope)
#fromFrontWithElevation : vector (0,-1,-1) + position (computed according to the world envelope)

![arborescence2](https://cloud.githubusercontent.com/assets/12977635/13103309/143b19d4-d588-11e5-8122-69b481f55e5f.png)

**Comment by agrignard** [comment] 2016-02-17 08:31
I am not sure to understand the purpose of those constant? What do you mean by #fromTop?

**Comment by mazarsju** [comment] 2016-02-17 08:40
I don't know exactly what is happening during the compilation when a #constant is found, but the idea is that when you write the following line :

```
display my_display type:opengl camera_pos:#fromTop {...}
```

the position and the orientation of the camera is automatically computed to be on the top of the word, looking to the center of the world. So the camera looks "from the top". This #fromTop orientation/position is exactly the same as the current "default" orientation/position of the camera. But I would like to turn this "default" orientation/position to #fromFrontWithElevation instead, it makes more sense for me, as we are in 3D (cf #1554).

**Comment by agrignard** [comment] 2016-02-17 08:51
Ok I see. So we should add a new facet like camera_type or something like that that will interpret the constant. camera_pos is used only for the position of the camera,  in link with camera_look_pos and up_vector.

**Comment by mazarsju** [comment] 2016-02-17 08:53
Yes, maybe add a new facet is better then... Or using the same facet "camera_pos" for a different usage, but it may be a bit confused for the user, that is true...

**Comment by AlexisDrogoul** [comment] 2016-02-17 10:32
I think this is clearly a duplicate of #579 (with interesting ideas), which has not progressed a lot since the coding camp, and already describes managing camera positions/orientations. So, in that case (and when #579 will be addressed), the camera "constants" will not be constants but simply names of predefined cameras (the user being able, also, to add new names from the UI or in the model, with the `camera` statement). Having these predefined cameras already filling the UI menus will probably be of great help, too, for the user…

**Comment by AlexisDrogoul** [comment] 2016-03-07 16:54
Closing it as a duplicate of #579

**Closed by AlexisDrogoul** 2016-03-07 16:54 UTC
Labels: > Enhancement, Display OpenGL
