### ISSUE TITLE
Model save to asc broken?

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#2819] opened 2019-07-24 18:26 UTC
Run the "Save to ASC.gaml" model in Data Exportation.

The file is not created in the results folder. It is working for the rest like csv, geojson etc 

Gama 1.8 Official with JDK

**Comment by benoitgaudou** [comment] 2019-07-24 23:28
I just tried with the Git version of GAMA, and the file `grid.asc` is created in the `../results` folder.
Where is it created in your case

**Comment by AlexisDrogoul** [comment] 2019-07-25 04:12
Works like a charm for me too on Git version. Can someone else try with the latest build ? (I'm too lazy to download it).

**Comment by agrignard** [comment] 2019-07-25 12:59
I m pretty surprised by this bug but it still happening. You can see in this screenshot I have run the model and you cannot see the results folder (I did a refresh of the folder before to take the screenshot)

It might be due to an exotic configuration (mac 10.11) it works on the git version t I am might not be the only one to experience this
<img width="1912" alt="Screen Shot 2019-07-25 at 08 53 22" src="https://user-images.githubusercontent.com/3928502/61876017-dce9bf80-aeb9-11e9-996b-c485d4261eca.png">

I will redoanwload the officla release and test it (I might have an old official version? )

**Comment by agrignard** [comment] 2019-07-25 14:29
I just reproduce it with the last release (GAMA1.8_Official_withJDK_Mac_64bits) 22nd of June

The results folder is not created and the .asc file either

**Comment by benoitgaudou** [comment] 2019-07-26 03:10
Hi Arnaud,
I just downloaded the last continuous built version of GAMA
: GAMA1.8_Continuous_withJDK_Mac_07.25.19_bea2cfa.zip .
After running the model, I get the expected behaviour (the grid.asc created
in the folder results).

Could you tried with that one, because I remember that Alexis fix an issue
last week-end related to the case where the folder (result) does not exist.
In particular, can you try to, before running the model, create at hand the
result folder to check whether it creates the .asc file.

Cheers

Bneoit

[image: Screenshot 2019-07-26 at 10.06.09.png]

Le jeu. 25 juil. 2019 à 21:29, Arnaud Grignard <notifications@github.com> a
écrit :

**Comment by benoitgaudou** [comment] 2019-07-26 14:24
To confirm my previous message, I just downloaded the Gama official version (from the 22th).
In this version, if the folder result does not exist, then the .asc is not generated (whereas the save with some other data type works perfectly). When the folder exists, the save in .asc file works perfectly. 

With the continuous built this issue has been fixed (last week-end) in commit 
5a0dbe7.

I close the issue, feel free to reopen it if necessary.

**Closed by benoitgaudou** 2019-07-26 14:24 UTC
Labels: > Bug, Concerns Data Persistence, Concerns Models Library

**Comment by agrignard** [comment] 2019-07-26 14:26
I confirm this also. Working ok with the continuous build, not working with the official release unless the folder results exists.

So it means that in the current official release the bug is here.
