### ISSUE TITLE
Display with chart (issue of resizing ?)

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#2389] opened 2018-04-03 18:17 UTC
### Steps to reproduce
1. In some model with charts (in our case, 1 display for agents, 1 display for charts), run the model.

### Actual behavior
Sometimes, the chart in the chart display appears double (one on the left on the display, the other one from the center of the display).
Note that this issue is easily fixed by moving one of the border of the display (so by forcing resizing of the chart).

### System and version 
GAMA 1.8 RC, Windows 10

**Comment by AlexisDrogoul** [comment] 2018-04-04 02:01
Do you have any screenshots ? I can't reproduce it and don't really understand the description... Probably a Windows only problem in any case.

**Comment by hqnghi88** [comment] 2018-04-04 02:07
I never had this issue on my win 10 unless this case appeared on a not-powerful-enough machine ,the only thing i can imagine. As far as i know when one view is created, there is a refresh for all existing display view, doesnt it?

**Comment by sriramab** [comment] 2018-04-09 12:38
after some updates, i am not able to reproduce this.

**Comment by benoitgaudou** [comment] 2018-04-09 12:46
I showed that on 1 computer the first day ...
The second day I was not able to observe i again ...

Benoit

2018-04-09 14:38 GMT+02:00 Srirāma Bhamidipāti <notifications@github.com>:

**Comment by sriramab** [comment] 2018-04-13 10:02
This kind of happens in a mutated and different way! Charts are not displayed unless resized. There is a display window but it stays blank until made active by some kind of resizing or repositioning.

**Comment by hqnghi88** [comment] 2018-04-13 11:02
does it repeat or is reproduceible? if yes, team please.

**Comment by tcquang** [comment] 2018-04-30 07:41
Hi,
It occurred on low resolution displays. I saw that kind of charts in the computers in my practice lab (Core i3 - 1024x768, 2GB).
Besides that, the output of maps sometimes is bank when I arranged windows vertically (using Views\Arrange outputs \ Vertically). 
These problems will be fixed easily by stopping simulation and run again.
The GAMA version in computer lab is 1.7.
The figure is generated on may laptop Windows 10 64b. GAMA 1.8 64bits. Java 1.8 (Run in Override high DPI scaling mode)
![display1](https://user-images.githubusercontent.com/11825516/39418376-4aef202c-4c84-11e8-9924-ab67f6effbce.JPG)
![gama 1_8 pro](https://user-images.githubusercontent.com/11825516/39418377-4b34ab4c-4c84-11e8-8e06-963e525b15b3.JPG)

Quang

**Comment by sriramab** [comment] 2018-05-29 10:14
I still have this problem. Charts do not show up unless I resize them.

**Comment by pcaillou** [comment] 2018-05-31 11:45
Hi Srirama,

Does it happen for every chart whatever the model?
It seems to be working for me with windows 10 64bits (GIT Gama version)

Philippe

2018-05-29 12:14 GMT+02:00 Srirāma Bhamidipāti <notifications@github.com>:

**Comment by sriramab** [comment] 2018-05-31 14:10
Hi Philippe,

This is not really reproducible. Today it is not happening. But yes, it is always the same model. 
I am on windows 7 with latest build.

Srirama

**Comment by AlexisDrogoul** [comment] 2018-06-11 15:32
Have you tried to increase the delay between the opening of display views in the preferences ?

**Comment by sriramab** [comment] 2018-07-03 11:14
Yes, increasing delay has solved the problem for me.

**Comment by AlexisDrogoul** [comment] 2018-07-04 03:38
OK. So let's consider this case closed as it is covered by a preference. I don't fully understand, however, why increasing the delay really helps, but well...

**Comment by sriramab** [comment] 2018-07-04 05:08
May be something got fixed with the many new fancy changes you made to display layouts during the last 2-3 days

**Comment by sriramab** [comment] 2018-07-06 11:00
This has resurfaced, I am more than happy to provide a teamviewer session.

**Comment by sriramab** [comment] 2018-07-06 11:16
In my case, This is happening only in a series chart and only the first time, meaning, once I resize it, the chart is refreshed for the remainder of the simulation.

**Comment by AlexisDrogoul** [comment] 2018-07-06 16:35
Hum. It's been already reported, then fixed, in #1594 and #1722. Are you in these cases ? (i.e. front display only ?).

**Comment by sriramab** [comment] 2018-07-06 17:32
I can offer mine on team viewer, u can check the exact case also.

**Comment by hqnghi88** [comment] 2018-07-07 02:31
I cant reproduce it, with bot min and max delay, so no effect for these changes. 
Sriri, you did not mention your resurfacing case was helped with delay or not? as you say it helpful.

**Comment by sriramab** [comment] 2018-07-07 15:00
Yes, it helped, but then I updated gama, then it started again. It is very typical. It is happening only in one series chart. Today I made another series chart in the same model. This second series works normal. For me also it is not hundred percent reproducible. I wonder if this is happening related to having date on x-axis tick labels as I ask a question on the forum. May be if you try, please use a date as a tick label at one day frequency.

**Comment by AlexisDrogoul** [comment] 2018-07-08 02:18
@sriramab Yep, that would be helpful to post the 100% reproducible model. In the meantime, can you test with the new timing procedure ? (i.e. putting the delay to 1 sec, for instance).

**Comment by sriramab** [comment] 2018-07-10 08:21
I think for now, I will close this because I cannot share the model and may be it takes time before I make a reproducible model.

**Closed by sriramab** 2018-07-10 08:21 UTC
Labels: > Bug, Affects Usability, OS Windows, Version 1.8 RC
