### ISSUE TITLE
headless run problem

### ISSUE THREAD

**Issue by PeijunYe** [gama-platform/gama#2022] opened 2016-10-12 07:40 UTC
I am learning to use GAMA platform, beginning with a small program written by myself. The program runs very well in the GUI mode. But when I tried to start it in the headless mode, it fails. The problem is:

peijun:headless yepeijun$ sh gama-headless.sh test.xml output
gama-headless.sh

---
- GAMA version 1.7.0 V7                                          *
- http://gama-platform.org                                       *
- (c) 2007-2016 UMI 209 UMMISCO IRD/UPMC & Partners              *
  ---
  
  2016-10-12 14:33:33.054 java[548:15408] [JRSAppKitAWT markAppIsDaemon]: Process manager already initialized: can't fully enable headless mode.
  Exception in thread "Thread-2" java.lang.IllegalArgumentException: Equal objects must have equal hashcodes. During rehashing, Trove discovered that the following two objects claim to be equal (as in java.lang.Object.equals()) but their hashCodes (or those calculated by your TObjectHashingStrategy) are not equal.This violates the general contract of java.lang.Object.hashCode().  See bullet point two in that method's documentation. object #1 =class java.lang.Integer id= 646953941 hashCode= 23 toString= 23; object #2 =class java.lang.Integer id= 646953941 hashCode= 23 toString= 23
  
  at gnu.trove.impl.hash.TObjectHash.buildObjectContractViolation(TObjectHash.java:464)
  at gnu.trove.impl.hash.TObjectHash.throwObjectContractViolation(TObjectHash.java:426)
  at msi.gama.util.TOrderedHashMap.rehash(TOrderedHashMap.java:142)
  at gnu.trove.impl.hash.THash.postInsertHook(THash.java:388)
  at msi.gama.util.TOrderedHashMap.doPut(TOrderedHashMap.java:300)
  at msi.gama.util.TOrderedHashMap.put(TOrderedHashMap.java:231)
  at msi.gaml.types.TypesManager.addType(TypesManager.java:89)
  at msi.gaml.types.TypesManager.initType(TypesManager.java:85)
  at msi.gaml.compilation.AbstractGamlAdditions.initType(AbstractGamlAdditions.java:481)
  at msi.gaml.compilation.AbstractGamlAdditions._type(AbstractGamlAdditions.java:254)
  at gaml.additions.GamlAdditions.initializeTypes(GamlAdditions.java:72)
  at gaml.additions.GamlAdditions.initialize(GamlAdditions.java:51)
  at msi.gaml.compilation.GamaBundleLoader.preBuild(GamaBundleLoader.java:199)
  at msi.gaml.compilation.GamaBundleLoader.preBuildContributions(GamaBundleLoader.java:88)
  at msi.gama.common.Activator$1.run(Activator.java:17)
  at java.lang.Thread.run(Thread.java:745)
  An error has occurred. See the log file
  /Users/yepeijun/Downloads/Gama.app/Contents/Eclipse/configuration/1476254012016.log.

Could anyone kindly tell me what is wrong with my work?

My laptop is Mac and the os is OSX 10.10.4
Java environment is jdk1.7.0_79
GAMA version is GAMA1.7_osx64

The log file, input xml file and the model file are all attached here.

[1476254012016.txt](https://github.com/gama-platform/gama/files/523750/1476254012016.txt)
[test.xml.txt](https://github.com/gama-platform/gama/files/523755/test.xml.txt)
[test.gaml.txt](https://github.com/gama-platform/gama/files/523759/test.gaml.txt)

Thank you so much!

**Comment by AlexisDrogoul** [comment] 2016-10-12 07:51
Hi,

Are you running the latest build ? Or a build downloaded before ? 

Alexis

**Comment by AlexisDrogoul** [comment] 2016-10-12 07:52
And just to be sure: have you tried running it on JDK 1.8 ? The recent builds now require JDK 1.8 to be present.

**Comment by ptaillandier** [comment] 2016-10-12 08:58
I have tested the headless mode with the latest build version of GAMA (version of today - that works normally in GUI mode) and the examples (road traffic and predator prey) do not work. I was not able to get the log file (detele just after its creation?); I just have this message : 
java[4948:495305] [JRSAppKitAWT markAppIsDaemon]: Process manager already initialized: can't fully enable headless mode.
....  normal GAMA log ...
An error has occurred. See the log file
/Users/administrateur/Desktop/Gama17.app/Contents/headless/.work5164/.metadata/.log.

**Comment by PeijunYe** [comment] 2016-10-12 11:51
@AlexisDrogoul 
Thank you for your help. Actually, I tried my program on JDK 1.8 originally and got the same problem. I thought it may be wrong about the JDK version. So I changed it into 1.7. But the problem remains.

Also, I have tested the program on my desktop (Windows 7 x64bit, JDK 1.8.0_65, Gama 1.7 for windows x64). In GUI mode, it still runs well. But in the headless mode, it says:
error: cannot find the main class: org.eclipse.core.launcher.Main
It seems the configuration of eclipse is wrong. Could you please tell me where I should check my system?

**Comment by PeijunYe** [comment] 2016-10-12 11:54
@ptaillandier 
yes. I believe we have met the same problem. Have you tried the Gama 1.6.1 version?

**Comment by PeijunYe** [comment] 2016-10-12 12:02
@AlexisDrogoul 
forget to tell you. My Gama platform was downloaded yesterday from:
http://51.255.46.42/download#GAMA17
I think it is the latest version. Right?

**Comment by viethuong8** [comment] 2016-12-22 08:05
I try build gama-platform with java8 and run it in headless-mode, but i get 3 different outputs when i run a same command.
Can you help me?

My environment:
MacOS Sierra 10.12.1
JDK8
GamaPlatform 1.7
Eclipse DSL Tools Version: Mars.2 Release (4.5.2)


Mac:headless ifi$ sudo sh gama-headless.sh samples/predatorPrey.xml ~/ooo
	gama-headless.sh
	******************************************************************
	* GAMA version 1.7.0 V7                                          *
	* http://gama-platform.org                                       *
	* (c) 2007-2016 UMI 209 UMMISCO IRD/UPMC & Partners              *
	******************************************************************
	2016-12-22 13:40:20.414 java[5833:92637] [JRSAppKitAWT markAppIsDaemon]: Process manager already initialized: can't fully enable headless mode.
	An error has occurred. See the log file
	/Users/[...]/Gama.app/Contents/Eclipse/configuration/1482388808297.log.
	Exception in thread "Thread-2" java.lang.IllegalStateException: Module has been uninstalled.
		at org.eclipse.osgi.container.Module.checkValid(Module.java:526)
		at org.eclipse.osgi.container.Module.start(Module.java:392)
		at org.eclipse.osgi.framework.util.SecureAction.start(SecureAction.java:454)
		at org.eclipse.osgi.internal.hooks.EclipseLazyStarter.postFindLocalClass(EclipseLazyStarter.java:107)
		at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClass(ClasspathManager.java:531)
		at org.eclipse.osgi.internal.loader.ModuleClassLoader.findLocalClass(ModuleClassLoader.java:324)
		at org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:327)
		at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:402)
		at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:352)
		at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:344)
		at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:160)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
		at java.lang.Class.getDeclaredConstructors0(Native Method)
		at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
		at java.lang.Class.getConstructor0(Class.java:3075)
		at java.lang.Class.newInstance(Class.java:412)
		at msi.gaml.compilation.kernel.GamaBundleLoader.preBuild(GamaBundleLoader.java:189)
		at msi.gaml.compilation.kernel.GamaBundleLoader.preBuildContributions(GamaBundleLoader.java:89)
		at msi.gama.common.Activator.lambda$0(Activator.java:15)
		at java.lang.Thread.run(Thread.java:745)


Mac:headless ifi$ sudo sh gama-headless.sh samples/predatorPrey.xml ~/ooo
	gama-headless.sh
	******************************************************************
	* GAMA version 1.7.0 V7                                          *
	* http://gama-platform.org                                       *
	* (c) 2007-2016 UMI 209 UMMISCO IRD/UPMC & Partners              *
	******************************************************************
	2016-12-22 13:55:38.602 java[6204:99431] [JRSAppKitAWT markAppIsDaemon]: Process manager already initialized: can't fully enable headless mode.
	An error has occurred. See the log file
	/Users/[...]/Gama.app/Contents/Eclipse/configuration/1482389732439.log.
	Exception in thread "Thread-2" java.lang.ExceptionInInitializerError
		at gaml.additions.GamlAdditions.initializeTypes(GamlAdditions.java:85)
		at gaml.additions.GamlAdditions.initialize(GamlAdditions.java:52)



Mac:headless ifi$ sudo sh gama-headless.sh samples/predatorPrey.xml ~/ooo
	gama-headless.sh
	******************************************************************
	* GAMA version 1.7.0 V7                                          *
	* http://gama-platform.org                                       *
	* (c) 2007-2016 UMI 209 UMMISCO IRD/UPMC & Partners              *
	******************************************************************
	2016-12-22 13:56:01.973 java[6220:99929] [JRSAppKitAWT markAppIsDaemon]: Process manager already initialized: can't fully enable headless mode.
	Exception in thread "Thread-2" java.lang.ExceptionInInitializerError
		at gaml.additions.GamlAdditions.initializeTypes(GamlAdditions.java:85)
		at gaml.additions.GamlAdditions.initialize(GamlAdditions.java:52)
		at msi.gaml.compilation.kernel.GamaBundleLoader.preBuild(GamaBundleLoader.java:198)
		at msi.gaml.compilation.kernel.GamaBundleLoader.preBuildContributions(GamaBundleLoader.java:89)
		at msi.gama.common.Activator.lambda$0(Activator.java:15)
		at java.lang.Thread.run(Thread.java:745)
	Caused by: java.lang.NullPointerException: Inflater has been closed
		at java.util.zip.Inflater.ensureOpen(Inflater.java:389)
		at java.util.zip.Inflater.inflate(Inflater.java:257)
		at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:152)
		at org.eclipse.osgi.storage.bundlefile.ZipBundleEntry$ZipBundleEntryInputStream.read(ZipBundleEntry.java:156)
		at org.eclipse.osgi.storage.StorageUtil.getBytes(StorageUtil.java:195)
		at org.eclipse.osgi.storage.bundlefile.BundleEntry.getBytes(BundleEntry.java:94)
		at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findClassImpl(ClasspathManager.java:568)
		at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClassImpl(ClasspathManager.java:540)
		at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClass(ClasspathManager.java:527)
		at org.eclipse.osgi.internal.loader.ModuleClassLoader.findLocalClass(ModuleClassLoader.java:324)
		at org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:327)
		at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:402)
		at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:352)
		at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:344)
		at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:160)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
		at java.lang.ClassLoader.defineClass1(Native Method)
		at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
		at org.eclipse.osgi.internal.loader.ModuleClassLoader.defineClass(ModuleClassLoader.java:272)
		at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.defineClass(ClasspathManager.java:632)
		at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findClassImpl(ClasspathManager.java:588)
		at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClassImpl(ClasspathManager.java:540)
		at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClass(ClasspathManager.java:527)
		at org.eclipse.osgi.internal.loader.ModuleClassLoader.findLocalClass(ModuleClassLoader.java:324)
		at org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:327)
		at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:402)
		at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:352)
		at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:344)
		at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:160)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
		at msi.gaml.types.GamaGeometryType.<clinit>(GamaGeometryType.java:545)
		... 6 more
	An error has occurred. See the log file
	/Users/[...]/Gama.app/Contents/Eclipse/configuration/1482389755827.log.

**Comment by AlexisDrogoul** [comment] 2017-02-24 17:44
Hi,

Took a while, but we have been able with @gnoubi (Nicolas Marilleau) to have a running headless version (commit 4c78390499b5caace9cac08ee0185f4f97afc061).

Can you try it ? 

Cheers
Alexis

**Comment by PeijunYe** [comment] 2017-02-28 02:05
@AlexisDrogoul 
Thanks for your help. I tried the latest version published at 27th, Feb. on Mac OSX through its own examples, but it seems some problems still remain.
1. the example "predatorPrey.xml" can be run normally on Mac OSX;
2. "predatorPrey2.xml" can be also run well at the beginning, but after the cycle 101, it reports an exception:
peijun:headless yepeijun$ sh gama-headless.sh samples/predatorPrey2.xml output
gama-headless.sh
******************************************************************
* GAMA version 1.7.0 V7                                          *
* http://gama-platform.org                                       *
* (c) 2007-2016 UMI 209 UMMISCO IRD/UPMC & Partners              *
******************************************************************
2017-02-28 08:46:17.395 java[556:12023] [JRSAppKitAWT markAppIsDaemon]: Process manager already initialized: can't fully enable headless mode.
>GAMA plugin loaded in 764 ms: 	msi.gama.core
>GAMA plugin loaded in 4 ms: 	ummisco.gama.network
>GAMA plugin loaded in 37 ms: 	simtools.gaml.extensions.traffic
>GAMA plugin loaded in 8 ms: 	simtools.gaml.extensions.physics
>GAMA plugin loaded in 3 ms: 	irit.gaml.extensions.test
>GAMA plugin loaded in 11 ms: 	ummisco.gaml.extensions.maths
>GAMA plugin loaded in 14 ms: 	msi.gaml.extensions.fipa
>GAMA plugin loaded in 5 ms: 	ummisco.gama.serialize
>GAMA plugin loaded in 14 ms: 	irit.gaml.extensions.database
>GAMA plugin loaded in 3 ms: 	msi.gama.lang.gaml
>GAMA plugin loaded in 2 ms: 	msi.gama.headless
>GAMA plugin loaded in 74 ms: 	ummisco.gama.java2d
>GAMA plugin loaded in 51 ms: 	msi.gaml.architecture.simplebdi
>GAMA plugin loaded in 20 ms: 	ummisco.gama.opengl
>GAMA total load time 1097 ms.
>GAMA building GAML artefacts in 338 ms
cpus :4
Init
nb_preys_init: 3
nb_predators_init: 2
seed : 0.9671707925632088
Simulation is running...
.Message at cycle 0
Message at cycle 1
.Message at cycle 2
...
.Message at cycle 100
Message at cycle 101
Exception in thread "Thread-7" java.lang.NullPointerException
	at msi.gama.headless.job.ExperimentJob.exportVariables(ExperimentJob.java:301)
	at msi.gama.headless.job.ExperimentJob.doStep(ExperimentJob.java:280)
	at msi.gama.headless.job.ExperimentJob.play(ExperimentJob.java:259)
	at msi.gama.headless.runtime.LocalSimulationRuntime$FakeApplication.run(LocalSimulationRuntime.java:222)

3. "roadTraffic.xml" cannot be run. It receives:
peijun:headless yepeijun$ sh gama-headless.sh samples/roadTraffic.xml output
gama-headless.sh
******************************************************************
* GAMA version 1.7.0 V7                                          *
* http://gama-platform.org                                       *
* (c) 2007-2016 UMI 209 UMMISCO IRD/UPMC & Partners              *
******************************************************************
2017-02-28 08:48:32.609 java[574:13022] [JRSAppKitAWT markAppIsDaemon]: Process manager already initialized: can't fully enable headless mode.
>GAMA plugin loaded in 797 ms: 	msi.gama.core
>GAMA plugin loaded in 13 ms: 	ummisco.gama.network
>GAMA plugin loaded in 25 ms: 	simtools.gaml.extensions.traffic
>GAMA plugin loaded in 7 ms: 	simtools.gaml.extensions.physics
>GAMA plugin loaded in 3 ms: 	irit.gaml.extensions.test
>GAMA plugin loaded in 14 ms: 	ummisco.gaml.extensions.maths
>GAMA plugin loaded in 16 ms: 	msi.gaml.extensions.fipa
>GAMA plugin loaded in 6 ms: 	ummisco.gama.serialize
>GAMA plugin loaded in 12 ms: 	irit.gaml.extensions.database
>GAMA plugin loaded in 3 ms: 	msi.gama.lang.gaml
>GAMA plugin loaded in 2 ms: 	msi.gama.headless
>GAMA plugin loaded in 6 ms: 	ummisco.gama.java2d
>GAMA plugin loaded in 47 ms: 	msi.gaml.architecture.simplebdi
>GAMA plugin loaded in 9 ms: 	ummisco.gama.opengl
>GAMA total load time 1134 ms.
>GAMA building GAML artefacts in 328 ms
cpus :4
Exception in thread "Thread-7" java.lang.RuntimeException: msi.gama.headless.core.GamaHeadlessException: Compilation errors: 
Syntax errors 

	at msi.gama.headless.core.HeadlessSimulationLoader.loadModel(HeadlessSimulationLoader.java:88)
	at msi.gama.headless.runtime.LocalSimulationRuntime.loadModel(LocalSimulationRuntime.java:183)
	at msi.gama.headless.job.ExperimentJob.load(ExperimentJob.java:231)
	at msi.gama.headless.job.ExperimentJob.loadAndBuild(ExperimentJob.java:197)
	at msi.gama.headless.runtime.LocalSimulationRuntime$FakeApplication.run(LocalSimulationRuntime.java:210)
Caused by: msi.gama.headless.core.GamaHeadlessException: Compilation errors: 
Syntax errors 

	at msi.gama.headless.core.HeadlessSimulationLoader.loadModel(HeadlessSimulationLoader.java:80)
	... 4 more

My java environment is 1.8.0_121, 64bit. There is no log file generated. Is there anything wrong with my operations?

Another question is how to run the examples on Windows platform. Is it directly run the "gama-headless.bat" only after setting these two lines: 
set inputFile="samples/predatorPrey.xml"
set outputFile="output" ?
If so, the program says it cannot find the Main class: org.eclipse.core.launcher.Main

**Comment by PeijunYe** [comment] 2017-02-28 02:12
@viethuong8 
It seems some exceptions happened in the initialization. Have you tried the latest version?

**Comment by AlexisDrogoul** [comment] 2017-03-26 05:38
To my knowledge, these bugs have been fixed (especially the one mentioned by @PeijunYe, with compilation errors). Can you verify it ? Thanks.

**Comment by AlexisDrogoul** [comment] 2017-03-31 12:05
Closing the issue as there are no reaction to the previous message. Please reopen in case these errors are still present.

**Comment by kalyons11** [comment] 2017-05-17 16:09
Hello,

I am running into this same issue when running the headless mode. I have downloaded the latest GAMA Version 1.7 RC 2 from 4/15/2017. I am running Mac OSX Sierra 10.12.4. Javac version 1.8.0_31-b13.

When I run the gama-headless.sh script, I get an error. I am using the exact command taken from the Wiki page.

```
$ sh headless/gama-headless.sh headless/samples/predatorPrey.xml outputHeadLess
******************************************************************
* GAMA version 1.7.0 V7                                          *
* http://gama-platform.org                                       *
* (c) 2007-2016 UMI 209 UMMISCO IRD/UPMC & Partners              *
******************************************************************
Error: Could not find or load main class org.eclipse.core.launcher.Main
```

The above steps and commits do not seem to have resolved this issue. I am working on a project with @agrignard at the MIT Media Lab using the GAMA Platform.

Any help is greatly appreciated!

**Comment by PeijunYe** [comment] 2017-05-18 07:13
@
I met your problem before on Windows OS. My version is 1.7 RC1. But I think Mac might be the same.
You need to assign the main class explicitly in the .sh file.
The java command line in the "gama-headless.sh" file is like:
java -cp ../Eclipse/plugins/org.eclipse.equinox.launcher*.jar ...
You can fine the .jar file through the path and replace the "*" with its full name. Mine is:
../Eclipse/plugins/org.eclipse.equinox.launcher_1.3.100.v20150511-1540.jar
Then you can start the simulation.

But in this example, some other exceptions may be thrown out. Can you try and tell me your result?


best regards!

peijun ye

**Comment by PeijunYe** [comment] 2017-05-18 07:14
@kalyons11
I met your problem before on Windows OS. My version is 1.7 RC1. But I think Mac might be the same.
You need to assign the main class explicitly in the .sh file.
The java command line in the "gama-headless.sh" file is like:
java -cp ../Eclipse/plugins/org.eclipse.equinox.launcher*.jar ...
You can fine the .jar file through the path and replace the "*" with its full name. Mine is:
../Eclipse/plugins/org.eclipse.equinox.launcher_1.3.100.v20150511-1540.jar
Then you can start the simulation.

But in this example, some other exceptions may be thrown out. Can you try and tell me your result?

best regards!

peijun ye

**Comment by kalyons11** [comment] 2017-05-18 11:24
@PeijunYe Thanks for the response. I made this change and the script ran for a bit longer, but then crashed with an error similar to the one you previously had.

```
2017-05-18 07:17:45.438 java[26653:4456088] [JRSAppKitAWT markAppIsDaemon]: Process manager already initialized: can't fully enable headless mode.
>GAMA plugin loaded in 810 ms: 	msi.gama.core
>GAMA plugin loaded in 14 ms: 	ummisco.gama.network
>GAMA plugin loaded in 44 ms: 	simtools.gaml.extensions.traffic
>GAMA plugin loaded in 23 ms: 	simtools.gaml.extensions.physics
>GAMA plugin loaded in 4 ms: 	irit.gaml.extensions.test
>GAMA plugin loaded in 47 ms: 	ummisco.gaml.extensions.maths
>GAMA plugin loaded in 45 ms: 	msi.gaml.extensions.fipa
>GAMA plugin loaded in 11 ms: 	ummisco.gama.serialize
>GAMA plugin loaded in 17 ms: 	irit.gaml.extensions.database
>GAMA plugin loaded in 9 ms: 	msi.gama.lang.gaml
>GAMA plugin loaded in 13 ms: 	ummisco.gama.java2d
>GAMA plugin loaded in 296 ms: 	msi.gaml.architecture.simplebdi
>GAMA plugin loaded in 47 ms: 	ummisco.gama.opengl
>GAMA total load time 1486 ms.
>GAMA building GAML artefacts in 489 ms
Number of cpus used:4 (available: 4)
```

Were you ever able to find a fix for this error?

**Comment by gnoubi** [comment] 2017-05-18 20:33
Dear,

There were a small bug with headless on the 1.7 RC1. This bug is solved in RC2. Could you test it ? 

Nicolas
-- 
Nicolas Marilleau
UMI 209 UMMISCO Institut de Recherche pour le Développement
Chercheur invité DISC/ Femto-ST Université de Franche-Comté

32 rue Henri Varagnat
93143 Bondy Cedex
tel : 01.48.02.79.01
mobile : 06.88.33.49.06

**Comment by agrignard** [comment] 2017-05-18 20:55
Just for information this is the output I get when I try to run a headless model

dhcp-18-111-20-43:Gama_RC2.app Arno$ cd Contents/
dhcp-18-111-20-43:Contents Arno$ sh headless/gama-headless.sh headless/samples/predatorPrey.xml outputHeadLess
headless/gama-headless.sh
******************************************************************
* GAMA version 1.7.0 V7                                          *
* http://gama-platform.org                                       *
* (c) 2007-2016 UMI 209 UMMISCO IRD/UPMC & Partners              *
******************************************************************
Error: Could not find or load main class org.eclipse.core.launcher.Main

**Comment by gnoubi** [comment] 2017-05-18 20:58
you have to be in headless directory to run headless. Otherwise, the scrip does not find gama plugins
nicolas
-- 
Nicolas Marilleau
UMI 209 UMMISCO Institut de Recherche pour le Développement
Chercheur invité DISC/ Femto-ST Université de Franche-Comté

32 rue Henri Varagnat
93143 Bondy Cedex
tel : 01.48.02.79.01
mobile : 06.88.33.49.06

**Comment by agrignard** [comment] 2017-05-18 21:36
Mmm...ok it's working from headless but we agree that the previous command should also work,no?

**Comment by gnoubi** [comment] 2017-05-19 06:29
No, the previous command doesn't work because, you are not locate at the good place and the script cannot find gama.

To solve such problem, we can add gama_home environment variable. This variable must be setup before using gama in headless mode

Nicolas 

Nicolas Marilleau
UMI 209 UMMISCO IRD/UPMC
Chercheur invité Femto-st

Institut de Recherche pour le Développement 
32 avenue Henri Varagnat
93143 Bondy 
Fixe : 0148027901
Mobile: 0688334906

**Comment by AlexisDrogoul** [comment] 2017-05-19 06:52
I guess the solution would come from having a proper build script for macOS (as it seems to work on Windows and Linux, right ?) that correctly configures the headless script and its location. Is it something that can be done for a RC3 version ?

**Comment by PeijunYe** [comment] 2017-05-19 09:56
@kalyons11
I have updated my version to RC2 and also met this. The program says: can't fully enable headless mode.
But the simulation seems normal, since no exception come out and the results in output directory (an empty txt file, a xml file, and a group of snapshots ) are right in my headless run. (Your meassage attached here is not complete. You can check if there are exceptions.)

The other 2 examples attached in the headless directory cannot be run very well. Both of them return some exceptions.
predatorPrey2: Thread 7 NullPointerException
roadTraffic: Thread 7 Compilation errors

Can you have a try?

best regards!

**Comment by PeijunYe** [comment] 2017-05-19 10:02
@gnoubi
I have tried the latest RC2 version. But the previous problem still remains.
Attached is the message of roadTraffic example on Windows. Could you please have a look?

best regards!

**Comment by PeijunYe** [comment] 2017-05-19 10:17
@gnoubi
I have tried the latest RC2 version. But the previous problem still remains.
Attached is the message of roadTraffic example on Windows. Could you please have a look?

best regards!
![roadtraffic](https://cloud.githubusercontent.com/assets/22786393/26243711/5ae310d6-3cbf-11e7-8c5c-724dfd987711.png)

**Comment by gnoubi** [comment] 2017-05-23 10:33
It was a compilation error in the model. The bug is fixed now

nicolas
-- 
Nicolas Marilleau
UMI 209 UMMISCO Institut de Recherche pour le Développement
Chercheur invité DISC/ Femto-ST Université de Franche-Comté

32 rue Henri Varagnat
93143 Bondy Cedex
tel : 01.48.02.79.01
mobile : 06.88.33.49.06

**Comment by gnoubi** [comment] 2017-05-23 10:53
issue solved

**Closed** 2017-05-23 10:53 UTC
Labels: > Bug, In Headless, OS OSX, Priority High, Version 1.7 beta
