### ISSUE TITLE
JOGL 2.3.2 problem on Ubuntu 16 and MESA drivers

### ISSUE THREAD

**Issue by ptaillandier** [gama-platform/gama#2472] opened 2018-07-23 17:13 UTC
**Describe the bug**
Opengl display does not work anymore.
Error (Eclipse) : 

GAMA Caught a workbench message : Unhandled event loop exception
com.jogamp.opengl.GLException: main: createImpl ARB n/a but required, profile > GL2 requested (OpenGL >= 3.1). Requested: GLProfile[GL3bc/GL3bc.sw], current: 3.0 (Compat profile, compat[ES2], FBO, software) - 3.0 Mesa 18.0.5
	at jogamp.opengl.x11.glx.X11GLXContext.createImpl(X11GLXContext.java:440)
	at jogamp.opengl.GLContextImpl.makeCurrentWithinLock(GLContextImpl.java:765)
	at jogamp.opengl.GLContextImpl.makeCurrent(GLContextImpl.java:648)
	at jogamp.opengl.GLContextImpl.makeCurrent(GLContextImpl.java:586)
	at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1279)
	at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:1147)
	at com.jogamp.opengl.swt.GLCanvas$3.run(GLCanvas.java:171)
	at com.jogamp.opengl.swt.GLCanvas.runInGLThread(GLCanvas.java:959)
	at com.jogamp.opengl.swt.GLCanvas.displayIfNoAnimatorNoCheck(GLCanvas.java:646)
	at com.jogamp.opengl.swt.GLCanvas.access$1100(GLCanvas.java:95)
	at com.jogamp.opengl.swt.GLCanvas$7.handleEvent(GLCanvas.java:389)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5348)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1348)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1374)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1357)
	at org.eclipse.swt.widgets.Control.gtk_draw(Control.java:3454)
	at org.eclipse.swt.widgets.Composite.gtk_draw(Composite.java:351)
	at org.eclipse.swt.widgets.Canvas.gtk_draw(Canvas.java:175)
	at org.eclipse.swt.widgets.Widget.windowProc(Widget.java:1939)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:6193)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5608)
	at org.eclipse.swt.internal.gtk.OS._gtk_main_do_event(Native Method)
	at org.eclipse.swt.internal.gtk.OS.gtk_main_do_event(OS.java:9282)
	at org.eclipse.swt.widgets.Display.eventProc(Display.java:1328)
	at org.eclipse.swt.internal.gtk.OS._g_main_context_iteration(Native Method)
	at org.eclipse.swt.internal.gtk.OS.g_main_context_iteration(OS.java:2116)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4181)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1150)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1039)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:680)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:594)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at msi.gama.application.Application.start(Application.java:83)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1499)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1472)
Exception in OpenGL:Animator thread: createImpl ARB n/a but required, profile > GL2 requested (OpenGL >= 3.1). Requested: GLProfile[GL3bc/GL3bc.sw], current: 3.0 (Compat profile, compat[ES2], FBO, software) - 3.0 Mesa 18.0.5
GAMA Caught a workbench message : Unhandled event loop exception
com.jogamp.opengl.GLException: main: createImpl ARB n/a but required, profile > GL2 requested (OpenGL >= 3.1). Requested: GLProfile[GL3bc/GL3bc.sw], current: 3.0 (Compat profile, compat[ES2], FBO, software) - 3.0 Mesa 18.0.5
	at jogamp.opengl.x11.glx.X11GLXContext.createImpl(X11GLXContext.java:440)
	at jogamp.opengl.GLContextImpl.makeCurrentWithinLock(GLContextImpl.java:765)
	at jogamp.opengl.GLContextImpl.makeCurrent(GLContextImpl.java:648)
	at jogamp.opengl.GLContextImpl.makeCurrent(GLContextImpl.java:586)
	at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1279)
	at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:1147)
	at com.jogamp.opengl.swt.GLCanvas$3.run(GLCanvas.java:171)
	at com.jogamp.opengl.swt.GLCanvas.runInGLThread(GLCanvas.java:959)
	at com.jogamp.opengl.swt.GLCanvas.displayIfNoAnimatorNoCheck(GLCanvas.java:646)
	at com.jogamp.opengl.swt.GLCanvas.access$1100(GLCanvas.java:95)
	at com.jogamp.opengl.swt.GLCanvas$7.handleEvent(GLCanvas.java:389)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5348)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1348)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1374)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1357)
	at org.eclipse.swt.widgets.Control.gtk_draw(Control.java:3454)
	at org.eclipse.swt.widgets.Composite.gtk_draw(Composite.java:351)
	at org.eclipse.swt.widgets.Canvas.gtk_draw(Canvas.java:175)
	at org.eclipse.swt.widgets.Widget.windowProc(Widget.java:1939)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:6193)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5608)
	at org.eclipse.swt.internal.gtk.OS._gtk_main_do_event(Native Method)
	at org.eclipse.swt.internal.gtk.OS.gtk_main_do_event(OS.java:9282)
	at org.eclipse.swt.widgets.Display.eventProc(Display.java:1328)
	at org.eclipse.swt.internal.gtk.OS._g_main_context_iteration(Native Method)
	at org.eclipse.swt.internal.gtk.OS.g_main_context_iteration(OS.java:2116)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4181)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1150)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1039)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:680)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:594)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at msi.gama.application.Application.start(Application.java:83)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1499)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1472)
Exception in OpenGL:Animator thread: createImpl ARB n/a but required, profile > GL2 requested (OpenGL >= 3.1). Requested: GLProfile[GL3bc/GL3bc.sw], current: 3.0 (Compat profile, compat[ES2], FBO, software) - 3.0 Mesa 18.0.5
Exception in OpenGL:Animator thread: createImpl ARB n/a but required, profile > GL2 requested (OpenGL >= 3.1). Requested: GLProfile[GL3bc/GL3bc.sw], current: 3.0 (Compat profile, compat[ES2], FBO, software) - 3.0 Mesa 18.0.5

**To Reproduce**
Open and run a model with an opengl display

**Desktop (please complete the following information):**
 - OS:Ubuntu 16.04 64 bits
 - GAMA version: git 
 - Java version: 1.8

**Additional context**

**Comment by AlexisDrogoul** [comment] 2018-07-23 17:43
I would rather say it is a problem of the graphics card and that GAMA has nothing to do with (if you look at the stack trace, JOGL cannot find a correct config). 

So can you give more specifications ? Did the same model work under OpenGL and Linux before ? If so what did you change (graphics configuration, OS version, ...). A bit of background would be appreciated -- otherwise there are no ways to deal with the exception.

**Comment by AlexisDrogoul** [comment] 2018-07-23 18:15
Well.  See: http://forum.jogamp.org/problem-using-jogl-2-3-2-on-linux-tc4038557.html as well as https://jogamp.org/bugzilla/show_bug.cgi?id=1357

Now, the problem is that we have to wait for 2.3.3: http://forum.jogamp.org/how-can-I-build-jogl-2-3-3-and-when-is-it-due-for-release-td4038662.html#a4038675

**Comment by AlexisDrogoul** [comment] 2018-07-25 01:23
I have experimented the temporary solution proposed in http://forum.jogamp.org/how-can-I-build-jogl-2-3-3-and-when-is-it-due-for-release-td4038662.html#a4038675 (i.e. a fat jar containing the bug fix for this problem). It seems to be working well. Can you try it ? 

Steps to follow:

 - download the fat jar from here: https://sourceforge.net/p/tuer/code/1319/tree//pre_beta/lib/jogamp/jogamp-fat.jar?format=raw
 - drop it in `ummisco.gama.opengl` (directly at the root of the project)
- open `plugin.xml`, go to the `Runtime` tab and remove all the entries of the Classpath except `.`. Then add `jogamp-fat.jar`.

Tell me if it solves your problem, in which case we might consider pushing this solution to the server.

**Comment by ptaillandier** [comment] 2018-07-25 07:31
Hi,

Yes, it works. Thanks Alexis.

Patrick

2018-07-25 3:23 GMT+02:00 Alexis Drogoul <notifications@github.com>:

**Comment by AlexisDrogoul** [comment] 2018-07-25 07:50
OK. It's good. So what should we do ? @nghi, do we have the possibility to have two different versions of the ummisco.gama.opengl plugin, one for Linux (with the fat jar and a different MANIFEST.MF) and one for Windows and MacOS X (with the current installation) ? Or do we replace directly the current installation (seems to work well under MacOS X) with the new one ?

**Comment by hqnghi88** [comment] 2018-07-25 10:10
Dear Alexis,
Maven has some documents but I did not success to separate the profiles depend on OS. Iam retrying.

**Comment by AlexisDrogoul** [comment] 2018-07-25 10:12
@hqnghi88  don't spend too much time on it. We can just temporarily replace the different jars by the fat jar (we'll put them back when the official 2.3.3 version will be released). I can do it almost immediately (actually, my local version is running on the fat jar).

**Comment by AlexisDrogoul** [comment] 2018-07-25 13:21
I'll push in a few minutes a version with the fat jar (but the other jars are still there, just the classpath is changed. So dont be afraid if the whole GAMA grows by 10++ MB.

**Closed** 2018-07-25 14:04 UTC
Labels: Affects Usability, Display OpenGL, OS Linux
