### ISSUE TITLE
Freeze: when opening a models folder in the Library

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#1418] opened 2016-01-17 17:41 UTC
I get the following deadlock report after having tried to open a models folder (in ants).
Note that GAMA had crashed previoussly and I have not created a new workspace at this run.

Java-level deadlock detected
 
This means that some threads are blocked waiting to enter a synchronization block or
waiting to reenter a synchronization block after an Object.wait() call, where each thread
owns one monitor while trying to obtain another monitor already held by another thread.
 
Deadlock:

Worker-0 is waiting to lock org.eclipse.xtext.internal.ResourceServiceProviderDescriptor@1a10f943 which is held by Worker-3
Worker-3 is waiting to lock java.util.Collections$SynchronizedMap@36fa471c which is held by Worker-0

Thread stacks

Worker-0 [BLOCKED; waiting to lock org.eclipse.xtext.internal.ResourceServiceProviderDescriptor@1a10f943]
 org.eclipse.xtext.internal.ResourceServiceProviderDescriptor.get(ResourceServiceProviderDescriptor.java:38)
 org.eclipse.xtext.resource.impl.ResourceServiceProviderRegistryImpl$InternalData.getServiceProvider(ResourceServiceProviderRegistryImpl.java:46)
 org.eclipse.xtext.resource.impl.ResourceServiceProviderRegistryImpl.getResourceServiceProvider(ResourceServiceProviderRegistryImpl.java:109)
 org.eclipse.xtext.resource.impl.ResourceServiceProviderRegistryImpl.getResourceServiceProvider(ResourceServiceProviderRegistryImpl.java:129)
 msi.gama.lang.utils.EGaml.getInstance(EGaml.java:329)
 msi.gama.lang.utils.GamlExpressionCompiler.getFreshResource(GamlExpressionCompiler.java:918)
 msi.gama.lang.utils.GamlExpressionCompiler.getEObjectOf(GamlExpressionCompiler.java:935)
 msi.gama.lang.utils.GamlExpressionCompiler.compile(GamlExpressionCompiler.java:92)
 msi.gaml.expressions.GamlExpressionFactory.createExpr(GamlExpressionFactory.java:102)
 msi.gaml.descriptions.BasicExpressionDescription.compile(BasicExpressionDescription.java:82)
 msi.gaml.descriptions.SymbolDescription.compileTypeProviderFacets(SymbolDescription.java:108)
 msi.gaml.descriptions.SymbolDescription.getType(SymbolDescription.java:353)
 msi.gaml.descriptions.VariableDescription.getType(VariableDescription.java:133)
 msi.gaml.descriptions.VariableDescription.getDocumentation(VariableDescription.java:237)
 msi.gama.lang.gaml.resource.GamlResourceDocManager$Documentation.<init>(GamlResourceDocManager.java:67)
 msi.gama.lang.gaml.resource.GamlResourceDocManager.getGamlDocumentation(GamlResourceDocManager.java:176)
 msi.gaml.factories.DescriptionFactory.getGamlDocumentation(DescriptionFactory.java:44)
 msi.gama.lang.gaml.scoping.BuiltinGlobalScopeProvider.addVar(BuiltinGlobalScopeProvider.java:329)
 msi.gama.lang.gaml.scoping.BuiltinGlobalScopeProvider.createDescriptions(BuiltinGlobalScopeProvider.java:408)
 msi.gama.lang.gaml.scoping.BuiltinGlobalScopeProvider.<clinit>(BuiltinGlobalScopeProvider.java:440)
 sun.reflect.NativeConstructorAccessorImpl.newInstance0(native method)
 sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
 sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
 java.lang.reflect.Constructor.newInstance(Constructor.java:422)
 com.google.inject.internal.DefaultConstructionProxyFactory$1.newInstance(DefaultConstructionProxyFactory.java:85)
 com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:85)
 com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:254)
 com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:54)
 com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
 com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1031)
 com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
 com.google.inject.Scopes$1$1.get(Scopes.java:65)
 com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:40)
 com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:204)
 com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:198)
 com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1024)
 com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:198)
 com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:179)
 com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:109)
 com.google.inject.Guice.createInjector(Guice.java:95)
 com.google.inject.Guice.createInjector(Guice.java:72)
 com.google.inject.Guice.createInjector(Guice.java:62)
 msi.gama.lang.gaml.ui.internal.GamlActivator.createInjector(GamlActivator.java:67)
 msi.gama.lang.gaml.ui.internal.GamlActivator.getInjector(GamlActivator.java:55)
 msi.gama.lang.gaml.ui.GamlExecutableExtensionFactory.getInjector(GamlExecutableExtensionFactory.java:26)
 org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory.create(AbstractGuiceAwareExecutableExtensionFactory.java:51)
 org.eclipse.core.internal.registry.ConfigurationElement.createExecutableExtension(ConfigurationElement.java:262)
 org.eclipse.core.internal.registry.ConfigurationElementHandle.createExecutableExtension(ConfigurationElementHandle.java:55)
 org.eclipse.emf.ecore.plugin.RegistryReader$PluginClassDescriptor.createInstance(RegistryReader.java:167)
 org.eclipse.emf.ecore.plugin.RegistryReader$ResourceFactoryDescriptor.createFactory(RegistryReader.java:189)
 org.eclipse.emf.ecore.resource.impl.ResourceFactoryRegistryImpl.convert(ResourceFactoryRegistryImpl.java:92)
 org.eclipse.emf.ecore.resource.impl.ResourceSetImpl$2.delegatedGetFactory(ResourceSetImpl.java:458)
 org.eclipse.emf.ecore.resource.impl.ResourceFactoryRegistryImpl.getFactory(ResourceFactoryRegistryImpl.java:144)
 org.eclipse.emf.ecore.resource.impl.ResourceFactoryRegistryImpl.getFactory(ResourceFactoryRegistryImpl.java:85)
 org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.createResource(ResourceSetImpl.java:431)
 org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.createResource(ResourceSetImpl.java:423)
 org.eclipse.xtext.resource.SynchronizedXtextResourceSet.createResource(SynchronizedXtextResourceSet.java:32)
 msi.gama.lang.gaml.resource.GamlModelBuilder.getInfo(GamlModelBuilder.java:158)
 msi.gaml.factories.ModelFactory.getInfo(ModelFactory.java:143)
 msi.gama.gui.navigator.FileMetaDataProvider.createGamlFileMetaData(FileMetaDataProvider.java:280)
 msi.gama.gui.navigator.FileMetaDataProvider.getMetaData(FileMetaDataProvider.java:211)
 msi.gama.gui.navigator.NavigatorBaseLighweightDecorator.decorate(NavigatorBaseLighweightDecorator.java:25)
 org.eclipse.ui.internal.decorators.LightweightDecoratorDefinition.decorate(LightweightDecoratorDefinition.java:273)
 org.eclipse.ui.internal.decorators.LightweightDecoratorManager$LightweightRunnable.run(LightweightDecoratorManager.java:83)
 org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
 org.eclipse.ui.internal.decorators.LightweightDecoratorManager.decorate(LightweightDecoratorManager.java:367)
 org.eclipse.ui.internal.decorators.LightweightDecoratorManager.getDecorations(LightweightDecoratorManager.java:349)
 org.eclipse.ui.internal.decorators.DecorationScheduler$1.ensureResultCached(DecorationScheduler.java:372)
 org.eclipse.ui.internal.decorators.DecorationScheduler$1.run(DecorationScheduler.java:332)
 org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

Worker-3 [BLOCKED; waiting to lock java.util.Collections$SynchronizedMap@36fa471c]
 msi.gama.lang.gaml.ui.internal.GamlActivator.getInjector(GamlActivator.java:53)
 msi.gama.lang.gaml.ui.GamlExecutableExtensionFactory.getInjector(GamlExecutableExtensionFactory.java:26)
 org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory.create(AbstractGuiceAwareExecutableExtensionFactory.java:51)
 org.eclipse.core.internal.registry.ConfigurationElement.createExecutableExtension(ConfigurationElement.java:262)
 org.eclipse.core.internal.registry.ConfigurationElementHandle.createExecutableExtension(ConfigurationElementHandle.java:55)
 org.eclipse.xtext.internal.ResourceServiceProviderDescriptor.get(ResourceServiceProviderDescriptor.java:40)
 org.eclipse.xtext.resource.impl.ResourceServiceProviderRegistryImpl$InternalData.getServiceProvider(ResourceServiceProviderRegistryImpl.java:46)
 org.eclipse.xtext.resource.impl.ResourceServiceProviderRegistryImpl.getResourceServiceProvider(ResourceServiceProviderRegistryImpl.java:109)
 org.eclipse.xtext.resource.impl.ResourceServiceProviderRegistryImpl.getResourceServiceProvider(ResourceServiceProviderRegistryImpl.java:129)
 org.eclipse.xtext.ui.resource.UriValidator.isValid(UriValidator.java:27)
 org.eclipse.xtext.ui.resource.Storage2UriMapperImpl.isValidUri(Storage2UriMapperImpl.java:247)
 org.eclipse.xtext.ui.resource.Storage2UriMapperImpl.getUri(Storage2UriMapperImpl.java:233)
 org.eclipse.xtext.builder.impl.ToBeBuiltComputer.getUri(ToBeBuiltComputer.java:345)
 org.eclipse.xtext.builder.impl.ToBeBuiltComputer.updateStorage(ToBeBuiltComputer.java:287)
 org.eclipse.xtext.builder.impl.ToBeBuiltComputer$2.visit(ToBeBuiltComputer.java:260)
 org.eclipse.core.internal.resources.Resource$2.visit(Resource.java:119)
 org.eclipse.core.internal.resources.Resource$1.visitElement(Resource.java:83)
 org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:82)
 org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:87)
 org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:87)
 org.eclipse.core.internal.watson.ElementTreeIterator.iterate(ElementTreeIterator.java:129)
 org.eclipse.core.internal.resources.Resource.accept(Resource.java:93)
 org.eclipse.core.internal.resources.Resource.accept(Resource.java:51)
 org.eclipse.core.internal.resources.Resource.accept(Resource.java:116)
 org.eclipse.core.internal.resources.Resource.accept(Resource.java:104)
 org.eclipse.xtext.builder.impl.ToBeBuiltComputer.updateProject(ToBeBuiltComputer.java:254)
 org.eclipse.xtext.builder.impl.ToBeBuiltComputer.updateProjectNewResourcesOnly(ToBeBuiltComputer.java:221)
 org.eclipse.xtext.builder.impl.XtextBuilder.fullBuild(XtextBuilder.java:278)
 org.eclipse.xtext.builder.impl.XtextBuilder.build(XtextBuilder.java:117)
 org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:734)
 org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
 org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:205)
 org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:329)
 org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:404)
 org.eclipse.core.internal.resources.Project$1.run(Project.java:556)
 org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2241)
 org.eclipse.core.internal.resources.Project.internalBuild(Project.java:534)
 org.eclipse.core.internal.resources.Project.build(Project.java:119)
 org.eclipse.xtext.builder.impl.BuildScheduler$BuildJob.run(BuildScheduler.java:164)
 org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

Frozen threads found (potential deadlock)
 
It seems that the following threads have not changed their stack for more than 10 seconds.
These threads are possibly (but not necessarily!) in a deadlock or hung.
 
main <--- Frozen for at least 15 sec
msi.gama.lang.gaml.ui.internal.GamlActivator.getInjector(String) GamlActivator.java:53
msi.gama.lang.gaml.ui.GamlExecutableExtensionFactory.getInjector() GamlExecutableExtensionFactory.java:26
org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory.create() AbstractGuiceAwareExecutableExtensionFactory.java:51
org.eclipse.core.internal.registry.ConfigurationElement.createExecutableExtension(String) ConfigurationElement.java:262
org.eclipse.core.internal.registry.ConfigurationElementHandle.createExecutableExtension(String) ConfigurationElementHandle.java:55
org.eclipse.emf.ecore.plugin.RegistryReader$PluginClassDescriptor.createInstance() RegistryReader.java:167
org.eclipse.emf.ecore.plugin.RegistryReader$ResourceFactoryDescriptor.createFactory() RegistryReader.java:189
org.eclipse.emf.ecore.resource.impl.ResourceFactoryRegistryImpl.convert(Object) ResourceFactoryRegistryImpl.java:92
org.eclipse.emf.ecore.resource.impl.ResourceSetImpl$2.delegatedGetFactory(URI, String) ResourceSetImpl.java:458
org.eclipse.emf.ecore.resource.impl.ResourceFactoryRegistryImpl.getFactory(URI, Map, Map, Map, String, boolean) ResourceFactoryRegistryImpl.java:144
org.eclipse.emf.ecore.resource.impl.ResourceFactoryRegistryImpl.getFactory(URI, String) ResourceFactoryRegistryImpl.java:85
org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.createResource(URI, String) ResourceSetImpl.java:431
org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.createResource(URI) ResourceSetImpl.java:423
org.eclipse.xtext.resource.SynchronizedXtextResourceSet.createResource(URI) SynchronizedXtextResourceSet.java:32
msi.gama.lang.gaml.resource.GamlModelBuilder.getInfo(URI, long) GamlModelBuilder.java:158
msi.gaml.factories.ModelFactory.getInfo(URI, long) ModelFactory.java:143
msi.gama.gui.navigator.FileMetaDataProvider.createGamlFileMetaData(IFile) FileMetaDataProvider.java:280
msi.gama.gui.navigator.FileMetaDataProvider.getMetaData(Object, boolean) FileMetaDataProvider.java:211
msi.gama.gui.navigator.NavigatorContentProvider.getChildren(Object) NavigatorContentProvider.java:64
msi.gama.gui.navigator.NavigatorContentProvider.hasChildren(Object) NavigatorContentProvider.java:138
org.eclipse.ui.internal.navigator.extensions.SafeDelegateTreeContentProvider.hasChildren(Object) SafeDelegateTreeContentProvider.java:112
org.eclipse.ui.internal.navigator.NavigatorContentServiceContentProvider.callNormalHasChildren(Object, Object, SafeDelegateTreeContentProvider) NavigatorContentServiceContentProvider.java:444
org.eclipse.ui.internal.navigator.NavigatorContentServiceContentProvider.access$4(NavigatorContentServiceContentProvider, Object, Object, SafeDelegateTreeContentProvider) NavigatorContentServiceContentProvider.java:439
org.eclipse.ui.internal.navigator.NavigatorContentServiceContentProvider$3.run() NavigatorContentServiceContentProvider.java:407
org.eclipse.core.runtime.SafeRunner.run(ISafeRunnable) SafeRunner.java:42
org.eclipse.ui.internal.navigator.NavigatorContentServiceContentProvider.hasChildren(Object) NavigatorContentServiceContentProvider.java:392
org.eclipse.ui.internal.navigator.NavigatorContentServiceContentProvider.hasChildren(TreePath) NavigatorContentServiceContentProvider.java:436
org.eclipse.jface.viewers.AbstractTreeViewer.isExpandable(Object) AbstractTreeViewer.java:2131
org.eclipse.jface.viewers.TreeViewer.isExpandable(Object) TreeViewer.java:553
org.eclipse.jface.viewers.AbstractTreeViewer.isExpandable(Item, TreePath, Object) AbstractTreeViewer.java:2169
org.eclipse.jface.viewers.AbstractTreeViewer.updatePlus(Item, Object) AbstractTreeViewer.java:2861
org.eclipse.jface.viewers.TreeViewer.updatePlus(Item, Object) TreeViewer.java:804
org.eclipse.jface.viewers.AbstractTreeViewer.createTreeItem(Widget, Object, int) AbstractTreeViewer.java:844
org.eclipse.jface.viewers.AbstractTreeViewer$1.run() AbstractTreeViewer.java:818
org.eclipse.swt.custom.BusyIndicator.showWhile(Display, Runnable) BusyIndicator.java:70
org.eclipse.jface.viewers.AbstractTreeViewer.createChildren(Widget, boolean) AbstractTreeViewer.java:791
org.eclipse.jface.viewers.TreeViewer.createChildren(Widget, boolean) TreeViewer.java:611
org.eclipse.jface.viewers.AbstractTreeViewer.createChildren(Widget) AbstractTreeViewer.java:762
org.eclipse.jface.viewers.AbstractTreeViewer.handleTreeExpand(TreeEvent) AbstractTreeViewer.java:1493
org.eclipse.jface.viewers.TreeViewer.handleTreeExpand(TreeEvent) TreeViewer.java:903
org.eclipse.jface.viewers.AbstractTreeViewer$4.treeExpanded(TreeEvent) AbstractTreeViewer.java:1505
org.eclipse.swt.widgets.TypedListener.handleEvent(Event) TypedListener.java:132
org.eclipse.swt.widgets.EventTable.sendEvent(Event) EventTable.java:84
org.eclipse.swt.widgets.Display.sendEvent(EventTable, Event) Display.java:4230
org.eclipse.swt.widgets.Widget.sendEvent(Event) Widget.java:1491
org.eclipse.swt.widgets.Widget.sendEvent(int, Event, boolean) Widget.java:1514
org.eclipse.swt.widgets.Widget.sendEvent(int, Event) Widget.java:1499
org.eclipse.swt.widgets.TreeItem.sendExpand(boolean, boolean) TreeItem.java:1036
org.eclipse.swt.widgets.Tree.expandItem_expandChildren(long, long, long, boolean) Tree.java:1256
org.eclipse.swt.widgets.Display.windowProc(long, long, long, long) Display.java:5955
org.eclipse.swt.internal.cocoa.OS.objc_msgSendSuper(objc_super, long, long) OS.java (native)
org.eclipse.swt.widgets.Widget.callSuper(long, long, long) Widget.java:227
org.eclipse.swt.widgets.Widget.mouseDownSuper(long, long, long) Widget.java:1121
org.eclipse.swt.widgets.Tree.mouseDownSuper(long, long, long) Tree.java:2047
org.eclipse.swt.widgets.Widget.mouseDown(long, long, long) Widget.java:1113
org.eclipse.swt.widgets.Control.mouseDown(long, long, long) Control.java:2569
org.eclipse.swt.widgets.Tree.mouseDown(long, long, long) Tree.java:2015
org.eclipse.swt.widgets.Display.windowProc(long, long, long) Display.java:5692
org.eclipse.swt.internal.cocoa.OS.objc_msgSendSuper(objc_super, long, long) OS.java (native)
org.eclipse.swt.widgets.Widget.callSuper(long, long, long) Widget.java:227
org.eclipse.swt.widgets.Widget.windowSendEvent(long, long, long) Widget.java:2130
org.eclipse.swt.widgets.Shell.windowSendEvent(long, long, long) Shell.java:2337
org.eclipse.swt.widgets.Display.windowProc(long, long, long) Display.java:5756
org.eclipse.swt.internal.cocoa.OS.objc_msgSendSuper(objc_super, long, long) OS.java (native)
org.eclipse.swt.widgets.Display.applicationSendEvent(long, long, long) Display.java:5193
org.eclipse.swt.widgets.Display.applicationProc(long, long, long) Display.java:5342
org.eclipse.swt.internal.cocoa.OS.objc_msgSend(long, long, long) OS.java (native)
org.eclipse.swt.internal.cocoa.NSApplication.sendEvent(NSEvent) NSApplication.java:128
org.eclipse.swt.widgets.Display.readAndDispatch() Display.java:3695
org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run() PartRenderingEngine.java:1127
org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm, Runnable) Realm.java:337
org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(MApplicationElement, IEclipseContext) PartRenderingEngine.java:1018
org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(MApplicationElement) E4Workbench.java:156
org.eclipse.ui.internal.Workbench$5.run() Workbench.java:654
org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm, Runnable) Realm.java:337
org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Display, WorkbenchAdvisor) Workbench.java:598
org.eclipse.ui.PlatformUI.createAndRunWorkbench(Display, WorkbenchAdvisor) PlatformUI.java:150
msi.gama.application.Application.start(IApplicationContext) Application.java:124
org.eclipse.equinox.internal.app.EclipseAppHandle.run(Object) EclipseAppHandle.java:196
org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(Object) EclipseAppLauncher.java:134
org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(Object) EclipseAppLauncher.java:104
org.eclipse.core.runtime.adaptor.EclipseStarter.run(Object) EclipseStarter.java:380
org.eclipse.core.runtime.adaptor.EclipseStarter.run(String[], Runnable) EclipseStarter.java:235
sun.reflect.NativeMethodAccessorImpl.invoke0(Method, Object, Object[]) NativeMethodAccessorImpl.java (native)
sun.reflect.NativeMethodAccessorImpl.invoke(Object, Object[]) NativeMethodAccessorImpl.java:62
sun.reflect.DelegatingMethodAccessorImpl.invoke(Object, Object[]) DelegatingMethodAccessorImpl.java:43
java.lang.reflect.Method.invoke(Object, Object[]) Method.java:497
org.eclipse.equinox.launcher.Main.invokeFramework(String[], URL[]) Main.java:669
org.eclipse.equinox.launcher.Main.basicRun(String[]) Main.java:608
org.eclipse.equinox.launcher.Main.run(String[]) Main.java:1515
org.eclipse.equinox.launcher.Main.main(String[]) Main.java:1488

process reaper <--- Frozen for at least 38 sec
java.lang.UNIXProcess$ProcessPipeInputStream.processExited() UNIXProcess.java:528
java.lang.UNIXProcess.lambda$initStreams$271() UNIXProcess.java:299
java.lang.UNIXProcess$$Lambda$7.run()
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor$Worker) ThreadPoolExecutor.java:1142
java.util.concurrent.ThreadPoolExecutor$Worker.run() ThreadPoolExecutor.java:617
java.lang.Thread.run() Thread.java:745

**Comment by AlexisDrogoul** [comment] 2016-01-17 20:24
Check again with one of the latest commits. I have slightly postponed the two operations of reading/writing back the metadata of files. This may help. Otherwise, a solution is to always wait for a full build to finish to display the children of a folder (this seems to be the cause of your problem). Strange, however, that you are the only one to have it...

**Comment by AlexisDrogoul** [comment] 2016-01-18 14:15
Seems to have been fixed by what I mentioned in the previous comment.

**Closed by AlexisDrogoul** 2016-01-18 14:15 UTC
Labels: > Bug
