### ISSUE TITLE
Switch from modelling to simulation perspective abnormally long 

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#3216] opened 2021-09-28 14:56 UTC
**Describe the bug**
This one is also hard to reproduce I guess but obvious enough on my computer to be notify. the transition from Modelling perspective to Simulation is very glitchy (not the Simulation to Modelling) and a mix of the previous simualtion persective + the current Modellign perspective is displayed as shown in the gif

So maybe it comes from the model it self (which doesn't seem to be crazy except that it use many (not to say most  of the graphical feature (mesh,text,overlay, layer, chart, visible, event, etc etc)

**To Reproduce**
1. Clone this repo https://github.com/CityScope/CSL_IDB
2. Create a new project Import -> "MESA_REDONDA"
3. Open Mesa_OD-based.gaml
4. Run experiment "mesa"

**Expected behavior**
Normal

**Screenshots**
![Screen Recording 2021-09-28 at 16 26 58 mov](https://user-images.githubusercontent.com/3928502/135112020-58f52b4d-3cfd-4f80-8c7f-38acce729895.gif)

**Desktop (please complete the following information):**
 - OS: Mac OS Catalina 
 - GAMA_1.8.2_Alpha_withJDK_Mac_09.25.21_056eab6f

**Additional context**

**Comment by agrignard** [comment] 2021-09-28 15:39
Sorry you're right the repo is private (due to some data we cannot share inside) I just sent you an invite.

Just a head up if it can help I am also testing this on a Mac Mini (Ram 32 GB, Intel UHD Graphics 630 1536Mb) the glitch is still here but it's way better. 

The screenshot that I did is on a macbook pro (Ram 16 GB, AMD Radeon R9 M370X 2 GB
Intel Iris Pro 1536 MB)

@tnguyenh on a dell (but I don't know his graphics card) is also experiencing some latency

So maybe it is link with the GPU, so it might be difficult to reproduce.

I hope this can help

**Comment by AlexisDrogoul** [comment] 2021-09-28 17:14
I can't reproduce it on macOS BigSur, JDK 15.0.2 (J9), Eclipse 2021-06, AMD Radeon Pro 5500M 8 Go.

Neither on a 34" screen nor on the HiDPI screen (below is the 34"):
![screencast 2021-09-28 23-53-30](https://user-images.githubusercontent.com/579256/135133387-19366f51-1510-45ab-a260-334134300547.gif)

The only difference that can play a role is that the release uses Eclipse 2021-03 as a foundation (for reasons explained here: https://github.com/gama-platform/gama/issues/3199#issuecomment-924585467). Can you test the git version using Eclipse 2021-06 and see if the problem persists ?

**Comment by agrignard** [comment] 2021-09-28 17:35
After some back and forth test I might have found (one of) the guilty.

I notice the glitch is less strong (but sill here) without overlay

**Comment by agrignard** [comment] 2021-10-01 10:49
I don't see it anymore with this version.  ```MacOS-jdk15-OpenJ9-SWT_2021-09```

**Comment by agrignard** [comment] 2021-10-01 10:52
But the overlay is now weird...
<img width="750" alt="Screenshot 2021-10-01 at 12 51 24" src="https://user-images.githubusercontent.com/3928502/135608244-761a0012-dc5f-461c-9bcb-b458e00099c5.png">

**Comment by AlexisDrogoul** [comment] 2021-10-01 13:16
Great. This will be the official combination for the release on macOS. 
I close this issue for now on.

**Closed by AlexisDrogoul** 2021-10-01 13:16 UTC
Labels: 🙅🏻‍♂️ Affects Usability, ❌ * Not reproducible, Version 1.8.2
