### ISSUE TITLE
Crash when try to display chart using opengl (Windows OS)

### ISSUE THREAD

**Issue by mazarsju** [gama-platform/gama#1321] opened 2015-12-04 04:12 UTC
GAMA crashes when we try to display chart using opengl in Windows.

Here is an example of model:

model my_first_model

global
{
	int numberA <- 2 update:numberA*2;
	int numberB <- 10000 update:numberB-1000;
}

experiment my_experiment type: gui {
	output {
		display "my_display" type:opengl {
			chart "my_pie_chart" type:pie {
				datalist ["numberA","numberB"] value:[numberA,numberB] color:[#red,#blue];
			}
		}
	}
}

**Comment by mazarsju** [comment] 2015-12-04 04:17
Error message on Eclipse :-1: 


# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x0000000053452ea9, pid=6216, tid=7760
#
# JRE version: Java(TM) SE Runtime Environment (8.0_11-b12) (build 1.8.0_11-b12)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.11-b03 mixed mode windows-amd64 compressed oops)
# Problematic frame:
# C  [atio6axx.dll+0x17a2ea9]
#
# Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
#
# An error report file with more information is saved as:
# F:\Eclipse\eclipse\hs_err_pid6216.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.sun.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.

See also log attached
[hs_err_pid6216.txt](https://github.com/gama-platform/gama/files/51636/hs_err_pid6216.txt)

**Comment by AlexisDrogoul** [comment] 2015-12-04 09:12
Closed as a duplicate of #1288

**Closed by AlexisDrogoul** 2015-12-04 09:12 UTC
Labels: > Bug, Display OpenGL, OS Windows
