### ISSUE TITLE
GUI - Fix displayed button, Icone or legend

### ISSUE THREAD

**Issue by gnoubi** [gama-platform/gama#1408] opened 2016-01-17 02:03 UTC
There are no method to implement fix located button, icone or legend on a display even if the zoom or display center of a window is changing. Showing a legend is an often question I have. Showing fix button or agent is important to increase the usability of a participative model

**Comment by AlexisDrogoul** [comment] 2016-01-17 02:09
Duplicate of #1326 (where I'm still awaiting your comments, by the way :) )

**Closed by AlexisDrogoul** 2016-01-17 02:09 UTC
