### ISSUE TITLE
Facet Camera location Broken 

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#3290] opened 2022-01-25 07:21 UTC
**Describe the bug**
Copy a camera location facet and past it in any display 

e.g 
`````
camera_location: {267.3999,449.0795,744.0471} camera_target: {267.3999,449.0665,0} camera_orientation: {0.0,1.0,0.0}
`````

**Expected behavior**
Working 

**Screenshots**
<img width="754" alt="Screenshot 2022-01-25 at 08 21 00" src="https://user-images.githubusercontent.com/3928502/150929745-189bc51c-d882-4fdf-a63c-93739fa68351.png">

**Desktop (please complete the following information):**
 - Mac OS
 - Gama 1.8.2 last realeae

**Additional context**

**Comment by agrignard** [comment] 2022-01-25 07:24
It seems to be related more specifically to the facet camera_target 

`````
camera_location: {267.3999,449.0795,744.0471}  camera_orientation: {0.0,1.0,0.0}
``````

"work" but gives not the desired results

**Comment by AlexisDrogoul** [comment] 2022-01-25 08:08
Seems to be a duplicate of #3279 -- although it is difficult to understand the second comment. What does `"work" but gives not the desired results` mean ?

**Comment by agrignard** [comment] 2022-01-28 11:03
By "work" I mean it compiles and the display can be instantiatated (not with the right camera position) but you can see something, whereas with the full facet camera_target the display is freezed.

Sorry I couldn't take  spend more time on this I will try to test it more sooner

**Comment by agrignard** [comment] 2022-01-31 11:48
It seems to be indeed a duplicate of the #3279. Do we want to close one of this 2 issues?

**Comment by AlexisDrogoul** [comment] 2022-02-05 04:48
Yes it is a duplicate. Closing this one.

**Closed by AlexisDrogoul** 2022-02-05 04:48 UTC
Labels: 😱 Bug, 🖥 Display OpenGL, Priority High
