### ISSUE TITLE
Invasive copy/paste of camera parameters

### ISSUE THREAD

**Issue by tnguyenh** [gama-platform/gama#2897] opened 2019-10-18 12:09 UTC
**Describe the bug**
When running some models that specify the camera position, look_pos, etc, the parameters of the camera is constantly copied to the computer clip board, erasing any other content that has been copied.

**To Reproduce**

Run the following model. Open any program in which you can type text (Gama editor, Notepad, ...) and keep pasting. The camera parameters are pasted, like this:

camera_pos: {-117.2808,240.9944,250.0} camera_look_pos: {50.0,50.0,106.6337} camera_up_vector: {0.324,0.3699,0.8708} 
camera_pos: {-171.2674,174.5088,250.0} camera_look_pos: {50.0,50.0,106.6337} camera_up_vector: {0.4283,0.2414,0.8708} 
camera_pos: {-181.4959,154.2657,250.0} camera_look_pos: {50.0,50.0,106.6337} camera_up_vector: {0.4482,0.2023,0.8708} 
camera_pos: {-195.9586,112.9766,250.0} camera_look_pos: {50.0,50.0,106.6337} camera_up_vector: {0.4762,0.1225,0.8708} 
...

I precise that the model is running while I am writing this. I kept pressing ctrl+V without leaving the current window (no copy action or anything else).

**Desktop (please complete the following information):**
 - OS: Windows 10
 - PC Model: HP Zbook g2
 - GAMA version: 1.8, Git
 - Java version: embedded JDK so I don't know.
 - Graphics cards / Display system: [can be useful for displays, OpenGL problems]

**Additional context**

Current model:

```gaml

model tree

global {
	int video_cycle_nb parameter: 'Video duration' category: "Parameters" step: 1000 min: 10000 max:100000 <- 28000 ;
	int camera_z_offset parameter: 'Camera height' category: "Parameters" step: 10 min: 10 max: 500 <- 250;
	float length_max <- 100.0;
	float level_step <- 0.8;
	float width <- 100.0;//shape.width;
	float height <- 100.0;//shape.height;
	float env_size <- 0.5 * length_max / (1 - level_step);
	point seed_pos <- {width / 2, height / 2};
  
	
	init {
		create plant_seed {
			location <- seed_pos;
		}
	}
}




species plant_seed {

	aspect default {
		draw
		polygon([location + {env_size / 2, 0, -1}, location + {0.5 * env_size / 2, 0.86 * env_size / 2, -1}, location + {-0.5 * env_size / 2, 0.86 * env_size / 2, -1}, location + {-env_size / 2, 0, -1}, location + {-0.5 * env_size / 2, -0.86 * env_size / 2, -1}, location + {0.5 * env_size / 2, -0.86 * env_size / 2, -1}])
		color: #green border: #green;
		draw cone3D(6, 6) at: location color: rgb(108, 122, 137);
		draw polygon([location + {0, 0, 3}, location + {env_size / 6, 0, 0}, location + {0.5 * env_size / 6, 0.86 * env_size / 6, 0}]) color: rgb(135, 121, 78) border:
		rgb(135, 121, 78);
		draw polygon([location + {0, 0, 3}, location + {0.5 * env_size / 6, 0.86 * env_size / 6, 0}, location + {-0.5 * env_size / 6, 0.86 * env_size / 6, 0}]) color: rgb(115, 101, 58)
		border: rgb(115, 101, 58);
		draw polygon([location + {0, 0, 3}, location + {-0.5 * env_size / 6, 0.86 * env_size / 6, 0}, location + {-env_size / 6, 0, 0}]) color: rgb(115, 101, 58) border:
		rgb(115, 101, 58);
		draw polygon([location + {0, 0, 3}, location + {-env_size / 6, 0, 0}, location + {-0.5 * env_size / 6, -0.86 * env_size / 6, 0}]) color: rgb(135, 121, 78) border:
		rgb(135, 121, 78);
		draw polygon([location + {0, 0, 3}, location + {-0.5 * env_size / 6, -0.86 * env_size / 6, 0}, location + {0.5 * env_size / 6, -0.86 * env_size / 6, 0}]) color:
		rgb(135, 121, 78) border: rgb(135, 121, 78);
		draw polygon([location + {0, 0, 3}, location + {0.5 * env_size / 6, -0.86 * env_size / 6, 0}, location + {env_size / 6, 0, 0}]) color: rgb(135, 121, 78) border:
		rgb(135, 121, 78);
	}

}



experiment "Random" type: gui autorun: true  {
	float minimum_cycle_duration <- 0.001;
	output {
			display 'Tree' type: opengl background: #blue ambient_light: 150 draw_env: false toolbar: false fullscreen: true 
			camera_pos: {50,50, camera_z_offset} + ({-66.4803 - 50, 275.5971 - 50, 0} rotated_by(cycle/200::{0,0,1})) camera_look_pos: {50, 50, 106.6337} camera_up_vector: {0.2488, 0.4679, 0.8481} {
		}

	}

}
```

**Comment by AlexisDrogoul** [comment] 2019-10-19 03:18
Well, this is the intended behaviour as soon as the camera parameters are changed in a way or another (seems to be the case here, no ?)

**Comment by tnguyenh** [comment] 2019-10-19 14:12
You mean that each time the camera parameters are changed, the new parameters are automatically copied to the clipboard ?

**Comment by AlexisDrogoul** [comment] 2019-12-10 12:09
A bit long to answer, sorry, but yes. Should we close this issue ?

**Comment by agrignard** [comment] 2020-01-07 08:40
I have to admit that I was also a bit surprised by this behavior

What is weird for me is that a someone using  a software A (Gama Platform) might be able to copy something not relevant at all in a software B (textedit for instance)

**Comment by AlexisDrogoul** [comment] 2020-02-14 15:00
@agrignard that's how clipboards work 😄 
More seriously: it's a workaround while we don't have a proper way to save the definition of a display in an experiment. And it prevents the user from having to open the side controls to copy the facets if he/she wants to preserve the position of the camera. I can always add a preference to toggle this if this is really annoying.

**Comment by hqnghi88** [comment] 2020-02-14 15:08
Dear Alexis,
I think Tri (and may be others windows user) has a real problem. The fact is that we did not intended to copy something about camera pos, we are working with some other apps, we copied some text into clipboard, we switch to gama to check the simulation, we return to others apps, and boom, clipboard is filled by long text of the cam param.... 
Is there any reason/thread that auto copy these params by display threads?

**Comment by AlexisDrogoul** [comment] 2020-02-14 15:21
The parameters of the camera are only copied if the values are changed. Either by the user or if you declare a rotation / change in your display. So it is not every display that exhibits it. For me it makes sense to do it as soon as the camera is changed. But we can always put a preference... 🙄

**Comment by hqnghi88** [comment] 2020-02-14 15:24
I did not tested again,  but i have impression that it is copied on display activated/focused, not on rotated/changed. But may be i m wrong. And a preference is fine for me.
Cheers.

**Closed** 2020-02-15 06:50 UTC
Labels: OS Windows, Priority Low, Version 1.8.0, Version Git, 😱 > Bug

**Comment by agrignard** [comment] 2020-02-19 23:39
Ok cool , the preference is a good option!
