### ISSUE TITLE
Phantom (grey) views appearing in the modelling perspective

### ISSUE THREAD

**Issue by sriramab** [gama-platform/gama#2515] opened 2018-08-16 08:44 UTC
Please see the attached pic, I am getting this strange gray box to the top right corner of the editor and also the editor for current model behaves strange in a sense that it is not full size to the window. This continues to the simulation mode but disappears in full screen mode.

![graybox](https://user-images.githubusercontent.com/12668606/44198143-dba80280-a140-11e8-9d73-3232dfa0afbf.JPG)

or sometimes like squeezed as in this pic.

![squeezedcapture](https://user-images.githubusercontent.com/12668606/44198266-3e010300-a141-11e8-85d4-bc8f945793af.JPG)

Is something wrong with my settings?

Version 16.08.2018 continuous, windows 7

**Comment by AlexisDrogoul** [comment] 2018-08-16 10:49
What is the context ? Immediately after launching, after an experiment ?

**Comment by sriramab** [comment] 2018-08-16 10:55
Yes, when I launch GAMA and when I close simulation mode: so two occasions.

**Comment by AlexisDrogoul** [comment] 2018-08-16 10:59
Looks like your workbench settings of the modelling perspective have been corrupted. Two things to try:

- 1 Views / Others... / Reset Perspective...
- 2 Switch temporarily to another workspace if the above does not work

Otherwise I honestly don't see where it can come from.

**Comment by sriramab** [comment] 2018-08-16 11:08
Option 1 did not help. Option 2 solves the issue.

**Comment by agrignard** [comment] 2018-08-16 13:41
I also notice this behavior however it is hard to document and reproduce and didn't push an issue however it seems I'm not the ony one so I reopen it. 

In my case this is what I have sometime (a grey interactive console windows even if I have the interactive console in the bottom left corner) 
<img width="1919" alt="screen shot 2018-08-16 at 09 37 04" src="https://user-images.githubusercontent.com/3928502/44211863-f75adb00-a137-11e8-92e9-4f60fdbfc8d0.png">

Then this is what I get after doing a reset persepctive (without relaunching the simulation) 

<img width="1920" alt="screen shot 2018-08-16 at 09 37 56" src="https://user-images.githubusercontent.com/3928502/44211954-1b1e2100-a138-11e8-99bb-17d1ded7863c.png">

and then of course it s reworking after switching workspace (which is not something you really want to do)

<img width="1919" alt="screen shot 2018-08-16 at 09 39 52" src="https://user-images.githubusercontent.com/3928502/44212097-6f290580-a138-11e8-909a-99c6ed4e063e.png">
 

GAMA1.8_Mac_64_08.15.18_2ef8bfc

**Comment by AlexisDrogoul** [comment] 2018-08-16 15:14
Hi,

Please do not reopen these kinds of issues without a way to reproduce them,
as they are likely the fruit of a corruption of the workbench.xmi file,
which originates from previous manipulations (freezes, errors, force
quitting, or - probably the most common among developers  - running several
instances of GAMA in parallel on the same workspace). By the way, deleting
the workbench.xmi file is the best way to cure this (as it is the case in
Eclipse), changing workspaces is just a way to avoid reloading a corrupt
xmi file.

So, until we have reproducible scenarios, I will close this.



Le jeu. 16 août 2018 à 20:41, Arnaud Grignard <notifications@github.com> a
écrit :

**Comment by agrignard** [comment] 2018-08-16 20:31
I get the point that if issue are not reproductible they shouldn't be here however this one is very hard to reproduce especially because it happens in different configuration that indeed seems to be linked to a workspace corruption. So I guess we can keep on trying to track it 

So I got this rendering now that appears a crash of GAMA due to too much memory used (I am playing with some point cloud file so this one was more than 500K object).

<img width="1920" alt="screen shot 2018-08-16 at 16 27 15" src="https://user-images.githubusercontent.com/3928502/44233261-57ba3e80-a171-11e8-9de8-3a3e513d8f00.png">

As a side note I have the impression that workspace are a bit more sensitive those days, I mean I use to work for a while in the same workspace, I am now creating new workspace quiet often.

**Comment by AlexisDrogoul** [comment] 2018-08-19 01:38
I have implemented a different strategy in the "Reset Perspective..." menu command. This will now restart GAMA and explicitly instruct the workbench to not load the corrupted `workbench.xmi` file at startup (i.e. equivalent to ditching this file or adding `-clearPersistedState` to the developer run configuration). GAMA will then lose memory of the opened editors but will normally clean whatever garbage has accumulated over the runs.

**Comment by AlexisDrogoul** [comment] 2018-08-19 02:33
With this new command, the modeler can restart GAMA in a pristine state without having to deal with command line arguments or deleting files from the .metadata directory. Since there is no way to know if a workbench.xmi file is corrupted from the point of view of the modeler, it is the only fix that can be provided to this. So I will close this issue -- but do not hesitate to report success or failures running this command.

**Closed by AlexisDrogoul** 2018-08-19 02:33 UTC
Labels: > Bug, Concerns Interface
