### ISSUE TITLE
csv_file to matrix crashes : index_out_of_bound

### ISSUE THREAD

**Issue by corentinjuvigny** [gama-platform/gama#3284] opened 2022-01-20 13:45 UTC
**Describe the bug**

while opening a csv file of my own, sometimes the cast form the csv_file to a matrix crashes with error "index out of bound"

**To Reproduce**

1. when trying to open file a csv file name warehouses.csv containing :

```
35.9257,69.6817,4,iron,145376,5.67662,wood,2167.77,13.9209,plastic,76.7917,0.110895,concrete,2275.46,47.3281,
91.247,63.3338,3,iron,165538,6.22904,plastic,210.265,0.26907,concrete,1531.4,18.6448,
```

2. when using ```matrix mat <- matrix(csv_file(...))```

3. error thrown :   

`Java error: index out  of bounds`

**Expected behavior**

With a csv file with a less number of column : 
```
35.9257,69.6817,3,iron,145376,5.67662,wood,2167.77,13.9209,plastic,76.7917,0.110895,
91.247,63.3338,3,iron,165538,6.22904,plastic,210.265,0.26907,concrete,1531.4,18.6448,
```

no error happens

**Screenshots**
![2022-01-20-142959_1920x1080_scrot](https://user-images.githubusercontent.com/49539269/150349395-17fc6f38-f5b5-4f60-9667-1e31f17b12d3.png)

**Desktop (please complete the following information):**
 - OS: archlinux 
 - PC Model: dell insperion 2022
 - GAMA version: 1.8.1
 - Java version: 1.8

**Additional context**
This error seems to appear only when the csv file as too many columns, or something like that.

**Comment by hqnghi88** [comment] 2022-01-21 01:26
Hi,
It is not an issue. As usual, any csv editor will save the blank column with a separator. You can easily try with excel or gsheet.
So your problem come from that missing of separators: adding 3 more colones will remove the error.
35.9257,69.6817,4,iron,145376,5.67662,wood,2167.77,13.9209,plastic,76.7917,0.110895,concrete,2275.46,47.3281,
91.247,63.3338,3,iron,165538,6.22904,plastic,210.265,0.26907,concrete,1531.4,18.6448,,,,

or you can try with a simple case:
This will give you index out of bound
1,2,3,
4,

and this is normal: 
1,2,3
4,,,

**Comment by Aya-Badawy89** [comment] 2022-01-21 14:45
I had a similar issue and I found that when I add a separator, and the word contents when calling the file, the issue is resolved.
Here is the example from my model:
I add the separator and true after the path of the file , it works. Then, I assign the file to a matrix (file name.contents). This way it works. You can try it out and hopefully it works with you. 
```
file outcome_file <- csv_file("../includes/outcomes.csv", ",", true);
matrix outcomes <- matrix(outcome_file.contents);
```

**Comment by AlexisDrogoul** [comment] 2022-01-25 04:32
@Aya-Badawy89  the "index out of bounds" is emitted because the rows have different lengths. Your code works in this particular configuration, not before of `contents` but because you tell GAMA that the file has a header (last parameter `true`), so the number of columns of the first line is not taken into account. 

I will see if we can somehow make this a bit more robust.

**Comment by AlexisDrogoul** [comment] 2022-01-25 04:49
It is actually a bug and thank you @corentinjuvigny for having uncovered it. If I take a simple example like 

```
1,2,3
4
```

and look at the metadata displayed in the workspace, the dimension of the CSV file is reported to be `1 x 2`, i.e. 1 column and 2 rows. Which is obviously wrong, right ? 

If now I invert the two lines to obtain

```
4
1,2,3
```

The dimension reported is `3 x 2` (i.e. 3 columns and 2 rows), which is correct. 

The problem comes from the fact that the meta information does not "use" the first line to compute the columns number. I can't see why it wouldn't, so my guess is that it is a bug. I will propose a fix soon.

**Comment by Aya-Badawy89** [comment] 2022-01-29 20:17
I noticed something strange that I cannot explain:

1. Can you please try the code below. 
2. Run 4 experiments, the first one make the parameter (first) true and the other three make the parameter false
3. An error will appear in the matrix in the fourth experiment saying it is out of bounds! Why is that?

```
model testmatrix

global {
	matrix results;
	bool first <- true;
	string name <- 'hello';
	int num <- 2;
	reflex when: time=1 {
		if (first = true) {
			save [name, num] to:
			"../includes/test.csv" type:"csv" header:true rewrite: true;
		}
		else {
			name <- 'hello2';
			num <- 4;
			save [name, num] to:
			"../includes/test.csv" type:"csv" header:true rewrite: false;
		}
		file outcome_file <- csv_file("../includes/test.csv", ",",true);
		results <- (outcome_file.contents);
		write results;
	}
	
}
experiment exp type: gui {
	parameter first var:first;
}
```
N.B. This was not happening yesterday.

**Comment by Aya-Badawy89** [comment] 2022-01-29 20:55
Oh. it works now. In the above example, it was just that I had to declare the results matrix this way
matrix results <- [ ];
NOT 
matrix results;
But, I don't why it only appears after adding the 4th row. Do matrices have default lengths?

**Comment by AlexisDrogoul** [comment] 2022-02-05 04:35
The specific problem addressed by this report has been solved as far as I can tell. Closing this issue now. 
@Aya-Badawy89 please open a separate issue for your problem.

**Closed by AlexisDrogoul** 2022-02-05 04:35 UTC
Labels: 😱 Bug, About Data, Priority High, 👍 Fix to be tested
