### ISSUE TITLE
Gama legacy headless raises an NPE on 1.9.3 docker

### ISSUE THREAD

**Issue by romainreuillon** [gama-platform/gama#352] opened 2024-10-09 11:10 UTC
OpenMOLE is based on using the docker container of GAMA and gama-headless.sh. When running with GAMA docker up to 1.9.2 the predator prey models runs perfectly. However when running this model with the 1.9.3 docker it raises an NPE:

java.lang.NullPointerException: Cannot invoke "msi.gaml.expressions.IExpression.value(msi.gama.runtime.IScope)" because the return value of "msi.gama.kernel.experiment.IExperimentPlan.getStopCondition()" is null

Note that this error arrise only using the docker container as using the gama headless directly works ok.

To reproduce it you can extract the archive linked to the issue. It contains:
 - the predator prey gaml file
 - an xml describing the experiment

Go in the extracted directory and run:
```docker run -it -v $PWD:/xp  gamaplatform/gama:1.9.3 /xp/exp.xml /tmp/out```

It should produce the following error:
```
******************************************************************
* GAMA version 1.9.3                                             *
* http://gama-platform.org                                       *
* (c) 2007-2023 UMI 209 UMMISCO IRD/SU & Partners                *
******************************************************************
> FLAG  : enable_debug                                  set to________ true
> FLAG  : enable_logging                                set to________ true
> FLAG  : use_global_preference_store                   set to________ true
> GAMA  : version 1.9.3                                 loading on____ linux 6.8.0-45-generic, x86_64, JDK 17-ea
> JAI   : ImageIO extensions                            loaded for____ BTF|TF8|TIF|TIFF|arx|asc|bmp|btf|gif|jp2|jpeg|jpg|pbm|pgm|png|ppm|tf8|tif|tiff|wbmp
Oct 09, 2024 11:06:06 AM java.util.prefs.FileSystemPreferences$1 run
INFO: Created user preferences directory.
> GAMA  : Plugin msi.gama.core                          loaded in_____ 569ms
> GAMA  : Plugin irit.gaml.extensions.database          loaded in_____ 10ms
> GAMA  : Plugin miat.gaml.extensions.pedestrian        loaded in_____ 8ms
> GAMA  : Plugin msi.gama.headless                      loaded in_____ 1ms
> GAML  : Initializing parser                           done in_______ 93ms
> GAMA  : Plugin msi.gama.lang.gaml                     loaded in_____ 97ms
> GAMA  : Plugin msi.gaml.architecture.simplebdi        loaded in_____ 32ms
> GAMA  : Plugin msi.gaml.extensions.fipa               loaded in_____ 5ms
> GAMA  : Plugin simtools.gaml.extensions.physics       loaded in_____ 6ms
> GAMA  : Plugin simtools.gaml.extensions.traffic       loaded in_____ 16ms
> GAMA  : Plugin ummisco.gama.network                   loaded in_____ 2ms
> GAMA  : Plugin ummisco.gama.serialize                 loaded in_____ 3ms
> GAMA  : Snapshot services                             inactive______ (headless mode)
> GAMA  : Plugin ummisco.gaml.extensions.image          loaded in_____ 11ms
> GAMA  : Plugin ummisco.gaml.extensions.maths          loaded in_____ 42ms
> GAMA  : Plugin ummisco.gaml.extensions.stats          loaded in_____ 17ms
> GAMA  : Loading extensions to 'create'                done in_______ 3ms
> GAMA  : Loading extensions to 'save'                  done in_______ 58ms
> GAMA  : Loading extensions to 'draw'                  done in_______ 1ms
> GAMA  : Loading extensions to 'event'                 done in_______ 0ms
> GAMA  : Gathering built-in models                     done in_______ 1ms
> GAMA  : Loading constants                             done in_______ 69ms
> GAML  : Plugins with language additions               loaded in_____ 1769ms
GAMA configuring and loading...
> GAML  : Artifacts                                     built in______ 23ms
java.lang.NullPointerException: Cannot invoke "msi.gaml.expressions.IExpression.value(msi.gama.runtime.IScope)" because the return value of "msi.gama.kernel.experiment.IExperimentPlan.getStopCondition()" is null
```

**Comment by romainreuillon** [comment] 2024-10-09 11:14
[gama-bug.tar.gz](https://github.com/user-attachments/files/17307029/gama-bug.tar.gz)

**Comment by lesquoyb** [comment] 2024-10-14 03:06
Hello, I think this issue has been solved already, could you try in your environment with the alpha version (gamaplatform/gama:alpha) ?

**Comment by romainreuillon** [comment] 2024-10-14 14:08
Thank you for the quick answer.

I tried it with the same model it gave me a compilation error:
```
[reuillon:~/Documents/Tmp/gama-bug] 1 $ docker run -it -v $PWD:/xp  gamaplatform/gama:alpha /xp/exp.xml /tmp/out
Unable to find image 'gamaplatform/gama:alpha' locally
alpha: Pulling from gamaplatform/gama
c6a83fedfae6: Pull complete 
479e64820c60: Pull complete 
cf4e44e3ea2c: Pull complete 
238c673ab2bb: Pull complete 
eca2c62bac89: Pull complete 
dc62d18bfdf2: Pull complete 
a218874c45c9: Pull complete 
4f4fb700ef54: Pull complete 
Digest: sha256:f381dcea8d1f7dac3bb18752a5ce263c32a0e90474dc14b8799d73a320d5f67c
Status: Downloaded newer image for gamaplatform/gama:alpha
******************************************************************
* GAMA version 2024.8.0-SNAPSHOT                                         *
* http://gama-platform.org                                       *
* (c) 2007-2024 UMI 209 UMMISCO IRD/SU & Partners                *
******************************************************************
> FLAG  : enable_debug                                  set to________ true
> FLAG  : enable_logging                                set to________ true
> FLAG  : use_global_preference_store                   set to________ true
> JAI   : ImageIO extensions                            loaded for____ BTF|TF8|TIF|TIFF|arx|asc|bmp|btf|gif|jp2|jpeg|jpg|pbm|pgm|png|ppm|tf8|tif|tiff|wbmp
> GAMA  : version 2024.8.0-SNAPSHOT                     loading on____ Linux 6.8.0-45-generic, processor amd64, JDK OpenJDK 64-Bit Server VM Eclipse Adoptium version 21.0.4+7-LTS
Oct 14, 2024 1:56:12 PM java.util.prefs.FileSystemPreferences$1 run
INFO: Created user preferences directory.
> GAMA  : Plugin gama.core                              loaded in_____ 334ms
> GAMA  : Plugin gama.extension.bdi                     loaded in_____ 27ms
> GAMA  : Plugin gama.extension.database                loaded in_____ 9ms
> GAMA  : Plugin gama.extension.fipa                    loaded in_____ 5ms
> GAMA  : Snapshot services                             inactive______ (headless mode)
> GAMA  : Plugin gama.extension.image                   loaded in_____ 18ms
> GAMA  : Plugin gama.extension.maths                   loaded in_____ 38ms
> GAMA  : Plugin gama.extension.network                 loaded in_____ 2ms
> GAMA  : Plugin gama.extension.pedestrian              loaded in_____ 8ms
> GAMA  : Plugin gama.extension.physics                 loaded in_____ 6ms
> GAMA  : Plugin gama.extension.serialize               loaded in_____ 3ms
> GAMA  : Plugin gama.extension.stats                   loaded in_____ 23ms
> GAMA  : Plugin gama.extension.traffic                 loaded in_____ 13ms
> GAMA  : Plugin gama.headless                          loaded in_____ 1ms
> GAML  : Initializing parser                           done in_______ 92ms
> GAMA  : Plugin gaml.compiler                          loaded in_____ 94ms
> GAMA  : Loading extensions to 'create'                done in_______ 1ms
> GAMA  : Loading extensions to 'save'                  done in_______ 39ms
> GAMA  : Loading extensions to 'draw'                  done in_______ 1ms
> GAMA  : Loading extensions to 'event'                 done in_______ 1ms
> GAMA  : Gathering built-in models                     done in_______ 1ms
> GAMA  : Loading constants                             done in_______ 65ms
> GAML  : Plugins with language additions               loaded in_____ 726ms
GAMA configuring and loading...
> GAML  : Artifacts                                     built in______ 23ms
gama.gaml.compilation.GamaCompilationFailedException: The model couldn't be compiled because of compilation errors
```

Then I tried to generate an xml input for this example taken from github (https://github.com/gama-platform/gama/blob/2024-06/gama.library/models/Tutorials/Predator%20Prey/models/Model%2012.gaml), and I get another NPE:
```
[reuillon:~/Documents/Tmp/gama-bug] $ docker run -it -v $PWD:/xp  gamaplatform/gama:alpha -xml prey_predator /xp/pp12.gaml /xp/pp12.xml 
******************************************************************
* GAMA version 2024.8.0-SNAPSHOT                                         *
* http://gama-platform.org                                       *
* (c) 2007-2024 UMI 209 UMMISCO IRD/SU & Partners                *
******************************************************************
> FLAG  : enable_debug                                  set to________ true
> FLAG  : enable_logging                                set to________ true
> FLAG  : use_global_preference_store                   set to________ true
> JAI   : ImageIO extensions                            loaded for____ BTF|TF8|TIF|TIFF|arx|asc|bmp|btf|gif|jp2|jpeg|jpg|pbm|pgm|png|ppm|tf8|tif|tiff|wbmp
> GAMA  : version 2024.8.0-SNAPSHOT                     loading on____ Linux 6.8.0-45-generic, processor amd64, JDK OpenJDK 64-Bit Server VM Eclipse Adoptium version 21.0.4+7-LTS
Oct 14, 2024 2:06:44 PM java.util.prefs.FileSystemPreferences$1 run
INFO: Created user preferences directory.
> GAMA  : Plugin gama.core                              loaded in_____ 361ms
> GAMA  : Plugin gama.extension.bdi                     loaded in_____ 43ms
> GAMA  : Plugin gama.extension.database                loaded in_____ 9ms
> GAMA  : Plugin gama.extension.fipa                    loaded in_____ 5ms
> GAMA  : Snapshot services                             inactive______ (headless mode)
> GAMA  : Plugin gama.extension.image                   loaded in_____ 12ms
> GAMA  : Plugin gama.extension.maths                   loaded in_____ 36ms
> GAMA  : Plugin gama.extension.network                 loaded in_____ 2ms
> GAMA  : Plugin gama.extension.pedestrian              loaded in_____ 8ms
> GAMA  : Plugin gama.extension.physics                 loaded in_____ 5ms
> GAMA  : Plugin gama.extension.serialize               loaded in_____ 4ms
> GAMA  : Plugin gama.extension.stats                   loaded in_____ 11ms
> GAMA  : Plugin gama.extension.traffic                 loaded in_____ 13ms
> GAMA  : Plugin gama.headless                          loaded in_____ 1ms
> GAML  : Initializing parser                           done in_______ 95ms
> GAMA  : Plugin gaml.compiler                          loaded in_____ 97ms
> GAMA  : Loading extensions to 'create'                done in_______ 2ms
> GAMA  : Loading extensions to 'save'                  done in_______ 46ms
> GAMA  : Loading extensions to 'draw'                  done in_______ 2ms
> GAMA  : Loading extensions to 'event'                 done in_______ 0ms
> GAMA  : Gathering built-in models                     done in_______ 2ms
> GAMA  : Loading constants                             done in_______ 65ms
> GAML  : Plugins with language additions               loaded in_____ 761ms
GAMA configuring and loading...
> GAML  : Artifacts                                     built in______ 25ms
/xp/pp12.gaml model is being compiled...
Parameter file saved at: /xp/pp12.xml
[reuillon:~/Documents/Tmp/gama-bug] $ docker run -it -v $PWD:/xp  gamaplatform/gama:alpha /xp/pp12.xml /tmp/out
******************************************************************
* GAMA version 2024.8.0-SNAPSHOT                                         *
* http://gama-platform.org                                       *
* (c) 2007-2024 UMI 209 UMMISCO IRD/SU & Partners                *
******************************************************************
> FLAG  : enable_debug                                  set to________ true
> FLAG  : enable_logging                                set to________ true
> FLAG  : use_global_preference_store                   set to________ true
> JAI   : ImageIO extensions                            loaded for____ BTF|TF8|TIF|TIFF|arx|asc|bmp|btf|gif|jp2|jpeg|jpg|pbm|pgm|png|ppm|tf8|tif|tiff|wbmp
> GAMA  : version 2024.8.0-SNAPSHOT                     loading on____ Linux 6.8.0-45-generic, processor amd64, JDK OpenJDK 64-Bit Server VM Eclipse Adoptium version 21.0.4+7-LTS
Oct 14, 2024 2:07:15 PM java.util.prefs.FileSystemPreferences$1 run
INFO: Created user preferences directory.
> GAMA  : Plugin gama.core                              loaded in_____ 363ms
> GAMA  : Plugin gama.extension.bdi                     loaded in_____ 28ms
> GAMA  : Plugin gama.extension.database                loaded in_____ 8ms
> GAMA  : Plugin gama.extension.fipa                    loaded in_____ 5ms
> GAMA  : Snapshot services                             inactive______ (headless mode)
> GAMA  : Plugin gama.extension.image                   loaded in_____ 11ms
> GAMA  : Plugin gama.extension.maths                   loaded in_____ 51ms
> GAMA  : Plugin gama.extension.network                 loaded in_____ 2ms
> GAMA  : Plugin gama.extension.pedestrian              loaded in_____ 8ms
> GAMA  : Plugin gama.extension.physics                 loaded in_____ 6ms
> GAMA  : Plugin gama.extension.serialize               loaded in_____ 3ms
> GAMA  : Plugin gama.extension.stats                   loaded in_____ 13ms
> GAMA  : Plugin gama.extension.traffic                 loaded in_____ 14ms
> GAMA  : Plugin gama.headless                          loaded in_____ 2ms
> GAML  : Initializing parser                           done in_______ 93ms
> GAMA  : Plugin gaml.compiler                          loaded in_____ 95ms
> GAMA  : Loading extensions to 'create'                done in_______ 2ms
> GAMA  : Loading extensions to 'save'                  done in_______ 44ms
> GAMA  : Loading extensions to 'draw'                  done in_______ 2ms
> GAMA  : Loading extensions to 'event'                 done in_______ 0ms
> GAMA  : Gathering built-in models                     done in_______ 1ms
> GAMA  : Loading constants                             done in_______ 71ms
> GAML  : Plugins with language additions               loaded in_____ 766ms
GAMA configuring and loading...
> GAML  : Artifacts                                     built in______ 22ms
java.lang.NullPointerException: Cannot invoke "gama.headless.common.DataType.name()" because the return value of "gama.headless.job.ListenedVariable.getDataType()" is null
```

Any idea of what is going on?

**Comment by lesquoyb** [comment] 2024-10-15 04:02
for the compilation error it probably is the declaration of a parameter with the `parameter` facet, it won't be supported anymore in the next release and has been removed from the alpha. The supported way to do it is to declare parameters in the experiments.
If you cannot find where the compilation error is, the easiest way would be to open the file in the gama editor to get the complete compilation error message.

For the second point, I tried to reproduce but on my computer with the git version it works normally, I will check with the docker version later.

**Comment by lesquoyb** [comment] 2024-10-24 04:20
Ok so I tried in docker and have the same error message. For now I have no clue what could be the difference between the docker environment and the git version. @RoiArthurB any idea ?

**Comment by lesquoyb** [comment] 2024-10-24 04:35
Turns out it is linked to the output and more particularly the displays. If I comment out the displays from the xml everything works fine

**Comment by lesquoyb** [comment] 2024-10-24 05:07
More updates:
 - I found the issue and it is not related to docker at all, no need to investigate this @RoiArthurB my local setup was just weird and I can now reproduce with git version
 - The problem itself was just that there was no handling of how to log displays properly
 - I fixed it locally, but now I'm wondering when this was introduced and why, once I'm sure it was just something like forgetting this case while rewriting the headless I will commit to the repo.
 - The fact that there was no stack trace at all linked to the NPE is a bit weird, I will also have a look at that

**Comment by lesquoyb** [comment] 2024-11-11 10:43
It should be fixed in the current alpha, could you test it ?
By the way, if you have a use of legacy headless where you don't need to modify the generated xml apart from the number of steps you could try to run the simulation directly in one step with the `-gaml` option as described [here](https://gama-platform.org/wiki/next/HeadlessLegacy#easy-mode)

**Comment by romainreuillon** [comment] 2024-11-12 15:58
Nice ! Thanks

Would it be possible to push the latest alpha version to the docker hub? So I can test it in OpenMOLE.

Actually in OpenMOLE the XML is modified to set the input parameters and output values are parsed at the end of the simulation. From what I read the gaml version is not yet ready for that. I am mistaken?

**Comment by lesquoyb** [comment] 2024-11-12 16:05
Oops, I thought the docker image was automatically updated with each new build, maybe it's only with the stable release, so that's a new issue.
In the meantime, @RoiArthurB could you manually do it?

**Comment by romainreuillon** [comment] 2024-11-18 15:25
Dear @lesquoyb @RoiArthurB, 

we are preparing the exmodelo school and we will demonstrate how to run GAMA models in OpenMOLE.

Would it be possible to publish a docker manually to test patch ?

Best
Romain

**Comment by RoiArthurB** [comment] 2024-11-19 02:59
@lesquoyb @romainreuillon Building here : https://github.com/gama-platform/gama.docker/actions/runs/11905365919

**Comment by romainreuillon** [comment] 2024-11-20 21:25
Thx !

**Comment by lesquoyb** [comment] 2024-11-25 21:06
I guess it's all working now? I'm closing the issue, if it's not the case feel free to reopen

**Closed by lesquoyb** 2024-11-25 21:06 UTC
Labels: About Headless

**Comment by romainreuillon** [comment] 2024-11-25 21:43
Yes it actually works. Thank you for the fix :rocket:

**Comment by ElCep** [comment] 2025-03-25 07:16
Is it fixed ?  Same problematic as @romainreuillon 
I tried to run our model from normal gama (1.9.3) and it works... it also works in headless...

Romain  told me to test in a docker since that's what's used in OpenMole, and that's the drama! Here's what he told me 

`docker pull gamaplatform/gama:1.9.3`

But it fails with the same bug !

here's what I have inside the docker

```
./gama-headless.sh /work/models/Sim_Ref_bidouille .
Sim_Ref_bidouille.gaml  Sim_Ref_bidouille.xml   Sim_Ref_bidouille1.xml Sim_Ref_bidouille3.xml
bash-5.1# ./gama-headless.sh /work/models/Sim_Ref_bidouille1.xml .
******************************************************************
* GAMA version 1.9.3                                             *
* http://gama-platform.org/                                       *
* (c) 2007-2023 UMI 209 UMMISCO IRD/SU & Partners                *
******************************************************************
> FLAG  : enable_debug                                  set to________ true
> FLAG  : enable_logging                                set to________ true
> FLAG  : use_global_preference_store                   set to________ true
> GAMA  : version 1.9.3                                 loading on____ linux 6.13.6-100.fc40.x86_64, x86_64, JDK 17-ea
> JAI   : ImageIO extensions                            loaded for____ BTF|TF8|TIF|TIFF|arx|asc|bmp|btf|gif|jp2|jpeg|jpg|pbm|pgm|png|ppm|tf8|tif|tiff|wbmp
> GAMA  : Plugin msi.gama.core                          loaded in_____ 736ms
> GAMA  : Plugin irit.gaml.extensions.database          loaded in_____ 12ms
> GAMA  : Plugin miat.gaml.extensions.pedestrian        loaded in_____ 15ms
> GAMA  : Plugin msi.gama.headless                      loaded in_____ 2ms
> GAML  : Initializing parser                           done in_______ 129ms
> GAMA  : Plugin msi.gama.lang.gaml                     loaded in_____ 133ms
> GAMA  : Plugin msi.gaml.architecture.simplebdi        loaded in_____ 49ms
> GAMA  : Plugin msi.gaml.extensions.fipa               loaded in_____ 9ms
> GAMA  : Plugin simtools.gaml.extensions.physics       loaded in_____ 9ms
> GAMA  : Plugin simtools.gaml.extensions.traffic       loaded in_____ 27ms
> GAMA  : Plugin ummisco.gama.network                   loaded in_____ 4ms
> GAMA  : Plugin ummisco.gama.serialize                 loaded in_____ 7ms
> GAMA  : Snapshot services                             inactive______ (headless mode)
> GAMA  : Plugin ummisco.gaml.extensions.image          loaded in_____ 22ms
> GAMA  : Plugin ummisco.gaml.extensions.maths          loaded in_____ 64ms
> GAMA  : Plugin ummisco.gaml.extensions.stats          loaded in_____ 20ms
> GAMA  : Loading extensions to 'create'                done in_______ 4ms
> GAMA  : Loading extensions to 'save'                  done in_______ 80ms
> GAMA  : Loading extensions to 'draw'                  done in_______ 2ms
> GAMA  : Loading extensions to 'event'                 done in_______ 1ms
> GAMA  : Gathering built-in models                     done in_______ 2ms
> GAMA  : Loading constants                             done in_______ 81ms
> GAML  : Plugins with language additions               loaded in_____ 1970ms
GAMA configuring and loading...
> GAML  : Artifacts                                     built in______ 42ms
java.lang.NullPointerException: Cannot invoke "msi.gaml.expressions.IExpression.value(msi.gama.runtime.IScope)" because the return value of "msi.gama.kernel.experiment.IExperimentPlan.getStopCondition()" is null
```

maybe the ussue isn't closed after all 😸

**Comment by RoiArthurB** [comment] 2025-03-25 08:35
@ElCep without having your files, it's hard to truly tell what are the problems, but here's what I can say from your logs: 
- On your first message, as identified by Baptiste previously, do you have any displays in your running experiment? This seems to be an issue within this tagged container for some reason...
- On your second message (where you're not trying to run experiments in XML, nor having an NPE, so it would be a different issue), your model doesn't compile, probably due to the evolution of the GAMA language between 1.9.3 and the latest alpha. One quick way to validate this theory is to try to open your project in the alpha release of GAMA and see if it works in GUI :) 

Also, as a tip, you're not forced to log inside the docker container, by default it will execute the gama-headless command, so you can just run this command : `docker run -v /path/to/your/model:/work gamaplatform/gama:1.9.3 /work/models/Sim_Ref_bidouille/Sim_Ref_bidouille.xml /work/models/Sim_Ref_bidouille/` (ref: https://github.com/gama-platform/gama.docker?tab=readme-ov-file#example )

**Comment by ElCep** [comment] 2025-03-25 09:32
Our model works in the headless version of Gama 1.9.3, but not in the docker version, which is strange! 

In alpha version 2025.03.0 there's actually a bug in the model at parameter facet level, but if I ask @alassaneBah to look at this problem, he'll crucify me. 

They take the following form: 
```
float campaignProbability1 parameter: "campaign probability" category:"Fishing Unit (Cat.I)" init:0.1;
int campaignDuration1 parameter: "campaign duration" category:"Fishing Unit (Cat.I)" init:3;
float campaignProbability2 parameter: "campaign probability" category:"Fishing Unit (Cat.II)" init:0.1;
int campaignDuration2 parameter: "campaign duration" category:"Fishing Unit (Cat.II)" init:6;
float campaignProbability3 parameter: "campaign probability" category:"Fishing Unit (Cat.III)" init:0.1;
int campaignDuration3 parameter: "campaign duration" category:"Fishing Unit (Cat.III)" init:9;
```
Can you give me some advice on how to declare them in the experiment, so that I can get by?

**Comment by lesquoyb** [comment] 2025-03-25 09:41
The syntax simply changed and declaring a parameter outside of an experiment is just not allowed anymore for all versions after 1.9.3.
Nothing changed regarding the way to declare them in experiment though, it will look something like this:
```
parameter "campaign probability" var:campaignProbability1 <- 0.01 category:"Fishing Unit (Cat.I)" ;
```

**Comment by ElCep** [comment] 2025-03-25 11:19
Thanks @lesquoyb! I've made the adjustments and it's running in the gama:alpha GUI. So back to the dockers. I have to use XML to inject parameters from OpenMole (cc. @romainreuillon ). 

But `./gama-headless.sh -xml Lolli_Sim_Ref /work/models/Sim_Ref_bidouille.gaml /work/models/Sim_Ref_bidouille.xml` returns an empty XML 

```
c97193e2d679:/opt/gama-platform/headless# ./gama-headless.sh -xml Lolli_Sim_Ref /work/models/Sim_Ref_bidouille.gaml /work/models/Sim_Ref_bidouille.xml
******************************************************************
* GAMA version 2024.11.0-SNAPSHOT                                         *
* http://gama-platform.org                                       *
* (c) 2007-2024 UMI 209 UMMISCO IRD/SU & Partners                *
******************************************************************
> FLAG  : enable_debug                                  set to________ true
> FLAG  : enable_logging                                set to________ true
> FLAG  : use_global_preference_store                   set to________ true
> JAI   : ImageIO extensions                            loaded for____ BTF|TF8|TIF|TIFF|arx|asc|bmp|btf|gif|jp2|jpeg|jpg|pbm|pgm|png|ppm|tf8|tif|tiff|wbmp
> GAMA  : version 2024.11.0-SNAPSHOT                    loading on____ Linux 6.13.6-100.fc40.x86_64, processor amd64, JDK OpenJDK 64-Bit Server VM Eclipse Adoptium version 21.0.6+7-LTS
> GAMA  : Plugin gama.core                              loaded in_____ 504ms
> GAMA  : Plugin gama.extension.bdi                     loaded in_____ 55ms
> GAMA  : Plugin gama.extension.database                loaded in_____ 13ms
> GAMA  : Plugin gama.extension.fipa                    loaded in_____ 7ms
> GAMA  : Snapshot services                             inactive______ (headless mode)
> GAMA  : Plugin gama.extension.image                   loaded in_____ 24ms
> GAMA  : Plugin gama.extension.maths                   loaded in_____ 68ms
> GAMA  : Plugin gama.extension.network                 loaded in_____ 6ms
> GAMA  : Plugin gama.extension.pedestrian              loaded in_____ 20ms
> GAMA  : Plugin gama.extension.physics                 loaded in_____ 14ms
> GAMA  : Plugin gama.extension.serialize               loaded in_____ 7ms
> GAMA  : Plugin gama.extension.stats                   loaded in_____ 29ms
> GAMA  : Plugin gama.extension.traffic                 loaded in_____ 33ms
> GAMA  : Plugin gama.headless                          loaded in_____ 2ms
> GAML  : Initializing parser                           done in_______ 162ms
> GAMA  : Plugin gaml.compiler                          loaded in_____ 177ms
> GAMA  : Loading extensions to 'create'                done in_______ 4ms
> GAMA  : Loading extensions to 'save'                  done in_______ 70ms
> GAMA  : Loading extensions to 'draw'                  done in_______ 2ms
> GAMA  : Loading extensions to 'event'                 done in_______ 1ms
> GAMA  : Gathering built-in models                     done in_______ 2ms
> GAMA  : Loading constants                             done in_______ 105ms
> GAML  : Plugins with language additions               loaded in_____ 1202ms
GAMA configuring and loading...
> GAML  : Artifacts                                     built in______ 38ms
/work/models/Sim_Ref_bidouille.gaml model is being compiled...

=== ERROR ===
	GAMA is about to generate an empty XML file.
	If you want to run a Batch experiment, please check the "-batch" flag.
Error in you command, here's the log :
cat: .workspace2/.metadata/.log: No such file or directory
c97193e2d679:/opt/gama-platform/headless# ls .workspace2/.metadata/

```

My experiment look like : 

```
experiment Lolli_Sim_Ref  type: batch until: step < 50{
	category "Init Biomass of Target species and Fishing Units" expanded: false color: #lightgreen; 
	....
	parameter "campaign duration cat3" var:campaignDuration3 <- 9 category:"Fishing Unit (Cat.III)" ;
    
}
```
Before it was `type:gui` so I changed it to `type: batch` on a hunch from @RoiArthurB

**Comment by RoiArthurB** [comment] 2025-03-26 02:58
@ElCep If you're using the `Legacy Headless mode` (https://gama-platform.org/wiki/next/HeadlessLegacy), you have to generate XML (in which you can set precise parameter values, etc). This operate over some `type: gui` experiments (for some legacy reason). As far as I know, it's the only mode supported by OpenMole.

Since 1.9.3, you also can run `type: batch` experiment directly in headless (https://gama-platform.org/wiki/next/HeadlessBatch), in this case you don't have (and can't) generate XML file for it since all the exploration plan would be already described in gaml (which is the only goal of the XML file from the legacy system).

**Comment by RoiArthurB** [comment] 2025-04-01 04:21
Hi, the issue you're having on the logs are from OpenMole and I can't help at all about this...

I would guess the problem comes from the generated XML is expecting `STRING` variables, but as the values are `INTEGER` it doesn't fill anything. 

In any case, can you please open a new issue about this problem as it's not related to the NPE error anymore :)
