### ISSUE TITLE
Windows scaling ratio causes bad #user_location values (Java2D displays)

### ISSUE THREAD

**Issue by lesquoyb** [gama-platform/gama#3308] opened 2022-03-01 04:07 UTC
**Describe the bug**
While playing with the `Mas KMeans Interactive` model in the Library models I found out that changing the Windows Scaling ratio to something else than 100% changes the value of the #user_location variable, applying the ratio to it. Which could break some models based on interaction with the user as the location of everything on screen keeps its location unchanged.

**To Reproduce**
1. Go to the windows settings and change the scaling ratio to something other than 100%
![image](https://user-images.githubusercontent.com/6374469/156102949-59c8612b-c947-433c-8fe1-b9df035c20ac.png)
2. Run an experiment using #user_location
3. the value of #user_location should be wrong

Here is a small model to track the bug :
```

model UserLocation

global {
	init {
		create cursor number:1;
	}	
}

species cursor {
	
	aspect default{
		draw circle(2) at:#user_location color:#green;
	}
}



experiment UserLocation type: gui {

	output {
		display main {
			species cursor;
		}
	}
}

```

The green circle is supposed to be located at the user's cursor location, but with a scaling ratio different than 100% you can clearly see that it has an offset.

**Expected behavior**
The value of #user_location should not change with the scaling ratio.

**Desktop (please complete the following information):**
 - OS: Windows 
 - GAMA version: 1.8.2

**Additional context**
The value of #user_location seem to be multiplied by the scaling ratio (for example +25% of the expected value with a scaling of 125%)

**Comment by AlexisDrogoul** [comment] 2022-03-20 07:12
Since the recent commits made for #3239 and #3313, I cant reproduce this problem anymore. Is it still happening on your side ? (remember to test by relaunching the .product, to make sure you catch the latest default options)

**Comment by lesquoyb** [comment] 2022-03-21 03:36
No more problem, the mentioned model from the library and the test model are both working like a charm

**Comment by lesquoyb** [comment] 2022-11-25 04:43
Reopening because it actually is still present for java2D displays. In my case it appears only with values of scaling of 175%, 225%, 250% and 300%

**Comment by AlexisDrogoul** [comment] 2022-12-27 08:16
> Reopening because it actually is still present for java2D displays. In my case it appears only with values of scaling of 175%, 225%, 250% and 300%

@lesquoyb : Does it mean it **does not** appear for 125% or 200% ? This would be surprising, so I prefer to be sure before hacking the mouse listener on Windows !

**Comment by lesquoyb** [comment] 2022-12-27 08:36
Yes, to summarize:
what works:
* 100%
* 125%
* 150%
* 200%
* 300%
what doesn't work:
 * 175%
 * 225%
 * 250%

Strangely enough, for 175% the user_location is less than the actual mouse location when the resolution is 1920x1200, but greater when it's 2K. for zooms greater than 200% user_location has a value greater than what it should be, but I can only test in 2K resolution.
The 300% zoom seems to work now but wasn't when I reopened the issue, I may do further tests later
**Edit**: I updated the resolution, I'm actually not in a standard 16:9 ratio but 16:10, so full HD is 1920x1200 and 2K is 2880x1800.
That unconventional ratio may be a part of the problem

**Comment by AlexisDrogoul** [comment] 2022-12-27 10:19
Well. Would be in that case interesting to list the resolutions that cause a problem (and if they cause a problem also at ratio 16:9). 
I have committed a possible fix for this. Please try it and report any progress (as I am not on Windows and cant test it).

**Comment by lesquoyb** [comment] 2022-12-27 10:21
On my computer the problem looks worse in 175% now, with greater difference between user_location and the mouse position, and the space used by opengl doesn't fill the whole tab.
![image](https://user-images.githubusercontent.com/6374469/209652169-88c8fccc-b2e7-414f-b5e2-5e044b868141.png)

In 150% (my normal scaling) everything still works fine

**Edit**: I tried different ratios and the problem is the same so I think we can leave that out of the equation

**Comment by AlexisDrogoul** [comment] 2022-12-27 11:03
Maybe I reversed the computation ? You can try to alter the filter() function to see if it helps (multiplying instead of dividing).

**Comment by AlexisDrogoul** [comment] 2022-12-29 17:17
> On my computer the problem looks worse in 175% now, with greater difference between user_location and the mouse position, and the space used by opengl doesn't fill the whole tab. 

I havent touched the OpenGL part... Wasn't it only restricted to Java2D displays ?

**Comment by lesquoyb** [comment] 2023-01-02 02:53
> > On my computer the problem looks worse in 175% now, with greater difference between user_location and the mouse position, and the space used by opengl doesn't fill the whole tab.
> 
> I havent touched the OpenGL part... Wasn't it only restricted to Java2D displays ?

My bad, I meant java2D

**Comment by lesquoyb** [comment] 2023-02-06 02:50
It didn't fix the issue

**Comment by lesquoyb** [comment] 2023-02-09 04:08
Update: recent commits actually introduced some regression, it is now not working with any scaling other than 100%

**Comment by AlexisDrogoul** [comment] 2023-02-09 04:23
Beware of using the correct arguments : -Dsun.java2d.uiScale.enabled=false (or remove this, so that Eclipse uses the default) /  -Duse_precise_autoscale=true

Is it the case ?

**Comment by lesquoyb** [comment] 2023-02-09 04:30
I had `-Duse_precise_autoscale=false`, but changing it to true didn't solve the issue

**Comment by lesquoyb** [comment] 2023-02-09 05:15
Deleting the ` -Dsun.java2d.uiScale.enabled=false` actually solved it for all resolutions, the only problem remaining is that those parameters are not packaged with the current gama release (tested with yesterday's one)

**Comment by AlexisDrogoul** [comment] 2023-02-12 14:21
We can now close this issue as the parameters should be correctly packaged.

**Closed by AlexisDrogoul** 2023-02-12 14:21 UTC
Labels: 😱 Bug, OS Windows, About GAML, 📺 Display Java2D
