### ISSUE TITLE
Paste shortcut paste the buffer in the gaml editor, and never in the "Search" field

### ISSUE THREAD

**Issue by mazarsju** [gama-platform/gama#1295] opened 2015-11-09 10:33 UTC
cf title

**Comment by mazarsju** [comment] 2015-11-09 10:38
Other problem with the "Search" field and the next/previous button :
1) write something in the search field (you can do next and previous)
2) click again on the search field (you CAN'T do next and previous anymore...)
1) edit the search field (you can do next and previous again...)

**Comment by AlexisDrogoul** [comment] 2015-12-02 04:55
I will what I can do on this one (pasting and copying are not part of the behavior of the text fields used in this control). The second "bug" is actually a design choice, but I dont really remember why it has been made :)

**Comment by AlexisDrogoul** [comment] 2015-12-13 13:40
OK. It seems to be caused by a long-standing bug in Eclipse (see http://aaron-kelley.net/blog/2012/05/ctrlc-to-copy-does-not-always-work-in-eclipse/). There is currently no way I can fix it automatically, but you can follow the advice of the blog post and it will work: go to Preferences, Advanced…, and unbind CTRL+C / CTRL+V … Strange enough but it works.

**Comment by AlexisDrogoul** [comment] 2015-12-13 17:56
I have found a workaround, in commit e21bb17704e0e5f2471295e8ec86b93e0d001ad3, for unbinding the keys — it might be necessary to create a new workspace, though. I close the issue.

**Comment by AlexisDrogoul** [comment] 2016-01-21 18:02
Reopening it, as I had to rebind the shortcuts to allow them to work in the navigator…

**Closed** 2016-12-06 00:54 UTC
Labels: Affects Usability, Concerns Modeling, OS All, Priority Low, Version Git
