### ISSUE TITLE
Folding issue

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#1892] opened 2016-06-21 20:31 UTC
### Steps to reproduce
1. Open a model, click on the bar to allow folding option

2. Right-click on the line number near the global statement, and choose folding / Collapse All.

### Expected behavior
Tell us what should happen (include all relevant expectations)

### Actual behavior

We cannot expand anymore by clicking on the plus button.
We have to right-click and choose Folding / expand all.

### System and version 
GAMA nightybuilt, MACOSX

**Comment by AlexisDrogoul** [comment] 2016-06-22 01:48
Cannot reproduce it on my locally built version (with the same script). I will test on the downloaded version.

**Comment by AlexisDrogoul** [comment] 2016-06-22 01:57
I downloaded the nightly build and it works fine.

**Comment by AlexisDrogoul** [comment] 2016-08-04 07:47
Closed as linked to #1893

**Closed by AlexisDrogoul** 2016-08-04 07:47 UTC
Labels: * Not reproducible
