### ISSUE TITLE
Windows scaling causes rendering issues

### ISSUE THREAD

**Issue by lesquoyb** [gama-platform/gama#3313] opened 2022-03-01 09:34 UTC
**Describe the bug**
Related to #3308 , using a scaling ratio different from 100% seems to break the rendering of charts

**To Reproduce**
Example model : 

```
experiment testBug {
	
	
	output {		
		display LV  {
			chart 'test' {
				data "testData" value: [1,2,3,4] color: #red;			
			}			
		}						
	}
	
}
```

Run this model with a scaling ratio different from 100% to see the chart rendered incorrectly :

![image](https://user-images.githubusercontent.com/6374469/156140446-84f1b715-cf88-49f0-93d8-f5e2d51ce89c.png)

expected rendering : 
![image](https://user-images.githubusercontent.com/6374469/156142831-efb64158-03ac-455c-9ecc-dd6f47230a01.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - GAMA version: git

**Additional context**
resizing the window or toggling to fullscreen seems to fix the issue, the button "zoom to fit view" doesn't work

**Comment by AlexisDrogoul** [comment] 2022-03-01 14:23
Probably a duplicate of #3239. What happens with several displays, by the way ? Is only the last one exhibiting the problem ?

**Comment by lesquoyb** [comment] 2022-03-02 02:27
I tried this display : 
```
output {	
		
		layout value:#horizontal tabs:true;
			
		display test  {
			chart 'test' {
				data "testData" value: [1,2,3,4] color: #red;			
			}			
		}	
		display test2  {
			chart 'test' {
				data "testData" value: [1,2,3,4] color: #red;			
			}			
		}	
		display test3  {
			chart 'test' {
				data "testData" value: [1,2,3,4] color: #red;			
			}			
		}						
	}
```
And there seem to be no problem surprisingly :
![image](https://user-images.githubusercontent.com/6374469/156282656-8c9f4002-a1e4-4dcc-a71f-71947dcfc1f8.png)

I think it is because the displays seem to be first drawn at a "normal" size, and then resized to fit the tab layout.

**Closed** 2022-03-21 14:32 UTC
Labels: 😱 Bug, About UI, 👍 Fix to be tested
