### ISSUE TITLE
Wrong orientation when drawing a texture

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#2914] opened 2019-12-07 17:50 UTC
**Describe the bug**
I am planning to display image generated by photoshop (in 4K) and also gif however I just notice a strange behavior when trying to simply display an image as background.

The weird thing is that it's doesnt seem to happen in the Built-In Shapes.gaml model and I guess we didn't realize it on model like boids or ants as the texture is symetric in rotation

Try to draw a background with an image (in opengl however I have the feeling that there is also another issue in java2D) using

`````
graphics world{ 
  draw geometry(shape_file_bounds) texture:gamaRaster.path ;
}
``````

or creating a species and drawing it with a texture 

````
species graphicWorld{
	aspect base{
		draw shape texture:gamaRaster.path;
	}
}
````
**To Reproduce**
Run the model 
The image is flip with an angle of 90. 

**Expected behavior**
Displayed as the original one. 
The workaround is to manually rotate the original picture 

**Screenshots**

OpenGl
<img width="1339" alt="Screen Shot 2019-12-07 at 12 42 10" src="https://user-images.githubusercontent.com/3928502/70378581-0139bc00-18f0-11ea-838b-583f21101f80.png">

Java2D

**Desktop (please complete the following information):**
 - OS: Mac OS
 - GAMA version: [git, 1.8, etc.]

**Additional context**

**Comment by AlexisDrogoul** [comment] 2019-12-10 15:04
Here, you are not simply displaying an image, you are using it as a texture within a shape. It is perfectly possible that textures are rotated by default, and it is normal that they do not work in Java2D. Actually, I don't really understand why you use the `texture:` facet. Wouldn't drawing the image be easier (e.g. `draw gamaRaster; `) ?

**Comment by benoitgaudou** [comment] 2020-02-19 06:07
Hi Arnaud,

With the GAMA release 1.8, I tried to use the GAMA image in texture for the aspect of an agent, in background of a display and in graphics. I was not able to reproduce any rotation error...
(note that in Java2D the textures do not appear, so I used only openGL).

Can we close this issue ?

Benoit

```
global {
	image_file Gama0_image_file <- image_file("../images/Gama.jpg");
	
	init {
		create t {
			shape <- square(50);
		}
	}
}

species t {
	aspect base{
		draw shape texture:Gama0_image_file border: #black ;
	}
}

experiment NewModel type: gui {

	output {
		
		display o type: opengl {
			graphics world{ 
			  draw geometry(world.shape) texture:Gama0_image_file ;
			  draw world.shape border: #black empty:true;
			}
		}	
		
		display d type: opengl {
			image Gama0_image_file;
			species t aspect: base;
		}
	}
}
```

<img width="952" alt="Screenshot 2020-02-19 at 14 07 28" src="https://user-images.githubusercontent.com/1555274/74806543-310a3480-5321-11ea-8463-b78084d401f1.png">

**Comment by hqnghi88** [comment] 2020-02-20 13:07
I tested and it works for git version. I remember that i had this issue last year but it seems ok now.

**Comment by AlexisDrogoul** [comment] 2020-02-21 00:15
OK, so let's close this for now. Reopen if you can reproduce it (and carefully note the context in that case).

**Closed by AlexisDrogoul** 2020-02-21 00:15 UTC
Labels: Version 1.8.0, ❌ * Not reproducible, 🖥 Display OpenGL, 😱 > Bug
