### ISSUE TITLE
Screenshot frame half square

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#1889] opened 2016-06-20 15:39 UTC
I just notice that when using the screenshot feature the rendered screenshot is not 100% ok

I mean (at least in my version (maybe it come from swt/eclipse config) I have a half square as a frame
![screen shot 2016-06-20 at 11 37 30](https://cloud.githubusercontent.com/assets/3928502/16200445/601751ba-36db-11e6-92e2-9616f77909ae.png)

Maybe there is a way to configure it (something related to fullscreen maybe) ?

**Comment by AlexisDrogoul** [comment] 2016-06-20 17:55
Hmm. Can't reproduce it on my configuration. Is the "quick snapshot" preference set to true or false (in the "Performances" tab) ?

**Comment by agrignard** [comment] 2016-06-20 19:59
right.

With the default value there is this problem if I turn it that's ok

**Comment by AlexisDrogoul** [comment] 2016-06-21 09:49
Sorry -- I didn't catch it. Do you have this error when it is set to TRUE or to FALSE ?

**Comment by agrignard** [comment] 2016-06-21 13:21
With the *default* value of the preferences Enable fast snapshots of
displays to *false* I have the problem.

**Comment by AlexisDrogoul** [comment] 2016-08-01 10:06
I can't reproduce it with neither of the preferences. I've tried a number of different models and the screenshots are all "clean", without any border. Can you try again with models in the library ?

**Comment by AlexisDrogoul** [comment] 2016-08-04 07:53
Closing it temporarily as no one seems to be experiencing this issue. Please reopen with a test case where it manifests itself consistently on your configuration.

**Closed by AlexisDrogoul** 2016-08-04 07:53 UTC
Labels: > Enhancement, Display OpenGL
