### ISSUE TITLE
Partial overriding of actions in species

### ISSUE THREAD

**Issue by iamharshal** [gama-platform/gama#2040] opened 2016-11-01 05:35 UTC
Thanks a ton guys for GAMA.

Assuming a feature to call parent's actions is not currently available, I propose 'parent->action' to call parent's action.

A species can have many actions, which can be overridden using 'virtual: true'. However, one caveat is - Overridden action must be implemented completely, knowing implementation of parent species, which may not be always possible and desirable. There should a way to call parent's implementation (using, say similar to keyword 'super' in Java language). Of course, there can be ways to get this done by defining actions with certain convention (say 'impl_', etc), but may not be as elegant.

PS: It's embarrassing that I cannot take up this feature implementation myself due to some constraints, thought I would have loved to.

**Comment by AlexisDrogoul** [comment] 2016-11-02 09:21
Call it 'super' or 'parent->',  this issue is actually a duplicate of #2009  and will be closed (but #2009 will be kept alive, do not worry !). The current implementation of the language makes it difficult to do this, as we do not keep any reference, in the final compiled model, to the overriden actions.

I will dig deeper and try to find a solution --

**Closed by AlexisDrogoul** 2016-11-02 09:21 UTC
