### ISSUE TITLE
Null Pointer Exception on Batch experiment (parent experiment is working)

### ISSUE THREAD

**Issue by ierpe** [gama-platform/gama#2432] opened 2018-06-25 20:12 UTC
### Steps to reproduce
1. Create a child batch experiment that as a regular working experiment as parent

2. Launch Batch experiment

3. There's an error at initialization

I am using moving, fipa, simple BDI
My main experiment is working fine. When I launch the batch experiment it crashes : 

![screenshot from 2018-06-25 21-33-15](https://user-images.githubusercontent.com/790992/41872631-c38f2846-78c2-11e8-9c67-848ca4385348.png)

[java_error.txt](https://github.com/gama-platform/gama/files/2134593/java_error.txt)

The model in question : https://github.com/ierpe/Cognitive_Biases_BDI

### System and version 
Which version of GAMA 1.7.0.201804170250
Debian SID
[gama-config-details.txt](https://github.com/gama-platform/gama/files/2134535/gama-config-details.txt)

**Comment by AlexisDrogoul** [comment] 2018-06-27 05:05
And does it work normally if you run a batch experiment that *is not* a child of another experiment ?

**Comment by ierpe** [comment] 2018-06-27 07:20
Hi, thanks for the answer.

I tried that but the error persists. 
Is the batch setting up locations in a different manner than with regular experiments?

If you want to have a look the experiment is in models -> main.gaml

**Comment by AlexisDrogoul** [comment] 2018-06-30 02:20
OK. I got it. This is due to the (rather strange) creation of agents you have in the `init`block of your experiment called "Main". Regular experiments create a default simulation and this creation of agents happens within it. However, batch experiments do not create a default simulation and their init block is run without any simulation running inside them. Hence the various errors you get: your agents can't find a "world" to be placed in. 

So the advised way of doing what you want to do is to create the agents within the `init`of the simulation (and not within that of the experiment). That way, they are created once the simulation (or the world) itself is created, not independently. 

I noticed also some other errors, like a division by zero in the save (due to the fact that the `nb_res` attribute is not yet updated). But basically your problem comes from the previous point. 

As it is not a bug of GAMA by itself (although we might want to document this), I will close the issue. Please reopen if you still cant get your model to run.

**Closed by AlexisDrogoul** 2018-06-30 02:20 UTC

**Comment by ierpe** [comment] 2018-07-02 16:12
It does work thanks.

The thing is I need to create many experiments with different values for my agents (people species and fire species), so I wanted to be able to initialize different amount of agents or different agents all together from an experiment to another.
For exemple in on experiment I want to create 3 fires like this : 	
```
		create fire number: 1 with: [choosed_location::{ 420, 550 }]; // in the middle of the city
		create fire number: 1 with: [choosed_location::{ 180, 810 }]; // in the middle of the city
		create fire number: 1 with: [choosed_location::{ 595, 750 }]; // in the middle of the city
```
But in another experiment I do not want these fires... So creating them within the experiment made sense, or am I missing some other way of doing it here?

**Comment by AlexisDrogoul** [comment] 2018-07-03 00:22
Hi,

I think what you describe here is that the initial populations (incl. fires) are parameters (ie inputs) of the simulations. So why don't you treat them like this ? Of course, agents themselves can't be parameters, so you have to define, for instance, experiment parameters like the sizes of the populations (or the overall size of all the agents + the proportion of each kind of agents); for fires, you can define a list of locations as a parameter: the size of the list will be the number of fire agents, and their locations the locations within the list. Your model, on the other hand, needs to be a bit redefined so that populations are initialized using these parameters. 
To go a bit further, you could even push all of these data within CSV files, make these CSV files your experiment parameters and have your model read the initial parameters from it. 

Hope this helps ! 

Cheers
Alexis
