### ISSUE TITLE
Issue of CRS when importing shapefile data: inconsistency between data and CRS

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#2504] opened 2018-08-08 09:46 UTC
**Describe the bug**
When I run a model in which we import shapefile data (e.g. Tutorials / Road Traffic / model1.gaml), I get an Exception at the init, in particular that seems due to:
```
	geometry shape <- envelope(envelope(buildings_shapefile) + envelope(roads_shapefile));
```

I has the feeling that it was due to my Preferences, but try to reset them to initial values but get the same exception.

**To Reproduce**
1. Run the model Tutorials / Road Traffic /Model 01.gaml
3. See error

**Expected behavior**
No error

**Screenshots**
Here is the screenshot of the Exception:

<img width="1672" alt="capture d ecran 2018-08-08 a 11 43 38" src="https://user-images.githubusercontent.com/1555274/43829882-5d28430c-9b00-11e8-8ae5-0fe5c513e7d3.png">

In addition here are my Preferences relatively to data:

<img width="800" alt="capture d ecran 2018-08-08 a 11 38 55" src="https://user-images.githubusercontent.com/1555274/43829935-6e15c522-9b00-11e8-8d35-11befe864f0d.png">

**Desktop (please complete the following information):**
 - OS: macOS High Sierra
 - GAMA version: git
 - Java version: 1.8

**Comment by AlexisDrogoul** [comment] 2018-08-09 07:16
Cant reproduce it. The model is working correctly on my version (Git) / computer. 

The only difference I see is in the preferences: 

<img width="619" alt="image" src="https://user-images.githubusercontent.com/579256/43883844-9eae464e-9bde-11e8-9b47-c1c955103a40.png">

The grayed-out pref on the first CRS (which shouldn't normally be used...)

**Comment by benoitgaudou** [comment] 2018-08-09 07:30
Hi

You are right, when I change the grayed -out préférence to its initial
value (but keeping it grey), it works well...

So its seems that we have an issue with preferences on fact...
I can report it when back at home.

Thanks

Benoit

Le jeu. 9 août 2018 à 09:16, Alexis Drogoul <notifications@github.com> a
écrit :

**Comment by AlexisDrogoul** [comment] 2018-08-09 07:36
Well, not really an issue with preferences, more an issue with the meaning of these preferences. 

Actually, GAMA cannot "guess" anything from the data if no .prj is provided. So I guess the second preference will be used in that case. The first one is only to tell GAMA if it should pay attention to the .prj information or not (i.e. or always use the value of the 2nd pref). 

I can "ungrayout" these 3 preferences and explain that they will be used, anyway, when no projection information is available.

**Comment by AlexisDrogoul** [comment] 2018-08-09 17:32
Actually, only the first one needs to be made active (and a bit more explicit). The two others will always have at least one CRS/projection available (the one currently used in the model).

To close this issue, I will post a commit that always enables the first CRS and explains a bit better what it is meant for.

<img width="619" alt="image" src="https://user-images.githubusercontent.com/579256/43915409-d412a09a-9c34-11e8-8c92-dc5f9288df63.png">

**Closed** 2018-08-09 17:33 UTC
Labels: * Not reproducible, Concerns Data Persistence, Concerns Models Library, Topology GIS, Version Git
