### ISSUE TITLE
Load and save camera positions values directly in the layer side controls

### ISSUE THREAD

**Issue by pcaillou** [gama-platform/gama#1234] opened 2015-05-31 20:32 UTC
```
Describe which enhancement/addition to GAMA you would like to see:
Add the possibility to define and save the camera position from the layer side control.

It is already possible to set the value in the model using the facet camera_pos, camera_look_pos
and camera_up_vector. This solution is a nice way to define trajectory during a simulation
but the user cannot change the position of the camera during the simulation.

Thanks to the layer side control the the user can change and save the camera parameters.





```

Original issue reported on code.google.com by `agrignard` on 2015-05-27 17:44:46

**Comment by AlexisDrogoul** [comment] 2015-12-18 17:22
This issue is actually a duplicate of #579 . I close it.

**Closed by AlexisDrogoul** 2015-12-18 17:22 UTC
Labels: 1 - Ready, > Enhancement, Display All, Priority Medium
