### ISSUE TITLE
Parameter with new initial value in Multi-simulation

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#2970] opened 2020-04-12 23:16 UTC
**Describe the bug**

Let consider an experiment with multi-simulation (a simulation that creates new simulations).
Let consider a global variable with an initial value defined in the global. 
When this variable is defined as a parameter in the experiment and another initial value is given to it in the experiment, this new initial value is taken into account only in the default simulation and not in the other created simulations.

**To Reproduce**

As an example, see  `rate_similar_wanted` in the following example.

```
global {	
	int nb_people <- 2000;
	float rate_similar_wanted <- 0.4;
	float neighbours_distance <- 5.0;	
	
	// Global variable computing the number of happy people
	int nb_happy_people update: people count each.is_happy;
	
	init {
		create people number: nb_people;
	}
	
	reflex end_simulation when: nb_happy_people = nb_people {
		write "End of the simulation";
		do pause;
	}
}

species people {	
	rgb color <- flip(0.5) ? #yellow : #red;
	bool is_happy;
	
	list<people> neighbours update: people at_distance neighbours_distance;
	
	reflex compute_similarity {
		float rate_similar <- 0.0;
		if(empty(neighbours)) {
			rate_similar <- 1.0;
		} else {
			int nb_neighbours <- length(neighbours);
			int nb_neighbours_sim <- neighbours count (each.color = color);
			rate_similar <- nb_neighbours_sim / nb_neighbours;
		}
		
		is_happy <- rate_similar >= rate_similar_wanted;
	}
	
	reflex move when: not(is_happy) {
		location <- any_location_in(world);
	}
	
	aspect circle {
		draw circle(2) color: color border: #black;
	}
}

experiment expMulti type: gui {

	parameter "Nb people agents" var: nb_people min: 1 max: 5000 step: 1;
	parameter "rate similar wanted" var: rate_similar_wanted <- 0.65 min: 0.0 max: 1.0 ;
	parameter "neighbours distance" var: neighbours_distance step: 1.0;
	
	init {
		create simulation with: [seed::2];
		create simulation with: [seed::3];
		create simulation with: [seed::4];		
	}
	
	permanent {
		display series_happy {
			chart "happy people" type: series {
				loop simu over: simulations {
					data "happy"+int(simu)+ (simu.rate_similar_wanted) value: simu.nb_happy_people ;					
				}
			}
		}
	}	
}
```

We can observe that only the default simulation (id = 0) takes 0.65 as value for `rate_similar_wanted`.
<img width="346" alt="Screenshot 2020-04-13 at 06 10 07" src="https://user-images.githubusercontent.com/1555274/79082102-73625780-7d4d-11ea-979a-4426b7db7693.png">

**Desktop (please complete the following information):**
 - OS:  macOS 
 - GAMA version: 1.8 & git

**Comment by AlexisDrogoul** [comment] 2020-04-25 15:57
Yes. Right. It works more or less as intended... Only the first simulation is actually created with the initial settings of the parameters, as the others are created explicitly in the code. The parameters actually play the role of the `with:` facet for the initial simulation. 

I however agree that one thing is troubling: during execution, changing the value of a parameter does not change it for the first simulation but for...  the lastly created one (see gama-platform/gama#3876).

**Comment by hqnghi88** [comment] 2020-04-25 17:45
Is it pros or cons for 2968 then :D ?

**Comment by AlexisDrogoul** [comment] 2021-09-03 18:14
I would close this issue as the execution is correct. Unless you would like an enhancement (like a new facet in parameter to apply the value to all simulations ?)

**Comment by AlexisDrogoul** [comment] 2021-09-19 16:16
I'd like to mention that this behaviour can actually be implemented directly without changing (for the moment) the Java implementation. Simply add an "on_change" block to your parameter and either change the value directly in all simulations or call an action that does it. 

```gaml
experiment e {
    float v1 <- 0.0;
    parameter "Change everywhere" var: v1 {ask simulations {sim_v1 <- v1;}}
...
}
```

**Closed by AlexisDrogoul** 2021-09-19 16:16 UTC
Labels: >> 😱 Bug, 📃 Concerns GAML, Concerns Simulations, Version Git, Version 1.8.0
