### ISSUE TITLE
export/ save to geo-referenced tif with world file extension

### ISSUE THREAD

**Issue by sriramab** [gama-platform/gama#1859] opened 2016-06-02 17:18 UTC
Hi,

I would like to request options for GAMA to export a grid file with simulated grid_values to a georeferenced image with world file extension tfw? may be similar to the lines of save statement 

please see some terminology here, may be u call it with some other name in GAMA
https://github.com/domlysz/BlenderGIS/wiki/Import-georef-raster

see answer number2 here 
http://gis.stackexchange.com/questions/30498/how-to-export-save-a-layer-composition-to-geotiff

regards,
Srirama

**Comment by sriramab** [comment] 2016-06-03 10:13
I think generating the tifw file is not difficult. Here are the steps

The generated file should be an ascii file with  6 lines
line1: resolution of the grid in x direction in metric units 
line2: rotation_x, this is almost always zero unless the grid was rotated, so default =0
line3: rotation_y, this is almost always zero unless the grid was rotated, so default=0
line4: negative resolution of the grid in y direction in metric units, but I think for gama this can be positive as CRS starts from left top. And because gama has only regular grids (same x, y resolution) this can be same as line 1 with a negative sign
line5: should be the real world x coordinate of the centre of top left pixel, which in case of GAMA will be location.x of top left cell
line6: should be the real world y coordinate of the centre of the top left pixel, which in case of GAMA will be location.y of the top left cell 

[here](http://webhelp.esri.com/arcims/9.3/General/topics/author_world_files.htm) are more details of translation

however, I do not know how to convert GAMA grid to a GeoTIFF

**Comment by sriramab** [comment] 2016-06-05 05:40
Coule you please check again. It gives error and says: save statement expecting csv, text, asc, shp but not geotiff yet. Yes I updated GIT and fetch from upstream showed me this fix. So I am unsure why this syntax error.

**Comment by sriramab** [comment] 2016-06-05 11:01
Please also check that when saved, the resulting tiff is probably not restricted to the extent of the GAMA world. For example, if you open the Save Statement> Save to asc.gaml file and try to save the grid as a tiff, there will be a tiff in the folder. But if you open this tiff, it is so huge and the grid in the model appears like a tiny pixel somewhere in the middle of the tiff. Could you please see:

1. That the tiff respects the world extent
2. the extent represents a correct CRS. I am importing a asc of my study area to form a grid in GAMA, then when I save the gird as tiff, it should keep the extent and CRS as my asc

**Comment by ptaillandier** [comment] 2016-06-05 11:21
Hi,

1) The problem is not directly linked to the geotiff save statement, but to
the geotiff (and asc) viewer: indeed, as a cell in the grid is represented
by a pixel, most of time the resolution of the geotiff image will be pretty
low, and as we use an image viewer to open the image in GAMA, it is normal
to have these small images. We could add a new viewer dedicated to
georeferenced images to improve the rendering ofgeotiff (and asc file) :
add an issue concerning it if you want .

2) Can you share your model (with your data)? In my previous tests, the
geotiff generated was well georeferenced.

Cheers,

Patrick

2016-06-05 13:01 GMT+02:00 Srirama Bhamidipati <notifications@github.com>:

**Comment by sriramab** [comment] 2016-06-05 11:25
I will send it in private. 
I opened the resulting tiff in mac preview, it is the same problem, extent is not restricted to the file extents.

**Comment by sriramab** [comment] 2016-06-05 20:30
Thank you Patrick. The enhancement works for me.

**Comment by AlexisDrogoul** [comment] 2016-06-06 02:28
Should we close this issue, then ?

**Closed** 2016-06-06 03:37 UTC
Labels: > Enhancement, Concerns GAML, Concerns Modeling, Concerns Simulation
