### ISSUE TITLE
Display windows closing when changing layout mode

### ISSUE THREAD

**Issue by tcquang** [gama-platform/gama#2441] opened 2018-07-04 04:02 UTC
Dear team,
I have a small issue when changed the layouts of simulation that there are 2 displays :
1. Open a model that have 2 display windows (i.e. Segregation (Agents).gaml  in the Toy Models)
2. Run the simulation  ( 2 displays were stacked normally)
3. Change display mode: Open menu Views\ Layout displays\Horizontally: The displays have been closed.
4. Stop the simulation, then run the model again. The error messages appeared:
 at cycle 0: Java error: exception in Eclipse
in all_people <- list<people>(people);
PartInitException: Abnormal Workbench Condition
org.eclipse.ui.internal.WorkbenchPage.showView(WorkbenchPage.java:4340)
ummisco.gama.ui.utils.SwtGui.lambda$0(SwtGui.java:184)
ummisco.gama.ui.utils.WorkbenchHelper.run(WorkbenchHelper.java:90)
ummisco.gama.ui.utils.SwtGui.internalShowView(SwtGui.java:179)
ummisco.gama.ui.utils.SwtGui.showView(SwtGui.java:221)
msi.gama.outputs.AbstractDisplayOutput.lambda$0(AbstractDisplayOutput.java:39)
org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:37) 

I have tested on the version GAMA1.8_Win_64_07.03.18. It works fine with my older version (GAMA1.8_Win_64_06.10.18). Windows 64bits. Java 1.8.

Thank you,
Best regards,
Quang
![display_issue](https://user-images.githubusercontent.com/11825516/42256079-2c84b976-7f79-11e8-8be2-7f8e0b1b9b21.JPG)

**Comment by AlexisDrogoul** [comment] 2018-07-04 04:20
I have to say that the layout of displays is still experimental (should be stated so in the menu) and that it is not safe to use it with Java2D displays, esp. charts. Have you tried to increase the delay between the opening of displays in the preferences ?

**Comment by tcquang** [comment] 2018-07-04 13:01
Dear Mr. Drogoul,
I have tried with opengl displays, but it gave the same issue.
This is the tested model:

model testView1

global {
	/** Insert the global definitions, variables and actions here */
	init{
		create pointTest number: 10;
	}
}
species pointTest{
	aspect default {
		draw circle(1) color:#red;
	}
	
}
experiment testView1 type:gui {
	/** Insert here the definition of the input and output of the model */
	output {
		display Dp1 type:opengl{
			species pointTest;
		}
		display Dp2 type:opengl{
			species pointTest;
		}
	}
}

**Comment by AlexisDrogoul** [comment] 2018-07-04 14:12
No, it works for me perfectly under MacOSX. Can you try with a new (and fresh) workspace ?

**Comment by AlexisDrogoul** [comment] 2018-07-04 14:57
This is normal: if you don't specify a layout in your model, the default layout is the one defined in the preferences (either #none or #stack). The previous layout don't stick anymore -- I will make it soon a preference, though, so that you can always get the same layout as the previous one you used, and I will also add the possibility in the menu to save it (in memory for the moment) and come back to the previously saved one. Later, these layouts will be saved along with the models, but not for the moment... .

**Comment by tcquang** [comment] 2018-07-04 15:05
There are somethings wrong with me.
I tested on GAMA1.8_Win_64_07.04.18_7f6bd2d. With new workspace, It works well on opengl. But in java2d, It gave exceptions: 


2 occurrences in 2 agents at cycle 0: Java error: nil value detected
in 
NullPointerException: null
ummisco.gama.opengl.SWTOpenGLDisplaySurface.outputReloaded(SWTOpenGLDisplaySurface.java:322)
ummisco.gama.ui.utils.SwtGui.getDisplaySurfaceFor(SwtGui.java:272)
msi.gama.outputs.LayeredDisplayOutput.createSurface(LayeredDisplayOutput.java:477)
msi.gama.outputs.LayeredDisplayOutput.init(LayeredDisplayOutput.java:414)
msi.gama.runtime.ExecutionScope.lambda$4(ExecutionScope.java:436)
msi.gama.runtime.ExecutionScope.runAndCatch(ExecutionScope.java:459)
msi.gama.runtime.ExecutionScope.init(ExecutionScope.java:436)
in agents Simulation 0, testView10

**Comment by AlexisDrogoul** [comment] 2018-07-04 15:10
Hum. This is happening sometime when you change the type of the display (from Java2D to OpenGL or reversely). The old views somehow "stick" somewhere in memory (I couldn't find a way to erase them completely) and SWT tries to reopen them instead of opening new views. This can be solved by giving them new names.

**Comment by AlexisDrogoul** [comment] 2018-07-05 08:35
Hum... So shall we close it ? I will try to have a fix for the second bug you reported.

**Comment by tcquang** [comment] 2018-07-05 08:53
Yes, of course. It seam only me who has the issue. I am trying to fix the issue on my computer. Now I can't launch experiments with 2 displays.   
Thank you!

**Comment by tcquang** [comment] 2018-07-05 09:11
I have solved the problem for me. 
I uninstalled Java, clean my computer and registry ( by CCleaner) then reinstall Java.
Thank you for your times!

**Comment by AlexisDrogoul** [comment] 2018-07-07 14:43
And what happens when you close the simulation and relaunch it ?

**Comment by hqnghi88** [comment] 2018-07-07 14:44
Well, some exception as quang posted

**Comment by AlexisDrogoul** [comment] 2018-07-07 15:51
Cant reproduce it, neither on Windows 10 nor on macOSX.

**Comment by hqnghi88** [comment] 2018-07-07 16:46
It should be wrong somewhere, i 've just tested on ubuntu, and it is not working now, as i tried once before there was no problem.

**Comment by AlexisDrogoul** [comment] 2018-07-07 17:05
Two things:

- the fixes were for Win32 only (you can see the flags additions/removals), so it probably did not work before that. But please test only for Win32 for the moment, it is already quite complicated !
- what means "not working" ?

**Comment by hqnghi88** [comment] 2018-07-07 17:09
Yes, i see your newest commit is win32 case.
But i mean "not working" because i tested one time before the restructuring of swt awt event, and it can change layout. And now, the phenomenon on ubuntu is as same as win, when clicked on layout, nothing shown, when stop and relaunch sim -> exception "Abnormal...."

**Comment by AlexisDrogoul** [comment] 2018-07-07 17:16
Yes, but the important point is: does it work on Windows (i.e. the focus of this thread) ? This bug seems to be more or less random, and Ubuntu is a hopeless OS, so let's just put it aside now. 
I cannot reproduce it at all. I tried many configurations, but no way. So, if it happens on Windows, can you also test if creating a new workspace allows it to work ?

**Comment by hqnghi88** [comment] 2018-07-07 17:31
New workspace make it work on both win and ubuntu. I think i was trying to change the delay of opening, and the problem occured ( not sure, but there are only few issue i was trying yesterday). It seem your correction of timing help this issue. BUT i realize a really decrease speed with same setting to open several displays than before.

**Comment by tcquang** [comment] 2018-07-07 17:32
Hi Nghi, did you try to clean the Registry of Windows (by using CCleaner)?

**Comment by hqnghi88** [comment] 2018-07-07 17:33
If you say registry, Quang, i  feel more confident on the delay time problem because it is written in registry (preference on windows).

**Comment by AlexisDrogoul** [comment] 2018-07-08 02:16
That's the purpose of timing :) What seems to happen (a bit randomly), is that the "displays" placeholder belonging to the simulation perspective is marked as "hidden" from this perspective and then written back to disk in this state. The only problem is that I don't really understand why, where and when this happens...

**Comment by AlexisDrogoul** [comment] 2018-07-27 12:49
I am trying another strategy, since renaming the parts seem to have an effect on the occurence of this bug (this strategy will also solve the problem of keeping the same name for an OpenGl and a Java2D display): that of randomising part of the secondary id of the view; i.e. just before opening the view, I add a random and unique component (`System.getMilliseconds()` or anything else), which I erase as soon as the view is open. That way, the workbench always thinks it is opening "new" views. I tested it for multi-simulations, co-modeling and normal simulations, and it seems to work without problem.

**Comment by AlexisDrogoul** [comment] 2018-07-27 13:37
Can you try your "dirty work" of launching, playing with layout, quitting, launching, playing with layout, quitting, launching,playing with layout, quitting, launching,playing with layout, quitting, launching,playing with layout, quitting, launching,playing with layout, quitting, launching,playing with layout, quitting, launching,playing with layout, quitting, launching,playing with layout, quitting, launching,playing with layout, quitting, launching,playing with layout, quitting, launching,playing with layout, quitting, launching ... ? 😄

**Comment by hqnghi88** [comment] 2018-07-27 13:49
A new exception in the dirty workspace. Im looping on a new workspace to see...
```
!ENTRY org.eclipse.equinox.event 4 0 2018-07-27 20:46:41.669
!MESSAGE Exception while dispatching event org.osgi.service.event.Event [topic=org/eclipse/e4/ui/model/ui/UIElement/visible/SET] {ChangedElement=org.eclipse.e4.ui.model.application.ui.advanced.impl.PlaceholderImpl@6272936b (elementId: msi.gama.application.view.OpenGLDisplayView:CityScopeTable@@@1532699200940, tags: [], contributorURI: null) (widget: Composite {}, renderer: org.eclipse.e4.ui.workbench.renderers.swt.ElementReferenceRenderer@ff0e6d4, toBeRendered: true, onTop: false, visible: false, containerData: null, accessibilityPhrase: null) (closeable: false), org.eclipse.e4.data={ChangedElement=org.eclipse.e4.ui.model.application.ui.advanced.impl.PlaceholderImpl@6272936b (elementId: msi.gama.application.view.OpenGLDisplayView:CityScopeTable@@@1532699200940, tags: [], contributorURI: null) (widget: Composite {}, renderer: org.eclipse.e4.ui.workbench.renderers.swt.ElementReferenceRenderer@ff0e6d4, toBeRendered: true, onTop: false, visible: false, containerData: null, accessibilityPhrase: null) (closeable: false), AttName=visible, EventType=SET, OldValue=true, Widget=Composite {}, NewValue=false}, AttName=visible, EventType=SET, OldValue=true, Widget=Composite {}, NewValue=false} to handler org.eclipse.e4.core.di.internal.extensions.EventObjectSupplier$DIEventHandler@42fe9099
!STACK 0
org.eclipse.e4.core.di.InjectionException: java.lang.NullPointerException
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:65)
	at org.eclipse.e4.core.di.internal.extensions.EventObjectSupplier$DIEventHandler.handleEvent(EventObjectSupplier.java:88)
	at org.eclipse.equinox.internal.event.EventHandlerWrapper.handleEvent(EventHandlerWrapper.java:201)
	at org.eclipse.equinox.internal.event.EventHandlerTracker.dispatchEvent(EventHandlerTracker.java:197)
	at org.eclipse.equinox.internal.event.EventHandlerTracker.dispatchEvent(EventHandlerTracker.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:148)
	at org.eclipse.equinox.internal.event.EventAdminImpl.dispatchEvent(EventAdminImpl.java:135)
	at org.eclipse.equinox.internal.event.EventAdminImpl.sendEvent(EventAdminImpl.java:78)
	at org.eclipse.equinox.internal.event.EventComponent.sendEvent(EventComponent.java:39)
	at org.eclipse.e4.ui.services.internal.events.EventBroker.send(EventBroker.java:52)
	at org.eclipse.e4.ui.internal.workbench.UIEventPublisher.notifyChanged(UIEventPublisher.java:60)
	at org.eclipse.emf.common.notify.impl.BasicNotifierImpl.eNotify(BasicNotifierImpl.java:374)
	at org.eclipse.e4.ui.model.application.ui.impl.UIElementImpl.setVisible(UIElementImpl.java:345)
	at ummisco.gama.ui.commands.ArrangeDisplayViews.lambda$4(ArrangeDisplayViews.java:128)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at ummisco.gama.ui.commands.ArrangeDisplayViews.hideDisplays(ArrangeDisplayViews.java:127)
	at ummisco.gama.ui.commands.ArrangeDisplayViews.execute(ArrangeDisplayViews.java:97)
	at ummisco.gama.ui.commands.ArrangeDisplayViews.execute(ArrangeDisplayViews.java:72)
	at ummisco.gama.ui.commands.ArrangeDisplayViews.execute(ArrangeDisplayViews.java:61)
	at ummisco.gama.ui.factories.DisplayLayoutFactory.lambda$0(DisplayLayoutFactory.java:38)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:37)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:182)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4213)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3820)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1150)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1039)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:680)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:594)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at msi.gama.application.Application.start(Application.java:83)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1499)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1472)
Caused by: java.lang.NullPointerException
	at org.eclipse.e4.ui.workbench.renderers.swt.ContributedPartRenderer$1.setFocus(ContributedPartRenderer.java:103)
	at org.eclipse.swt.widgets.Composite.setFocus(Composite.java:1099)
	at org.eclipse.swt.widgets.Composite.setFocus(Composite.java:1099)
	at org.eclipse.swt.widgets.Control.fixFocus(Control.java:1069)
	at org.eclipse.swt.widgets.Control.setVisible(Control.java:4017)
	at org.eclipse.swt.custom.CTabItem.setControl(CTabItem.java:290)
	at org.eclipse.e4.ui.workbench.renderers.swt.StackRenderer.hideChild(StackRenderer.java:979)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.subscribeVisibilityHandler(PartRenderingEngine.java:232)
	at sun.reflect.GeneratedMethodAccessor32.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:55)
	... 46 more
```

**Comment by AlexisDrogoul** [comment] 2018-07-27 14:03
Hum... The problem is that I don't know how you manage things, but I can't reproduce it 😞

**Comment by hqnghi88** [comment] 2018-07-27 14:06
[gama_workspacesaasa.zip](https://github.com/gama-platform/gama/files/2236011/gama_workspacesaasa.zip)
Here is the broken workspace . I post new issue on how to make it broken.

**Comment by AlexisDrogoul** [comment] 2018-07-28 16:09
I normally have killed this bug. What I did was to compare a "fresh" `workbench.xmi` file (the file saved periodically and at the closing of GAMA) with a "corrupted" one. I found that in the corrupted one, there were traces of temporary perspectives that were persisted -- I don't know how, but anyway.
So, now, at startup, GAMA inspects the workbench definition and removes all "dirty" perspectives, as well as at shutdown. So both situations are covered : if a freeze happens and GAMA has saved a dirty perspective, it is removed at start-up. And those still in memory (there shouldn't be any, but who knows ?) at shutdown are removed before the state of the benchmark is saved. This should normally alleviate the problem described in this issue. 

Please test !

**Comment by hqnghi88** [comment] 2018-07-28 16:50
I just tested quickly with my 2 dirty workspaces. It seem a double kills or triple kills. you prevent this issue on any dirty workspace of broken gama.
Congrat!!!!
Cheers.

**Closed by hqnghi88** 2018-07-28 16:50 UTC
Labels: > Bug, Affects Usability, Concerns Interface, Concerns Simulation, Display All, OS All, Priority Critical, Version Git
