### ISSUE TITLE
Add a 'Ready' status

### ISSUE THREAD

**Issue by sriramab** [gama-platform/gama#1945] opened 2016-07-25 11:42 UTC
Hi

Sometimes when you start Gama, it does some processes (cleaning, updating editor, documentation something) in background. This can been seen at the bottom right of the window. Sometimes, I miss to see this progress and click on experiment to run the simulation. This hangs Gama and sometimes also delays (and hangs) the displays to be shown. I have to force quit and start again. 

Would it be possible to show in the status bar of Gama, something like 'Gama Engine is now Ready' or something to that effect? Then a user knows, that gama is ready to take commands, coding, user inputs. :) 

Thanks

**Comment by AlexisDrogoul** [comment] 2016-07-27 17:37
Does the hang happen only when trying to run a simulation too early ? Or is it also concerning the edition of models, etc. ?

**Comment by sriramab** [comment] 2016-07-28 06:26
Apart from the case stated above. GAMA also hangs when you do some additions (edits) in code and run the model again. Mostly this hang is related to running the simulation. In other instances, I cannot reproduce the error. However, I notice that some models ( same model) hangs in different versions of GAMA. A model that does not run in new version (hangs) .. does not hang in old version. So I cannot state a clear case for duplication. I have observed this mostly in grid models and models with more than 3 species coming from shapefiles.

**Comment by sriramab** [comment] 2016-07-28 06:29
With regards to the case of shapefiles, some versions of GAMA checked for all 5 associated files of a .shp, while some versions of GAMA do not. Those which look for all 5 associated files - hang. This became clear to me when I run the model in Eclipse GIT version, where I could see red error lines in the console window stating .shx as missing. 

This is also the case when you run headless mode, gama looks for all 5 siblings, but the GAMA gui does not.

**Comment by sriramab** [comment] 2016-08-01 09:13
Running a same model in quick succession also hangs GAMA. 
Open a model, run it. Suddenly you notice a mistake. you quickly close the simulation. make some small change in the code/ or may be not change the code.... in both cases, if you quickly hit the experiment button.. GAMA hangs :( :( 

version, standalone, 2016-0801-0315 mac mavericks, java 8.

**Comment by AlexisDrogoul** [comment] 2016-08-01 09:53
I can't reproduce this on the library models. So I guess it is more or less linked with the use of complex GIS data (shape files, etc.) ?

**Comment by sriramab** [comment] 2016-08-01 10:11
For me it happens also on non gis models. You have to close a running simulation, quickly in a second or two you reload the experiment.

**Comment by AlexisDrogoul** [comment] 2016-08-02 09:28
OK. Can you give an example of a library model where it happens consistently for you ? I've tried approx. 40 of them and can't reproduce the behavior. In which version does it happen, by the way ?

**Comment by sriramab** [comment] 2016-08-02 13:13
Could you try this attached file. It hangs on my machine if I open, hit run experiment, close and then run again within a second or two. I then close GAMA, and if I open GAMA by clicking the icon in the dock, it take forever (hangs) to open GAMA. However if I open GAMA after 5 or so minutes, GAMA opens normally. 

Could it be that I need to clean some gama cache ? may be some cache makes it slower ?

my mac configuration Mac Dual Core 2.5GHz, 16GB Ram, Mavericks. I am using GAMA 1 August 2016 Nightly build.

**Comment by AlexisDrogoul** [comment] 2016-08-03 01:52
OK. I still can't reproduce it, so here are some things to try on your side:

- does the same happen in the developer version (not the build) ?
- does it happen in a clean workspace ?
- do you have a large number of files in your workspace (and a large number of GIS related files) and are their folders opened all the time ? 
- in your preferences, are you using multiple threads for running simulation or only a single one ?
- in the preferences again (in "Performances") do you have a delay for opening displays ? 

Thanks to review all of this when you can so I can diagnose what happens !

**Comment by sriramab** [comment] 2016-08-03 06:41
I will check them. For sure number 3 is always the case. Atleast 10-15 files are open.
Do you recommend a new workspace for every project? Because I create projects in same workspace since 3 years now, there are like 10 or more projects in the same workspace. And each projects has many models and many gis files, that is also why when I use TODO it was giving me so many todos.

Others I will check and inform. I stopped using developer version (if you mean eclipse that is), eclipse scares me and gets me errors that i dont understand and I get tired of updating /syncing workspaces and only to get more errors. I just use the nightly builds on github and run the zipped app.

**Comment by sriramab** [comment] 2016-08-03 06:43
Or do you think it could be the graphics card? I use 13" pro, and they dont have a strong graphics card.

**Comment by AlexisDrogoul** [comment] 2016-08-03 11:11
Actually, having one workspace per project can be a good idea (it is strongly advised for Eclipse, for instance). If you think it might be the graphics card, one thing can be to play a bit with the preferences in "Performances", although I'm not completely sure they will help for this problem.

**Comment by AlexisDrogoul** [comment] 2016-08-04 06:29
Another solution (if you dont want to have multiple workspaces) is to close the projects you are not working on (contextual menu in the navigator then `Close Project`).

**Comment by sriramab** [comment] 2016-08-08 09:54
Closing projects seems helpful. Thank you.

**Comment by AlexisDrogoul** [comment] 2016-08-26 06:09
The latest commit should also alleviate the problems of "resources" by considerably improving the compilation time and the memory footprint. Might be worth to check again on the latest version with multiple projects open. Meanwhile, I close the issue.

**Closed by AlexisDrogoul** 2016-08-26 06:09 UTC
Labels: > Enhancement, Affects Performance, Affects Stability, OS OSX, Version 1.7 beta
