### ISSUE TITLE
Open GL Texture on Ubuntu LTS 14.04 

### ISSUE THREAD

**Issue by DamPhil** [gama-platform/gama#1238] opened 2015-06-04 03:42 UTC
Trying to execute Procedural City model, Gama crashes and
throw the following message : 
Renderer initializing to 983 , 148 with drawable: SWT-GLCanvas[Realized true,
	jogamp.opengl.x11.glx.X11OnscreenGLXDrawable,
	Factory   jogamp.opengl.x11.glx.X11GLXDrawableFactory@30bbe83,
	handle    0x4a00002,
	Drawable size 983x148,
	SWT size 983x148]
Renderer reshaping to 0,0,983 , 148
Renderer reshaping to 0,0,983 , 138
Building texture : BufferedImage@179fd646: type = 5 ColorModel: #pixelBits = 24 numComponents = 3 color space = java.awt.color.ICC_ColorSpace@12f35f77 transparency = 1 has alpha = false isAlphaPre = false ByteInterleavedRaster: width = 197 height = 197 #numDataElements 3 dataOff[0] = 2
intel_do_flush_locked failed: No such file or directory

**Comment by AlexisDrogoul** [comment] 2015-06-04 08:56
Hum… I guess, given the log, that it takes place in the GIT version, isnt'it ?  Is there a more precise log available ? I think it should be interesting to enable the DEBUG mode of JOGL to have more information on what's going on internally. Look on the JOGL site to see how to enable DEBUG. Another first test would be to download the complete set of JOGL jars and launch the test from the terminal. Again, instructions are available on the JOGL site.

**Comment by agrignard** [comment] 2016-01-16 18:37
Any update on this one? Is it still occuring?

**Comment by AlexisDrogoul** [comment] 2016-01-27 02:31
W/o any more news, I push this back to the release of GAMA 1.7. A lot of tests have to be done on Ubuntu, anyway (see #1366, for instance )

**Comment by AlexisDrogoul** [comment] 2016-02-24 08:55
OK. I think I've found the cause of this Issue and #1505. Please have a look here: https://jogamp.org/bugzilla/show_bug.cgi?id=873

So, basically, what causes this crash is the lack of support of shared OpenGL contexts by the Intel driver on Ubuntu (13, 14, 15). Shared GL contexts were introduced in GAMA 1.7 as a way to cache common images and textures between several OpenGL displays (and also as a way to do some non-UI blocking loading of these textures). 

I will try to see (1) how to detect these configurations when launching JOGL; (2) how to disable shared contexts in this case (and rely on a single-threaded, context-bound loading mechanism).

Closing this one as a duplicate of #1505, anyway.

**Closed by AlexisDrogoul** 2016-02-24 08:56 UTC
Labels: > Bug, Affects Usability, Display OpenGL, OS Linux, Version Git
