### ISSUE TITLE
facet position with negative value

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#2164] opened 2017-04-04 13:48 UTC
Not sure if it's a bug but I'm a bit surprised by the behavior of the facet position with negative value in x and y

### Steps to reproduce
1. in road traffic if you do
species building aspect: base;
species building aspect: base position:{1000,0,0};
species building aspect: base position:{-1000,0,0};

<img width="699" alt="screen shot 2017-04-04 at 09 41 09" src="https://cloud.githubusercontent.com/assets/3928502/24659507/e3a220b0-191a-11e7-8a8c-ebee00601254.png">

### Expected behavior
I would expect to haev a symetric view

### Actual behavior
The negative one (-1000) is not well placed

### System and version 
GAMA RC1

**Comment by AlexisDrogoul** [comment] 2017-04-06 05:26
Closed as it is a duplicate of #1555. Use `species building aspect: base position:{-1000-world.shape.width,0,0};` as a temporary workaround (see the explanation in #1555). It will allow to obtain this:

![road_traffic - users drogoul documents git gama msi gama models models features 3d visualization models building elevation gaml 2017-04-06 12-25-09](https://cloud.githubusercontent.com/assets/579256/24739070/411b9c58-1ac4-11e7-87be-677808171bc1.png)

**Closed by AlexisDrogoul** 2017-04-06 05:26 UTC
Labels: Display OpenGL
