### ISSUE TITLE
Add examples of co-models and models coupling in Model Library

### ISSUE THREAD

**Issue by AlexisDrogoul** [gama-platform/gama#1406] opened 2016-01-16 19:16 UTC
The title says all !

**Comment by AlexisDrogoul** [comment] 2016-01-27 02:06
I've tried to run the model and it appears broken. A StackOverflow exception is raised at some point when it is instantiating the agents and it doesn't open.

**Comment by hqnghi88** [comment] 2016-01-27 02:21
Dear Alexis,
I cant reproduce the exception. I'm trying to.

HUYNH Nghi
[Vietnam] +84909128322
GAMA http://www.gama-platform.org/

**Comment by hqnghi88** [comment] 2016-01-27 03:16
Dear Alexis,
Could you please provide the log file, i still cant reproduce it with a git reset.
Thanks.

**Comment by AlexisDrogoul** [comment] 2016-03-12 06:33
Hi Nghi,

The model is loading correctly, but nothing happens (i.e. the displays are drawn, everything seems alright, but playing the model does not change anything on the displays).

Do you have the same behavior ?

Alexis

PS: I would also be in favor of having a more "pedagogical" model, which would show how to define experiments with different combinations of models, how to replace micro-models dynamically, etc.

**Comment by hqnghi88** [comment] 2016-03-12 07:09
Dear Alexis, I have push a fix yesterday night, it cause by the enhance of
multisimulation. Could you recheck the model. It would have three display:
a boids, an ants and the combination of "ants inside boids" (the ants find
and take food inside a boids. It would be then the idea, the micro-model of
epidemiology - the virus - evolve inside the host). I am working to
proposed other one that show the things you mentioned.
Cheers.

**Comment by hqnghi88** [comment] 2016-03-28 08:22
Dear Alexis, Patrick,
I have push some more examples on urban+traffic, flood+evacuation and a syntax model. Could you please check its meaning and give comments by the way.
Cheers.

**Comment by AlexisDrogoul** [comment] 2016-04-08 03:23
I havent checked yet. Are the models sufficiently commented ? @dphilippon , can you check them and provide any comments ? As soon as you consider they are ok, we might close this issue.

**Comment by dphilippon** [comment] 2016-04-08 03:37
As far as i know, they seem okay. However, I personally think the tags in the models should be added (the ones with Lô as author mainly), with a little more commentaries on the code (not on the description), more explicit variables and reflex names (not p and c, and dododo ;) ). Another thing that would be interesting, in the flood evacuation model, would be to add a monitor, or something just to know how many people are 'killed' by the flood and how many are saved.

**Comment by hqnghi88** [comment] 2016-04-08 06:43
Hi, I am doing the job and will close this soon.

**Closed** 2016-04-09 09:01 UTC
Labels: > Bug, Affects Stability, Concerns GAML, Concerns Modeling, In Models Library, OS All, Priority Critical, Version Git
