### ISSUE TITLE
copy/paste in search box doesn't work

### ISSUE THREAD

**Issue by sriramab** [gama-platform/gama#1755] opened 2016-05-16 15:45 UTC
In the editor, there is a search box with blue background. In this box, if you want to paste something: it is possible with a mouse>right click>paste but if you try keyboard shortcut ctrl+v; it does not work.

Ideally if would be nice that as soon as user double clicks and selects a piece of text, this text is already suggested in the blue search box, like it usually is the case with the find/replace dialog. 

Please see this may be combined to #1744

**Comment by sriramab** [comment] 2016-05-16 15:49
When you place the cursor in the search box, and do ctrl+v; the text is pasted on the current active line in the code editor and not in the search box.

**Comment by AlexisDrogoul** [comment] 2016-05-16 15:50
Closed as a duplicate of #1295 . The "correct" behavior for the search box (accepting copy and paste) has been reverted, by the way, as it was conflicting with copy and paste in the navigator ( #1393)

**Closed by AlexisDrogoul** 2016-05-16 15:50 UTC
Labels: > Bug, Affects Usability, Concerns Modeling, OS OSX
