### ISSUE TITLE
Calling Web Service from ABM

### ISSUE THREAD

**Issue by smas1** [gama-platform/gama#1905] opened 2016-07-01 06:40 UTC
Greetings All,

I want to call a web service using Gama-Platform. Is there any built in support or if not then how can i write a custom plugin for this?

**Comment by mazarsju** [comment] 2016-07-01 07:23
Hi,

I don't know exactly what do you want to do, but two trainees are already working on a way to display a simulation (only for OpenGL displays) in a browser using webGL, through a web service. The idea is to be able to launch a simulation of GAMA from a client machine, GAMA is executed in the server machine and send the graphic scenes which are displayed correctly in the client machine.

They just began 2 weeks ago, we hope the work will be done for next September.

**Comment by smas1** [comment] 2016-07-01 07:54
Thanks

I am trying to call a recommendation engine exposed as service from ABM. i was unable to find any operator for calling a web service. 

i just want to know that If there is any built in support for calling any http service and if not then how to customize it using JAVA for fulfilling the requirement.

**Comment by mazarsju** [comment] 2016-07-01 08:04
Oh ok sry I misunderstood you... I don't really know, maybe in the plugin "network" you can find some interesting stuff, but I can't find the documentation about it anymore... @agrignard and @stouhbi will answer you better than me for that.

**Comment by smas1** [comment] 2016-07-03 05:27
Thanks
but how you are planning to send the Gama graphics to client machine ? 

there must be some mode of communication

**Comment by mazarsju** [comment] 2016-07-06 03:58
Yes, we are planning to send all the graphical informations to a client machine. Some works are in progress, currently in the plugin "opengl", package "ummisco.gama.webgl" (see the "SceneReceiver" class), in the git version.

**Comment by AlexisDrogoul** [comment] 2017-02-28 19:11
Closing this issue while cleansing the backlog. Please reopen if still needed. Such a service could be easily (more or less!) implemented by designing a specific plugin (exposing dedicated primitives) or by using the network plugin, which can handle low-level communication with servers.

**Closed by AlexisDrogoul** 2017-02-28 19:11 UTC
Labels: > Enhancement
