### ISSUE TITLE
Wrong building of graph from skeletonize

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#1262] opened 2015-07-08 14:40 UTC
Import and run the attached model.
It contains a bounds shapefile and some obstacles and build the graph of shortest paths from the free space.

But it appears that some edges seems to miss in the graph (see the run of the model).

GAMA SVN, MACOSx

Benoit

PS : see below the model.
It is an archive (zip), but I rename it in order that Github accept it.
To get it, download the file on your computer, rename it and replace .png by .zip and unzip it :-)
![testgraphbuilding zip](https://cloud.githubusercontent.com/assets/1555274/8573015/cea52e94-258f-11e5-8708-4f65f58f794d.png)

**Comment by AlexisDrogoul** [comment] 2015-07-08 14:46
I think that "skeletonize" relies on the triangulation in JTS, and I know that this operation can sometimes fail (I replaced it by the OpenGL equivalent for the display). Could it be the cause here ?

**Comment by benoitgaudou** [comment] 2015-07-08 14:50
In fact I do not know exactly which one in the 2 following one returns a not so good result:
		list<geometry> skeletons <- skeletonize(region_move);
		list<geometry> skeletons_split  <- split_lines(skeletons);

On the screenshot, we can observe some missing edges...

Benoit 

<img width="1552" alt="capture d ecran 2015-07-08 a 16 49 43" src="https://cloud.githubusercontent.com/assets/1555274/8573341/5dbe454c-2591-11e5-93e4-75d931bc9ef0.png">

**Comment by benoitgaudou** [comment] 2015-07-09 10:22
I notice that in my shapefile the obstacles are well in line.
I am trying to move a little bit the obstacles to break these lines. In this case additional edges are created.

**Comment by ptaillandier** [comment] 2015-07-09 16:40
I will try to find the bug (not link to the triangulation, but more to the way "links" are derived from triangles).

**Comment by ptaillandier** [comment] 2015-07-10 12:27
ok, fixed by the last commit.

**Closed by ptaillandier** 2015-07-10 12:27 UTC
Labels: > Bug, OS All, Priority High, Topology GIS, Topology Graphs, Version Git
