### ISSUE TITLE
use of "agents" in a species reflex

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#2402] opened 2018-04-10 08:23 UTC
### Steps to reproduce
1. Try to use agents in a reflex in a species:
```
model TestAgents

global {
	init {
		create people number: 2;
	}
	
	reflex r2 {
		write "in GLOBAL = " + agents;
	}	
}

species people {
	reflex r {
		write "in species = " + agents;
	}
}

experiment TestAgents type: gui {
	/** Insert here the definition of the input and output of the model */
	output {
	}
}
```

### Expected behavior
I was expected to get the list of all agents, in both the global and in any species.

### Actual behavior
agents returns the list of all agents only in the global.
It returns an empty list in a species.

### System and version 
GAMA 1.8 RC, MacOSX

**Comment by hqnghi88** [comment] 2018-04-10 08:29
I get this
in GLOBAL = [people(0),people(1)]
in species = [people(0),people(1)]
in species = [people(0),people(1)]
Did i missed some steps to reproduce it?

**Comment by benoitgaudou** [comment] 2018-04-10 08:31
... OK ... I have to check my combinaison GAMA + Git version ...
because I get :
in GLOBAL = [people(0),people(1)]
in species = []
in species = []

2018-04-10 10:29 GMT+02:00 HUYNH Quang-Nghi <notifications@github.com>:

**Comment by benoitgaudou** [comment] 2018-04-10 08:34
I confirm that, with the up-to-date GAMA Git version on oxygen, master branch... 
I get: 
in GLOBAL = [people(0),people(1)]
in species = []
in species = []

**Comment by hqnghi88** [comment] 2018-04-10 08:37
In that case, could you please, include the prefs. gaml , please?

**Comment by benoitgaudou** [comment] 2018-04-10 09:02
Here is the file.

[preferences.gaml.zip](https://github.com/gama-platform/gama/files/1893890/preferences.gaml.zip)

**Comment by benoitgaudou** [comment] 2018-04-10 09:34
I have basically the default preferences.

Do you have some magic ones, that fix automatically all the issues ?
:-)

2018-04-10 11:21 GMT+02:00 HUYNH Quang-Nghi <notifications@github.com>:

**Comment by sriramab** [comment] 2018-04-10 10:39
Strangely, I get a blank console :laughing:

**Comment by hqnghi88** [comment] 2018-04-10 15:26
It takes time to answer because it was 
	gama.pref_optimize_agent_memory <- false;
cause this issue. No idea why an true can make it works

**Comment by hqnghi88** [comment] 2018-04-11 16:30
I have no solution when this preference is changed. Actually, AFAIK, when using the optimization of memory, all agent will lost all complex attributes, such as the macro-micro populations, to speed up the simulation.  So, when optimized, micro agents cannot know an attribute of macro agent (world), as described for the variable "agents" : The list of agents registered in this physical world . The workaround is using the world.agents. And may be a validator that emit warning which such value of preference.

**Comment by AlexisDrogoul** [comment] 2018-04-12 00:10
Hi,

yes. The default preference (pref_optimize_agent_memory set to true) causes this behaviour. `agents` in this case is the global attribute. If set to false, then `agents` becomes an attribute of the species. 

This process is implemented at the compilation level, by automatically detecting (if set to true) if a species contains -- or not -- a sub-species. 

You can check this by turning it on and off and recompiling a model (and then hovering over `agents`). Although I admit that the sub-title is a bit misleading... 

![ssss - essai models new model gaml - gama runtime 2018-04-12 09-05-45](https://user-images.githubusercontent.com/579256/38649395-403b08d2-3e31-11e8-8083-ff993eacaee7.png)
![monosnap 2018-04-12 09-04-44](https://user-images.githubusercontent.com/579256/38649397-410273e0-3e31-11e8-913f-58fc852ebd81.png)

**Comment by AlexisDrogoul** [comment] 2018-04-12 00:24
This variable (`agents`) only concerns the agents of the sub-populations (micro-agents). So there are two of them for the world (the 2 people) but zero for each people (as they don't have any sub-populations).

**Comment by hqnghi88** [comment] 2018-04-12 00:31
Yes, thanks, totally clear, agents of sub-pop of current species, it is not agents of current species. Thank you

**Comment by AlexisDrogoul** [comment] 2018-04-16 06:29
Closing this issue unless someone feels it is not clear enough ?

**Closed by AlexisDrogoul** 2018-04-16 06:29 UTC
Labels: > Bug, Concerns GAML, Version 1.8 RC

**Comment by AlexisDrogoul** [comment] 2018-04-17 09:38
Well, "normally", one should always use `world.agents` or `self.agents`... The preference might break the program of course (as `self.agents` is not known when the optimisation is set), but it is better than to have a different behaviour.
