### ISSUE TITLE
Browser of cell agent always empty 

### ISSUE THREAD

**Issue by PA-PINON** [gama-platform/gama#1263] opened 2015-07-13 04:13 UTC
When i want see all attributs of cell agent by this way : Agents / Population of "name cell agent" / Browse "name cell agent", this browse is always empty, whereas for any other type of agent is ok. 

You can test this problem by : 

--> Models library / Tutorials / Predator Prey / models / Model 13.gaml for example. 

I'm pretty sure, this problem doesn't exist in Mac OS (because i had test on a platform Mac OS and it was ok)  and maybe also Linux, it's just for Windows (Windows 8.1 and Windows 10). 

Windows 8.1, GAMA 1.7 version Git

**Comment by AlexisDrogoul** [comment] 2015-12-03 19:23
Closed as it is a duplicate of issue #1237

**Closed by AlexisDrogoul** 2015-12-03 19:23 UTC
Labels: 4 - Done, > Bug, Concerns Simulation

**Comment by AlexisDrogoul** [comment] 2015-12-23 16:32
Fixed in commit 218d4a37f8911a286fb7520e810a9b64562af23d
