### ISSUE TITLE
Different rendering between live keystone and preloaded keystone

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#2928] opened 2020-02-07 00:06 UTC
**Describe the bug**
First of all this bug is almost impossible to notice on a normal screen (e.g a retina).
It  becomes very obvious and quite problematic when projecting on a big surface (1mx2m)
Also AntiAliasing is set to true (by default)

**To Reproduce**
Open any model in Opengl
Press K 
Keystone it (whetever keystone)
Observe the rendering (which is already aliased as mention in https://github.com/gama-platform/gama/issues/2174)

Save the keystone value
Rerun the model 
Observe the different rendering which is even more aliased and less sharp

**Expected behavior**
The rendering should be the same as the one obtain while keystoning

Is it possible that the live keystone is applied on a specific surface whereas the preloaded keystone is made on a different one?

**Screenshots**
It's hard to see the difference on a normal screen

Live keystone (sharper)

<img width="1204" alt="Screen Shot 2020-02-07 at 01 02 59" src="https://user-images.githubusercontent.com/3928502/73989294-a4856c80-4945-11ea-894a-0eaeef0d1b07.png">
 Preloaded Keystone 
<img width="1263" alt="Screen Shot 2020-02-07 at 01 01 37" src="https://user-images.githubusercontent.com/3928502/73989312-abac7a80-4945-11ea-8961-c300cdf29243.png">

**Desktop (please complete the following information):**
Gama 1.8 
Mac OS

**Comment by AlexisDrogoul** [comment] 2020-02-20 02:53
A question since it is complicated to reproduce : what happens if you display the keystoned scene and press 'K' again ? Does it change to a "better" rendering ? Does it remain in the "bad" state ?

**Comment by AlexisDrogoul** [comment] 2020-02-23 13:10
One more thing: the code to display the keystone helper and the keystoned scene is rigorously the same (methods `render` and `finishRenderToTexture` in KeystoneHelper.java, both called by `display(...)` in `JOGLRenderer`). So it's surprising to say the least to have a difference.

**Comment by AlexisDrogoul** [comment] 2020-02-23 18:38
I have pushed two improvements that actually eliminate (on my screen however) the difference between the two keystone modes. Not completely sure why and how, but it seems to work. So I close this issue. Test the new rendering and reopen if needed.

**Closed** 2020-02-23 18:39 UTC
Labels: 🖥 Display OpenGL, 😱 > Bug, 🙅🏻‍♂️ Affects Usability
