### ISSUE TITLE
Shape of an object : should it contains the color of the object ?

### ISSUE THREAD

**Issue by tungohuu** [gama-platform/gama#2053] opened 2016-11-25 02:34 UTC
### Steps to reproduce
1. Create a species (father) from shape file. The mother has an attribute "color<-#gray"

2. Create inheritance species (son) from the mother above. Update the attribute "color<-#red"

3. Print out the value of the attribute "write color" of the son
===== here is the code =====
model v1

global {
	file building_file <- shape_file("../includes/hanoi_polygon/hanoi_vietnam_osm_polygon.shp");
	geometry shape <- envelope(building_file);
	float step <- 1 #mn; 
	
	init {		 	
		create building from: building_file {
			shape<-shape simplification 0.7;
		}
		
		ask 1 among ( building ) {
			
			create energy_control number:1 {
			      self.color <- #red;// update color of this species			      
			      self.location <- myself.location;
			      self.shape <- myself.shape;			      
			}
			do die;			
		}		 
	}		
}

species building {
	rgb color <- #gray;		
	aspect geom {		 
		 draw shape color: color;
	}
}

species energy_control parent: building {
		
	reflex upd
	{
		write color; // this prints "gray" although I update the color when I create this species
	}

}

experiment test type: gui {		
	
	output { 
		display map type: opengl {
              	species building aspect: geom  refresh: false; 
              	species energy_control aspect: geom;               	
        }
	}	
}

### Expected behavior
the value printed out is "red"

### Actual behavior
the value printed out is "gray"

### System and version 
Gama 1.7

**Comment by dphilippon** [comment] 2016-11-25 10:51
Okay so I'll change a little bit the issue,  as the problem is more a cognitive problem. 
Try the following model :
````
global
{
	geometry shape<-square(100);
    init 
    {
        create my_species 
        {
        		shape<-square(10);
        		location<-any_point_in(world.shape);
        }
        ask one_of(my_species)
        {
        		create child_species number:1
        		{
        			color<-#blue; 
        			shape<-myself.shape;
        			location<-myself.location;
        		}
        		do die;
        }
    }
}

species my_species {
    rgb color<-#grey;
    
}
species child_species parent:my_species
{
	rgb color<-#red;
	reflex update
	{
		write self.color;
	}
}

experiment expe type: gui
{
    output {
    }
}
````

Now if you launch it, you'll see in the console that the color written is grey, whereas it should be blue. 
If you change the lines' order, by putting the initialisation of the color to blue after the initialisation of the shape in the ````create child_species```` bloc, you'll now read blue. 

So basically, a shape of an object also contains its color. So I'm wondering, is it made to do so or not ? 

I found it quite surprising and I must admit that in my head, I do think that the shape of an object doesn't contain its color. Do we consider it as normal and document it or do we change it ?

**Comment by AlexisDrogoul** [comment] 2016-12-09 04:24
Actually, this issue has nothing to do with the color. It's due to the way non-native attributes of agents are stored. `color` is not native (except for agents instances of a grid species), which means its value will be stored in the attributes of its shape. It would be the same for any other attribute: geometries come with their full set of attributes, whether they are copied, duplicated, etc. (it is more or less necessary for GIS read/write operations).

The only solution for getting rid of the set of attributes is to recreate the geometry: i.e. instead of `shape<-myself.shape;`, to use `shape<-geometry(myself.shape.points);`. Not especially convenient, but I can't think of a better way right now.

One solution could be to zero the attributes when we copy a shape from an agent to another agent. I will try to see if it is possible and doesn't break existing assumptions. In the meantime, the only solution is to use the workaround above.

**Comment by AlexisDrogoul** [comment] 2016-12-10 19:06
I have committed a fix to this issue. Please reopen if it still manifests itself.

**Closed** 2016-12-10 19:06 UTC
Labels: * Workaround, Affects Usability, Concerns GAML, OS All, Version All
