### ISSUE TITLE
Issue with some CSV files (complex formatting)

### ISSUE THREAD

**Issue by ptaillandier** [gama-platform/gama#2870] opened 2019-08-23 08:40 UTC
### Steps to reproduce
1. Open and run the attached model

### Actual behavior
error obtained:
2 occurrences in 2 agents at cycle 0: Java error: index out of bounds
in matrix mat <- matrix(data_file);
ArrayIndexOutOfBoundsException: 522
msi.gama.util.file.GamaCSVFile.createMatrixFrom(GamaCSVFile.java:438)
msi.gama.util.file.GamaCSVFile.fillBuffer(GamaCSVFile.java:350)
msi.gama.util.file.GamaFile.getContents(GamaFile.java:346)
msi.gama.util.file.GamaFile._matrixValue(GamaFile.java:422)
msi.gama.util.file.GamaFile.matrixValue(GamaFile.java:417)
msi.gama.util.file.GamaFile.matrixValue(GamaFile.java:411)
msi.gaml.types.GamaMatrixType.staticCast(GamaMatrixType.java:53)
when applying the as operator on file('/home/pataillandie/gama_workspace_2019_v/test/includes/Questionnaire.csv') and matrix
in matrix mat <- matrix(data_file);
in init  {
	matrix mat <- matrix(data_file);
	write mat ;
}

in agents Simulation 0, CSVloading0

### System and version 
Linux, Git version

[csv_file_issue.zip](https://github.com/gama-platform/gama/files/3533586/csv_file_issue.zip)

**Comment by AlexisDrogoul** [comment] 2019-08-24 04:40
Duplicate of #2830. Use `	csv_file data_file <- csv_file("../includes/Questionnaire.csv", ",", '"', true);` in your model.

**Closed by AlexisDrogoul** 2019-08-24 04:40 UTC
Labels: > Bug, Concerns Data Persistence
