### ISSUE TITLE
Wrong result with the "split_with(string ...)" operator

### ISSUE THREAD

**Issue by ptaillandier** [gama-platform/gama#3311] opened 2022-03-01 04:36 UTC
**Describe the bug**
Test the following expression: 
		write "333%444" split_with "%%";

It should returns a list composed of only one element ["333%444"]. Instead GAMA returns ['333','444']

**Desktop (please complete the following information):**
 - GAMA version: git, 1.8.2

**Comment by AlexisDrogoul** [comment] 2022-03-02 15:18
Actually no. If you look at the doc, it rightly says : _Returns a list containing the sub-strings (tokens) of the left-hand operand delimited by each of the characters of the right-hand operand_
To use the whole string as a delimiter, you have to use the second form of `split_with` with a boolean argument set to true. i.e: 
`write "333%444" split_with ("%%", true);`

**Comment by ptaillandier** [comment] 2022-03-03 02:21
Very interesting. However, for me, the default behavior should be `"333%444" split_with ("%%", true)` to be consistent with older versions of GAMA and because it seems to be a lot more natural for modelers who are not computer scientists :) .

**Comment by AlexisDrogoul** [comment] 2022-03-03 03:09
Should I mention who implemented this operator like this in 2018 ?? 🤣

(https://github.com/gama-platform/gama/commit/c9d2a09186ebc2bb9b2fb74588bd54f4c4f4d48e)

**Comment by ptaillandier** [comment] 2022-03-03 03:13
2018 .... it is very recent considering the long history of GAMA 😅

Le jeu. 3 mars 2022 à 10:09, Alexis Drogoul ***@***.***> a
écrit :

**Comment by AlexisDrogoul** [comment] 2022-03-03 03:15
Maybe. But the important thing to consider is the **who**  ^^

**Comment by AlexisDrogoul** [comment] 2022-03-03 07:42
So I let you decide whether to close it or change your implementation 😀

**Comment by AlexisDrogoul** [comment] 2022-12-18 07:31
Let's close this issue -- everything works as intended !

**Closed by AlexisDrogoul** 2022-12-18 07:31 UTC
Labels: ❌ Not an issue
