### ISSUE TITLE
Enhancement: text layer in display section more flexible

### ISSUE THREAD

**Issue by pcaillou** [gama-platform/gama#832] opened 2015-05-30 06:05 UTC
```
Describe which enhancement/addition to GAMA you would like to see:

hi, currently, the text layer drawn on display is fixed to the world coordinates. For
example, if a text is defined at the top left corner of the world and lets say I am
displaying time as text. It shows on time on the top left corner. Then when I zoom
in to see some specific area of my world, the text layer is not visible because it
is fixed coordinates. And therefore I lose track of the display on text layer (time
in my case).

so it would be nice, that the text layer displays the text at defined position irrespective
of zoom levels of the world.




```

Original issue reported on code.google.com by `b.srirama` on 2014-03-04 12:46:45

**Comment by AlexisDrogoul** [comment] 2016-01-12 05:42
The original question has not been addressed, although the problem has been solved. I close this issue as a duplicate of #1326 (absolute positioning of elements).

**Closed by AlexisDrogoul** 2016-01-12 05:42 UTC
Labels: > Enhancement, Affects Usability, Display All, Display OpenGL, Priority Medium
