### ISSUE TITLE
Co-model with user interaction models: enhance with the new place of on_user_hold and the boolean flag "paused"

### ISSUE THREAD

**Issue by dphilippon** [gama-platform/gama#1665] opened 2016-04-07 02:34 UTC
Using co-model feature on a submodel with user interaction enable the possibility to interact with the user command, as the step doesn't even pause the model to make a choice. I think it would be great to stop all the models when a user interaction needs an interaction with the user.

**Comment by AlexisDrogoul** [comment] 2016-04-07 03:28
Could you provide a minimal example ? I dont see very clearly what "the step doesnt even pause the model to make a choice" means. Which model isn't paused ? The comodel ? The micro-model ? Which model is the one trying to interaction with the user ?

**Comment by dphilippon** [comment] 2016-04-07 04:01
Example : 
This model is the one asking to the user to write a message and display it in the console. (The experiment works)
```
model user


global
{
	
	init
	{
		create user number:1;
	}
}

species user control:user_only {   	
   user_panel "Default" initial: true {
   	transition to: "Write" when: cycle mod 20=0;
   }
   user_panel "Write"
   {
      user_command "Activate"  continue: true color: #blue{
        user_input "Target" returns: message type: string<-"None";
        write message;
      }
      transition to: "Default"; 
   }
}


experiment anExp type:gui
{
	float minimum_cycle_duration<-0.1#s;
	output
	{
	}
}
```

This model is the co-model (but with only one model for the moment)
```
model comodel
import "user.gaml" as model_user

global
{
	bool activated<-true;
	init
	{
		create model_user.anExp number:1 ;
	}
	reflex update
	{
		ask first(model_user.anExp).simulation
		{
				do _step_;
		}
	}

}

experiment test type: gui
{
	float minimum_cycle_duration<-0.1#s;
}
````
Normally, we expect the co-model to do as the experiment in the micro-model, which means that the user interaction contained in the micro-model, once the panel appears, will stop the experiment until the value of the user_command is set. However, it just continues to do the step, and doesn't even allow to set the value, as it is updates every cycle. I know that the ask within the reflex in the co model forces the step to pass, but so does the step by step button. But in this case, when launching the experiment in the micro-model, even pressing the button doesn't pass to the next step. 
That's why I was hoping to "stop" all the simulations once a user_panel appears, just like for the micro model.

**Comment by AlexisDrogoul** [comment] 2016-04-08 02:56
Well.. It's going to be difficult, as the "onUserHold" property is bound to a scope, in that case the scope of the micro-model. And I would bet (havent checked) that directly calling `_step_` bypasses the check on this property. I will investigate on this.

**Comment by hqnghi88** [comment] 2016-04-15 17:38
I close this issue with a commit that make SimulationAgent check the on_user_hold in its _step_ .
The comodel is : 
model comodel

import "user.gaml" as model_user

global
{
	bool activated <- true;
	init
	{
		create A number:10000;
		create model_user.anExp number: 1;
	}

	reflex update
	{
		ask (model_user.anExp collect each.simulation)
		{
			ask user
			{
				do _step_;
			}

		}

	}

}
species A skills:[moving]{
	reflex goaway{
		do wander;
	}
}
experiment test type: gui
{
	float minimum_cycle_duration <- 0.1 # s;
	output{
		display "mydisp"{
			species A;
		}
	}
}


Please feel free to reopen it and change the things inn futher.
Cheers

**Comment by AlexisDrogoul** [comment] 2016-04-21 12:26
I reopen this issue ( @hqnghi88, no need to do it !) as the fix has introduced a problem when several simulations -- be they micro-models or not -- use a user control panel; basically, if they run in different threads, they will not stop the macro-simulation and if one of the control panels is released, it will release all the others, as they all rely on the same scheduler flag. 

So all of this pledges for 2 things:

- [ ] remove `on_user_hold` from the scheduler and make it a property of the scope instead
- [ ] add at least one attribute to the simulations (`paused` ?) so that this state can be explicitly tested in the model (or in the experiment) -- allowing to block everything or not depending on the use case.

**Comment by AlexisDrogoul** [comment] 2016-04-22 04:00
I have committed what might be a fix for this issue. Note that the comodels running micro-models with a user control architecture now need to explicitly check whether their simulations are `paused` or not before stepping them (as I have removed the check introduced by @hqnghi88 in the `_step_()` method). So, by default, a micro-model waiting for a user input should not block its macro model, unless its `paused` state is checked. This does not concern experiments with multiple simulations, are they are managed internally by the experiment, which waits until all simulations have stepped.

This has to be more carefully tested before we close this issue.

**Comment by hqnghi88** [comment] 2016-04-22 04:34
Thank you Alexis,
I've just tested with the model of @dphilippon , it works perfectly without "checking anything", so it seem that the root cause is that the scope of user panel is not passed correctly. But the paused will do its role. I will test more cases.

**Comment by AlexisDrogoul** [comment] 2016-04-22 04:40
Well, this might be a problem, no ? We have to check which scope is passed to the user panel (the scope of the experiment or the one of the simulation).

**Comment by AlexisDrogoul** [comment] 2016-04-22 04:56
I've tested and it seems to be the same scope which is put on user hold and tested. Does it mean that your micro-model simulations work in the same thread as the simulation of the comodel ? In that case, it's normal that they stop the whole simulation. But it also means that the `paused` state can never be checked ... maybe only in the experiment ?

**Comment by AlexisDrogoul** [comment] 2016-05-03 10:45
Just to clarify things: does the fix work or not ? I'm a bit lost -- if it works, please close this issue.

**Comment by hqnghi88** [comment] 2016-05-04 04:11
Yes, this issue is fixed.

**Closed by hqnghi88** 2016-05-04 04:11 UTC
Labels: > Bug, Affects Usability, Concerns Interface, Concerns Simulation, OS All, Priority Medium, Version Git
