### ISSUE TITLE
Ubuntu > 14 and Intel Drivers do not support Shared OpenGL contexts and crash GAMA

### ISSUE THREAD

**Issue by RCura** [gama-platform/gama#1505] opened 2016-01-27 13:41 UTC
I'm running the latest (master 843c0a72ddfd2c0dc3d4d1b4bf38d8d45aaf69bd) Gama.

When updating the models library and trying to run the multi-simulation model (Ant Foraging (Multi-Simulation).gaml)

I can launch the model, and all the displays are correctly created.
![capture du 2016-01-27 14 36 30](https://cloud.githubusercontent.com/assets/807703/12615004/66cf1d20-c503-11e5-9a8c-2d62cc511c49.png)

I can run the model :
![capture du 2016-01-27 14 37 21](https://cloud.githubusercontent.com/assets/807703/12615022/81dbea1c-c503-11e5-8ae0-90dc263249b6.png)

I can change the parameters, reload the model etc.

But if I try to click on one of the Simulation displays (Ants (Simulation n of ants)), the screen goes black and Gama force close with this error (inside Eclipse) : 

    intel_do_flush_locked failed: Aucun fichier ou dossier de ce type

System : ubuntu 15.04 x64 / Java 1.8

**Comment by RCura** [comment] 2016-01-27 13:49
Related to model described here : #1445

**Comment by AlexisDrogoul** [comment] 2016-01-27 16:53
Can you try to remove the `type: opengl` facet from the display statement ?

**Comment by RCura** [comment] 2016-01-27 17:11
With this fix, it works well :)

**Comment by AlexisDrogoul** [comment] 2016-01-27 17:30
Well, actually, it's not really a fix — more a (annoying) recognition that OpenGL has a serious problem on your configuration… Just to be complete: can you share your graphics card model if you have one (or are you using the Intel CPU-based graphics card ) ?

**Comment by RCura** [comment] 2016-01-27 17:51
It's CPU-based : Intel® HD Graphics 5500 (Broadwell GT2)
Using native (i.e. kernel) drivers.

I'll try to install specific opengl drivers and report here

**Comment by AlexisDrogoul** [comment] 2016-02-14 08:37
Hi,

I"ve tested the release on Ubuntu 14.04 and it works like a charm — but with a "real" graphics card, and that's probably the culprit in that case. Have you tried to install better drivers ? 

Cheers
Alexis

**Comment by RCura** [comment] 2016-02-15 21:45
I did install all I could opengl-related. My chipset is anyway supposed to work "out of the box", as my computer was purchased (Dell) as a Linux computer.

Still no way to launch this.

**Comment by AlexisDrogoul** [comment] 2016-02-24 08:57
For reference (in #1238):

"OK. I think I've found the cause of this Issue and #1505. Please have a look here: https://jogamp.org/bugzilla/show_bug.cgi?id=873

So, basically, what causes this crash is the lack of support of shared OpenGL contexts by the Intel driver on Ubuntu (13, 14, 15). Shared GL contexts were introduced in GAMA 1.7 as a way to cache common images and textures between several OpenGL displays (and also as a way to do some non-UI blocking loading of these textures). 

I will try to see (1) how to detect these configurations when launching JOGL; (2) how to disable shared contexts in this case (and rely on a single-threaded, context-bound loading mechanism)."

**Comment by AlexisDrogoul** [comment] 2016-02-26 05:27
Hi,

I have committed a possible fix for this issue. To test it, open the Git version of GAMA, go to the "Preferences…" menu, select "Experimental" and set `Enable OpenGL background loading of textures ` to false. Then run any model that relies on an OpenGL display. 

Tell me if it works ! (I will see later how to automatically detect the configurations that do not support shared contexts).

Cheers
Alexis

PS: @dphilippon had reported the same issue in #1238 — so a second test could be interesting.

**Comment by AlexisDrogoul** [comment] 2016-03-03 14:10
Any update on this one ? Have you had a chance to test it ?

**Comment by RCura** [comment] 2016-03-03 15:59
Not right now, currently on vacations, after a hard time having to go back
to 1.6.1 release to have my model working :/
Will test on monday :smile:
Le 3 mars 2016 3:10 PM, "Alexis Drogoul" <notifications@github.com> a
écrit :

**Comment by RCura** [comment] 2016-03-07 10:11
Tried with and without this parameter activated, and it works like it should.
On multi-simulation model, Gama force closes when the option isn't disabled, and it works well when disabled :)

**Comment by AlexisDrogoul** [comment] 2016-03-07 14:04
Nice to hear this. Thanks a lot for testing ! I can safely close this issue then…

**Closed by AlexisDrogoul** 2016-03-07 14:04 UTC
Labels: > Bug, Affects Stability, Concerns Interface, Display OpenGL, OS Linux, Priority High, Version Git
