### ISSUE TITLE
The generated GAMA.APP appears with a version 4.4. on the Mac

### ISSUE THREAD

**Issue by jdzucker** [gama-platform/gama#1764] opened 2016-05-17 09:10 UTC
It is nice to have a unique name for gama that does not include the version name but it would be nice to have the correct version in the finder. The property fil should be modified in accordance.

**Comment by AlexisDrogoul** [comment] 2016-05-18 18:47
Closed as a duplicate of the more general issue #1773

**Closed by AlexisDrogoul** 2016-05-18 18:47 UTC
Labels: > Enhancement, OS OSX, Priority Low
