### ISSUE TITLE
Unable to run the Eclipse version of GAMA neither the latest build

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#2055] opened 2016-11-30 17:53 UTC
### Steps to reproduce
1. After an update on my Eclipse I cannot run anymore GAMA. We I run it it gets stocks in the loading screenplash 
<img width="567" alt="screen shot 2016-11-29 at 10 57 11" src="https://cloud.githubusercontent.com/assets/3928502/20764336/c0ddb156-b6fb-11e6-9c0d-de1a9015d45c.png">

I did all the usual clean, synchronize, add required from the gama.runtime.product but still...

NB: I have the same issue with the lastest build (but noit with the latest release...)

The only error I have is the following one 
The only error I have in the source is in gama.target.platform/pom.xml

Description    Resource    Path    Location    Type
Project build error: Unknown packaging: eclipse-target-definition    pom.xml    /gama.target.platform    line 4    Maven pom Loading Problem
Description    Resource    Path    Location    Type
Project build error: Unresolveable build extension: Plugin org.eclipse.tycho:tycho-maven-plugin:0.25.0 or one of its dependencies could not be resolved: Failure to find msi.gama:msi.gama.processor:jar:1.4.0 in http://buchen.github.io/maven-repo was cached in the local repository, resolution will not be reattempted until the update interval of buchen-maven-repo has elapsed or updates are forced    pom.xml    /gama.target.platform    line 1    Maven pom Loading Problem
Description    Resource    Path    Location    Type
Project build error: Unresolveable build extension: Plugin org.eclipse.tycho:tycho-maven-plugin:0.25.0 or one of its dependencies could not be resolved: Failure to find msi.gama:msi.gama.processor:jar:1.4.0 in http://buchen.github.io/maven-repo was cached in the local repository, resolution will not be reattempted until the update interval of buchen-maven-repo has elapsed or updates are forced    pom.xml    /msi.gama.parent    line 1    Maven pom Loading Problem

Is it link with Maven, do I miss some package?

### System and version 
Mac OS 10.11.6

**Comment by agrignard** [comment] 2016-12-01 00:46
Thanks again Nghi for finding the issue...

Apprently something related to the target platform remove the old one and add a new one...
<img width="1920" alt="screen shot 2016-11-30 at 19 34 44" src="https://cloud.githubusercontent.com/assets/3928502/20777522/8d859744-b735-11e6-8ae7-b50ac3478a53.png">


The question is why this happened....???????

**Comment by hqnghi88** [comment] 2016-12-01 00:56
Actually, I have not found the reason. I debugged and it stop at this line (line 42 in msi.gama.application.Application.java)
			final int returnCode = PlatformUI.createAndRunWorkbench(display, new ApplicationWorkbenchAdvisor());
Then it display some error about "missing" and "not found" of existing classes (i.e ummisco.ui.view.xxx). So I think something has been cached, then I removed, re-add the TP in PDE.

It need an expert to say the cause.

**Comment by hqnghi88** [comment] 2016-12-01 01:03
Actually, I have not found the reason. I debugged and it stop at this line (line 42 in msi.gama.application.Application.java)
			final int returnCode = PlatformUI.createAndRunWorkbench(display, new ApplicationWorkbenchAdvisor());
Then it display some error about "missing" and "not found" of existing classes (i.e ummisco.ui.view.xxx). So I think something has been cached, then I removed, re-add the TP in PDE.

It need an expert to say the cause.

**Comment by agrignard** [comment] 2016-12-01 14:38
.... Is GAMA is angry against me or what???

I still have this problem this morning... I went to preferencs remove the current target platform and create a new target definition but same problem

**Comment by hqnghi88** [comment] 2016-12-01 14:44
Can you place a breakpoint at the line I mentioned to see if it'll pass or not?

**Comment by agrignard** [comment] 2016-12-01 14:49
.... so strange!!!!

I run it once on debug mode and now it's ok

**Comment by agrignard** [comment] 2016-12-01 14:54
I don't know what to say... sometime it works some time not... very hard to reproduce

**Comment by hqnghi88** [comment] 2016-12-01 14:59
Yes, I said that to Benoit "very hard to reproduce", It seem to have a same root cause.

**Comment by benoitgaudou** [comment] 2016-12-02 11:57
Hi all,

I have more and more often the same issue.
I do not know if it helps, but the profile can find a deadlock with the following message: 

Frozen threads found (potential deadlock)

It seems that the following threads have not changed their stack for more than 10 seconds.
These threads are possibly (but not necessarily!) in a deadlock or hung.

main <--- Frozen for at least 1m 52s
java.lang.Runtime.loadLibrary0(Class, String) Runtime.java:862
java.lang.System.loadLibrary(String) System.java:1122
org.eclipse.core.internal.filesystem.local.unix.UnixFileNatives.<clinit>() UnixFileNatives.java:39
org.eclipse.core.internal.filesystem.local.LocalFileNativesManager.<clinit>() LocalFileNativesManager.java:50
org.eclipse.core.internal.filesystem.local.LocalFile.fetchInfo(int, IProgressMonitor) LocalFile.java:155
org.eclipse.core.filesystem.provider.FileStore.fetchInfo() FileStore.java:284
org.eclipse.core.internal.localstore.FileSystemResourceManager.hasSavedDescription(IProject) FileSystemResourceManager.java:589
org.eclipse.core.internal.resources.Project.create(IProjectDescription, int, IProgressMonitor) Project.java:281
org.eclipse.core.internal.resources.Project.create(IProjectDescription, IProgressMonitor) Project.java:252
msi.gama.application.workspace.WorkspaceModelsManager$3.execute(IProgressMonitor) WorkspaceModelsManager.java:497
org.eclipse.ui.actions.WorkspaceModifyOperation$1.run(IProgressMonitor) WorkspaceModifyOperation.java:108
org.eclipse.core.internal.resources.Workspace.run(IWorkspaceRunnable, ISchedulingRule, int, IProgressMonitor) Workspace.java:2241
org.eclipse.ui.actions.WorkspaceModifyOperation.run(IProgressMonitor) WorkspaceModifyOperation.java:130
msi.gama.application.workspace.WorkspaceModelsManager.importBuiltInProjects(String, boolean, IWorkspace, Map) WorkspaceModelsManager.java:511
msi.gama.application.workspace.WorkspaceModelsManager.linkModelsToWorkspace(String, String, boolean) WorkspaceModelsManager.java:454
msi.gama.application.workspace.WorkspaceModelsManager.linkSampleModelsToWorkspace() WorkspaceModelsManager.java:416
msi.gama.application.workbench.ApplicationWorkbenchAdvisor.initialize(IWorkbenchConfigurer) ApplicationWorkbenchAdvisor.java:66
org.eclipse.ui.application.WorkbenchAdvisor.internalBasicInitialize(IWorkbenchConfigurer) WorkbenchAdvisor.java:192
org.eclipse.ui.internal.Workbench$22.runWithException() Workbench.java:1684
org.eclipse.ui.internal.StartupThreading$StartupRunnable.run() StartupThreading.java:32
org.eclipse.swt.widgets.RunnableLock.run() RunnableLock.java:35
org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(boolean) Synchronizer.java:135
org.eclipse.swt.widgets.Display.runAsyncMessages(boolean) Display.java:4024
org.eclipse.swt.widgets.Display.readAndDispatch() Display.java:3700
org.eclipse.ui.internal.Workbench.runUI() Workbench.java:2989
org.eclipse.ui.internal.Workbench.access$9(Workbench) Workbench.java:2894
org.eclipse.ui.internal.Workbench$5.run() Workbench.java:685
org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm, Runnable) Realm.java:337
org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Display, WorkbenchAdvisor) Workbench.java:606
org.eclipse.ui.PlatformUI.createAndRunWorkbench(Display, WorkbenchAdvisor) PlatformUI.java:150
msi.gama.application.Application.start(IApplicationContext) Application.java:42
org.eclipse.equinox.internal.app.EclipseAppHandle.run(Object) EclipseAppHandle.java:196
org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(Object) EclipseAppLauncher.java:134
org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(Object) EclipseAppLauncher.java:104
org.eclipse.core.runtime.adaptor.EclipseStarter.run(Object) EclipseStarter.java:380
org.eclipse.core.runtime.adaptor.EclipseStarter.run(String[], Runnable) EclipseStarter.java:235
sun.reflect.NativeMethodAccessorImpl.invoke0(Method, Object, Object[]) NativeMethodAccessorImpl.java (native)
sun.reflect.NativeMethodAccessorImpl.invoke(Object, Object[]) NativeMethodAccessorImpl.java:62
sun.reflect.DelegatingMethodAccessorImpl.invoke(Object, Object[]) DelegatingMethodAccessorImpl.java:43
java.lang.reflect.Method.invoke(Object, Object[]) Method.java:497
org.eclipse.equinox.launcher.Main.invokeFramework(String[], URL[]) Main.java:669
org.eclipse.equinox.launcher.Main.basicRun(String[]) Main.java:608
org.eclipse.equinox.launcher.Main.run(String[]) Main.java:1515
org.eclipse.equinox.launcher.Main.main(String[]) Main.java:1488

process reaper <--- Frozen for at least 2m 21s
java.lang.UNIXProcess$ProcessPipeInputStream.processExited() UNIXProcess.java:528
java.lang.UNIXProcess.lambda$initStreams$271() UNIXProcess.java:299
java.lang.UNIXProcess$$Lambda$7.run()
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor$Worker) ThreadPoolExecutor.java:1142
java.util.concurrent.ThreadPoolExecutor$Worker.run() ThreadPoolExecutor.java:617
java.lang.Thread.run() Thread.java:745

Thread-7 <--- Frozen for at least 1m 52s
java.lang.ClassLoader$NativeLibrary.load(String, boolean) ClassLoader.java (native)
java.lang.ClassLoader.loadLibrary0(Class, File) ClassLoader.java:1938
java.lang.ClassLoader.loadLibrary(Class, String, boolean) ClassLoader.java:1821
java.lang.Runtime.load0(Class, String) Runtime.java:809
java.lang.System.load(String) System.java:1086
java.lang.ClassLoader$NativeLibrary.load(String, boolean) ClassLoader.java (native)
java.lang.ClassLoader.loadLibrary0(Class, File) ClassLoader.java:1938
java.lang.ClassLoader.loadLibrary(Class, String, boolean) ClassLoader.java:1842
java.lang.Runtime.loadLibrary0(Class, String) Runtime.java:870
java.lang.System.loadLibrary(String) System.java:1122
java.awt.Toolkit$3.run() Toolkit.java:1636
java.awt.Toolkit$3.run() Toolkit.java:1634
java.security.AccessController.doPrivileged(PrivilegedAction) AccessController.java (native)
java.awt.Toolkit.loadLibraries() Toolkit.java:1633
java.awt.Toolkit.<clinit>() Toolkit.java:1668
java.awt.Dimension.<clinit>() Dimension.java:88
java.lang.Class.forName0(String, boolean, ClassLoader, Class) Class.java (native)
java.lang.Class.forName(String) Class.java:264
javax.media.jai.JAI.class$(String) JAI.java:184
javax.media.jai.JAI.<clinit>() JAI.java:312
msi.gama.ext.Activator.start(BundleContext) Activator.java:37
org.eclipse.osgi.internal.framework.BundleContextImpl$3.run() BundleContextImpl.java:771
org.eclipse.osgi.internal.framework.BundleContextImpl$3.run() BundleContextImpl.java:1
java.security.AccessController.doPrivileged(PrivilegedExceptionAction) AccessController.java (native)
org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleActivator) BundleContextImpl.java:764
org.eclipse.osgi.internal.framework.BundleContextImpl.start() BundleContextImpl.java:721
org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0() EquinoxBundle.java:941
org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker() EquinoxBundle.java:318
org.eclipse.osgi.container.Module.doStart(Module$StartOptions[]) Module.java:571
org.eclipse.osgi.container.Module.start(Module$StartOptions[]) Module.java:439
org.eclipse.osgi.framework.util.SecureAction.start(Module, Module$StartOptions[]) SecureAction.java:454
org.eclipse.osgi.internal.hooks.EclipseLazyStarter.postFindLocalClass(String, Class, ClasspathManager) EclipseLazyStarter.java:107
org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClass(String) ClasspathManager.java:531
org.eclipse.osgi.internal.loader.ModuleClassLoader.findLocalClass(String) ModuleClassLoader.java:324
org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(String) BundleLoader.java:327
org.eclipse.osgi.internal.loader.sources.SingleSourcePackage.loadClass(String) SingleSourcePackage.java:36
org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(String, boolean) BundleLoader.java:398
org.eclipse.osgi.internal.loader.BundleLoader.findClass(String, boolean) BundleLoader.java:352
org.eclipse.osgi.internal.loader.BundleLoader.findClass(String) BundleLoader.java:344
org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(String, boolean) ModuleClassLoader.java:160
java.lang.ClassLoader.loadClass(String) ClassLoader.java:357
msi.gaml.compilation.kernel.GamaBundleLoader.<clinit>() GamaBundleLoader.java:58
msi.gama.common.Activator.lambda$0() Activator.java:26
msi.gama.common.Activator$$Lambda$11.run()
java.lang.Thread.run() Thread.java:745

**Comment by AlexisDrogoul** [comment] 2016-12-03 04:39
The trace posted by @benoitgaudou seems to indicate that there is a race between two processes (maybe two class loaders ?) to load native libraries (first and third, the second doesn't count). However, this alone cannot explain the freeze, unless, for instance, loading a description from a project implies the availability of JAI / AWT Toolkit native libraries, which is dubious. 

I never experienced this freeze myself, but I have observed it on other computers (usually slower than mine) since we implemented, with @romainreuillon, the Activator on msi.gama.ext to load native libraries of JAI early. However, this early loading is only required for headless operations, so there is a chance it competes with other processes when running the GUI version of GAMA. I will try to see if it can be delayed in that case.

**Comment by AlexisDrogoul** [comment] 2016-12-04 21:07
Can you all tell me with which version of Eclipse / JDK you have experienced the error ?

**Comment by hqnghi88** [comment] 2016-12-04 21:50
Oxygen / 1.8 b 102

HUYNH Quang-Nghi
[Vietnam] +84909128322
--
GAMA: http://gama-platform.org/

**Comment by agrignard** [comment] 2016-12-05 01:52
Version: Mars.2 Release (4.5.2) / jdk 1.8.0_91

**Comment by agrignard** [comment] 2016-12-07 19:07
I don't know if it can help or not, however sometime I get this problem:

<img width="1920" alt="screen shot 2016-12-07 at 14 06 51" src="https://cloud.githubusercontent.com/assets/3928502/20982435/84f7a1ca-bc86-11e6-8888-909e7b985101.png">

**Comment by AlexisDrogoul** [comment] 2016-12-08 04:54
Does the bug still happen with the new commit ?

**Comment by agrignard** [comment] 2016-12-08 14:41
It looks like it is solved. I wait a bit before to close it as it was very random

**Comment by sriramab** [comment] 2016-12-08 14:53
Yes this happens to me also, at random. A restart resolves the issues. Or changing/running a different model also sometimes resolves it.

**Comment by agrignard** [comment] 2016-12-13 16:36
It looks much more better now no? I mean I don't have anymore the problem? Should we close it?

**Comment by AlexisDrogoul** [comment] 2016-12-14 01:07
I close it, as it should be solved, effectively. Reopen if it persists.

**Closed by AlexisDrogoul** 2016-12-14 01:07 UTC
Labels: > Bug
