### ISSUE TITLE
draw sequence - geometry and string. 

### ISSUE THREAD

**Issue by sriramab** [gama-platform/gama#1888] opened 2016-06-20 13:29 UTC
### Steps to reproduce
1. in any model where you are drawing a string on display, sometimes the string is not visible because of other possible drawn objects in display. 
2. so I tried to draw a rectangle behind the string(). 
3. However, on doing so, the display got messed up with the sequence of drawing. I attach two images: one showing string without rectangle (hardly visible); then second image showing with a rectangle, and the display got even worse. 

Image 1
![textbackground](https://cloud.githubusercontent.com/assets/12668606/16195854/c12e283c-36fb-11e6-8281-a0a256ee0477.png)

Image 2
![order](https://cloud.githubusercontent.com/assets/12668606/16195863/c68d5546-36fb-11e6-8aa7-242a2fc9fbce.png)
1. please also see this discussion. https://groups.google.com/forum/#!topic/gama-platform/szOO1uZiNP8
### Expected behaviour

rectangle to be behind the string as I have draw rectangle statement before the  draw string statement. 
### Actual behaviour

strange to comprehend, please see attachments
### System and version

Mac Mavericks, non-GIT version, Java 1.8

**Comment by AlexisDrogoul** [comment] 2016-06-20 17:57
And what do you obtain when you draw your strings at some altitude (i.e. location + {0,0,0.1}) ?

**Comment by sriramab** [comment] 2016-06-20 19:27
Doing  `location +  {0,0,5}` has following results

For OpenGL everything is messed up: 1) the text is half shown half hidden because of the box, and appears differently at different zoom levels, 2) the box is translucent. that is, I can see the buffered lines beneath the rectangle, and not the whole buffer but only the boundaries of buffer. 

here a screenshot

![buffer](https://cloud.githubusercontent.com/assets/12668606/16207497/b0c03602-372d-11e6-8619-2fac28f4d9d6.png)

**Comment by AlexisDrogoul** [comment] 2016-06-21 14:39
I have posted some fresh code about the JOGL rendering. Does it change anything ? 

By the way, another solution to your problem would be to use two layers with the same species (the roads) and different aspects (one displaying the geometry, the other one the strings).

**Comment by sriramab** [comment] 2016-06-21 19:54
I do not see a big change, the underlying buffers are still visible through the rectangle above. Only case that works is java2D with draw rectangle before string. In java2D, having a different aspects does not help. When using different aspects, the rectangle becomes translucent and objects beneath can be seen through even in java2D

**Comment by sriramab** [comment] 2016-06-21 19:57
I feel this can really help in labelling many objects (in dense and coloured displays) with strings and a having their own background (rectangle behind) it to keep it clean and visible. Unless others also are interested, may be you can lower the priority of the issue? Thanks

**Comment by AlexisDrogoul** [comment] 2016-06-22 05:25
I dont really get it. I've tried different solutions evoked here (adding a z value to the individual draw, or a z value to the layer position, etc.) and all work fine. I can always draw a rectangle behind a string and I dont obtain this "transparency" thing you are mentioning.

**Comment by AlexisDrogoul** [comment] 2016-06-22 05:32
One thing you might try, by the way, to have "labels", is to use the facet `perspective: false` when drawing your text. You are limited in terms of fonts, but the text should normally be made visible.

**Comment by sriramab** [comment] 2016-06-22 05:36
Yes, I am already doing it

**Comment by AlexisDrogoul** [comment] 2017-01-23 11:44
Should be (more or less) fixed with the new commit 2553eb21926cfc83603888c96ce2c602b088f3c6

**Comment by AlexisDrogoul** [comment] 2017-02-21 02:58
Can you check if the recent commits have fixed the various issues depicted here ?

**Comment by AlexisDrogoul** [comment] 2017-02-28 19:31
I can't reproduce the issue anymore. Closing until further reopening :)

**Closed by AlexisDrogoul** 2017-02-28 19:31 UTC
Labels: Concerns GAML, Display OpenGL, OS OSX
