### ISSUE TITLE
Agent inspector changing automatically when an agent is casted in an other species

### ISSUE THREAD

**Issue by mazarsju** [gama-platform/gama#2000] opened 2016-09-21 10:19 UTC
I think this would be a good enhancement to follow better an agent, in particular when we are using multi-level species.

**Comment by AlexisDrogoul** [comment] 2017-03-27 17:17
Hi,

This would probably be a good thing -- but the problem is that the original agent is normally dead... We hit then some logic problem: shall we report it as dead or report it as reborn in another species ?
Beside, it would be very costly to track such modifications (i.e. the may multilevel works would not allow an easy identification of "transformed" agents).

I then close this request for now on. Reopen if you feel it is really missing.

Alexis

**Closed by AlexisDrogoul** 2017-03-27 17:17 UTC
Labels: > Enhancement, Concerns GAML
