### ISSUE TITLE
Reproductibility mode

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#2936] opened 2020-02-15 06:59 UTC
**Is your request related to a problem? Please describe.**
GAMA contains now many optimizations (with associated preferences) to increase speed of simulation and workaround to avoid some errors (when interacting with the display for example).
The default preferences are defined in order to improve usability of the platform for random users. 
But these preferences do not assure reproductibility, see issue #2930).

**Describe the solution you'd like**
I would be in favor of keeping the preferences values that maximize the usability of GAMA.
And I would be in favor of providing the possibility to modelers to define (in the experiment) that they want this experiment should be totally reproductible. This could be achieved by:
- defining a new preference (that could have an impact on one or many preferences values)
- defining a facet in experiment ?

**Comment by AlexisDrogoul** [comment] 2020-02-17 06:39
I would actually be more in favour of documenting what you write rather than proposing it as an option (either in preferences or in the experiments), because, in that case, we will have to deal with conflicting aspects in the code itself for which we cannot decide on behalf of the user (if you write `reproducible: true` and nevertheless create a display with an event layer, what do you disable ? Reproducibility or Interaction ? -- or if some of your species specify parallel: true, should we disable this ? Or rather disable the reproducibility ?). 

Could be a nice question in a FAQ ("How do I make sure that my experiment is reproducible ?").

**Comment by AlexisDrogoul** [comment] 2020-02-17 08:50
Closing this issue for the moment (it is linked from https://github.com/gama-platform/gama-platform.github.io/issues/77).

**Closed by AlexisDrogoul** 2020-02-17 08:50 UTC
Labels: Concerns Simulations, 🤗 > Enhancement
