### ISSUE TITLE
After the simulation is killed, experiment cycle is not correctly reported in the status bar

### ISSUE THREAD

**Issue by lesquoyb** [gama-platform/gama#273] opened 2024-07-31 04:45 UTC
**Describe the bug**
I noticed n some models that are not resource intensive, the cycle written in the status bar is not consistent with the cycle the model should have written nor with the actual cycle returned by writing `cycle` in the interactive console, for example here with a model that should have stopped at cycle 100, I have 3 different values for cycle:
![image](https://github.com/user-attachments/assets/8bbeb2ee-403f-45ed-be4b-48c8ed88fd4a)

**To Reproduce**
1. run this model:
```
model cycles

global {
	
	reflex y {
		write "hello";
	}
	
	reflex end when:cycle = 100 {
		do die;
	}
}

experiment a;
```
2. See error

**Expected behavior**
The cycle in the status bar, in the foldable menu of the status bar and in the interactive console are the same.

**Comment by AlexisDrogoul** [comment] 2024-09-02 01:30
The bug is not where you think it is. What we see here is a behavior (side effect) due to the existence of `cycle` in both `simulation` and `experiment`. You can try by replacing `do die;` by `do pause;` and you'll see the UI stop at a correct number, and you'll be interacting with the correct agent (i.e. the simulation) in the interactive console. 

To summarize: when you kill the simulation, only the experiment remains, and it has nothing else to do than running at full speed *indefinitely*, hence the high numbers reported (because the experiment is the only top-level agent remaining). 

The trick is that it continues running, but *we can't see it*. For an unknown reason, the update of the status bar is not done. But if you open and close the menu (or type `cycle` several times), you will see the numbers changing. 

So the issue is more on the refresh of the UI (which is blocked for some reason) than on the actual cycles within the simulation. I will update the title.

**Comment by AlexisDrogoul** [comment] 2024-09-02 02:47
Should be fixed by https://github.com/gama-platform/gama/commit/7a4fcee3a3dde23835b29fba8db2d774060c5521. Please test.

**Closed** 2024-09-13 05:00 UTC
Labels: 😱 Bug, 👍 Fix to be tested, About Runtime & Simulations
