### ISSUE TITLE
Current master doesn't compile

### ISSUE THREAD

**Issue by RCura** [gama-platform/gama#1548] opened 2016-02-15 21:54 UTC
I spent the day trying to compile/launch the current master branch.

I did this on my Ubuntu, using a fresh eclipse workspace, an updated Xtext (2.9.1.v20151218),a fresh gama git clone, still lots of errors and can't be launched.

I just tried to launch on my Windows computer now : 
Fresh setup of Eclipse Mars (still had Luna on my computer), fresh re-clone of the git repo, fresh Xtext : still can't be launched.

Here are the errors on Windows (didn't keep the Ubuntu error log) : 

![erreurs1](https://cloud.githubusercontent.com/assets/807703/13061160/60b2b2f2-d436-11e5-9139-9177eeef09b5.png)

And the error log : 

    !ENTRY org.eclipse.osgi 4 0 2016-02-15 22:50:05.810
    !MESSAGE Application error
    !STACK 1
    java.lang.Error: Unresolved compilation problems: 
        msi.gama.networks cannot be resolved to a type
        msi.gama.networks cannot be resolved to a type
        DrawStatement cannot be resolved to a type
        DrawStatement cannot be resolved to a type
        GraphstreamOutput cannot be resolved to a type
        GraphstreamOutput cannot be resolved to a type

        at gaml.additions.GamlAdditions.initializeSymbols(GamlAdditions.java:94)
        at gaml.additions.GamlAdditions.initialize(GamlAdditions.java:50)
        at msi.gaml.compilation.GamaBundleLoader.preBuild(GamaBundleLoader.java:174)
        at msi.gaml.compilation.GamaBundleLoader.preBuildContributions(GamaBundleLoader.java:71)
        at msi.gama.gui.swt.ApplicationWorkbenchAdvisor.initialize(ApplicationWorkbenchAdvisor.java:58)
        at org.eclipse.ui.application.WorkbenchAdvisor.internalBasicInitialize(WorkbenchAdvisor.java:192)
        at org.eclipse.ui.internal.Workbench$22.runWithException(Workbench.java:1644)
        at org.eclipse.ui.internal.StartupThreading$StartupRunnable.run(StartupThreading.java:32)
        at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
        at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:135)
        at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4155)
        at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3772)
        at org.eclipse.ui.internal.Workbench.runUI(Workbench.java:2949)
        at org.eclipse.ui.internal.Workbench.access$8(Workbench.java:2854)
        at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:651)
        at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
        at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:598)
        at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
        at msi.gama.application.Application.start(Application.java:124)
        at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:669)
        at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608)
        at org.eclipse.equinox.launcher.Main.run(Main.java:1515)
        at org.eclipse.equinox.launcher.Main.main(Main.java:1488)

    !ENTRY org.eclipse.core.jobs 2 2 Job found still running after platform shutdown.  Jobs should be canceled by the plugin that scheduled them during shutdown: org.eclipse.ui.internal.ide.IDEWorkbenchActivityHelper$4
    2016-02-15 22:50:07.037
    !MESSAGE Job found still running after platform shutdown.  Jobs should be canceled by the plugin that scheduled them during shutdown: org.eclipse.ui.internal.ide.IDEWorkbenchActivityHelper$4
    An error has occurred. See the log file

From a user point of view (considering the not-that-fast release cycle, it's hard to rely on releases), this is really a trouble not to be able to run a model.
I really hope the oncoming maven integration will help ensuring that the master branch doesn't get broken when committing.

**Comment by AlexisDrogoul** [comment] 2016-02-15 23:53
The fact is that it is not broken. As far as I know, it works out of the box for most people. 

I can just **guess** what is happening, and it has nothing to do with the build process, or Maven, but with the way Git is working — and maybe I'm wrong, but you will tell me.

After looking more closely, and using the log you provide, I'd say that, for a reason linked with the way Git is working, some generated `GamlAdditions.java` files and their directory (`gaml`), which are normally ignored by Git (they appear in '.gitignore'), have been committed in the repository (maybe they've been committed **before** the ignore rule was imposed) and are then part of the clone (they should not, once again, unless .gitignore is not working in that direction). These files  are supposed to be recreated dynamically but since they are not considered as derived — as they are part of the repository — Eclipse just can't erase them and they become completely outdated with respect to the actual state of the code.

For instance, GraphstreamOutput has been phased out at least one month ago. DrawStatement has been moved to another package one or two weeks ago. So how come these classes could still be present in your generated `GamlAdditions.java` files ? 

So, can you tell me: 

1) The timestamp of the gaml/GamlAdditions.java you have in msi.gama.core and irit.gaml.extensions.database ?
2) If you delete the gaml folders in these two projects, as well as the extend-gen folder in msi.gama.lang.gaml, do you have the same errors ?

After that, and if my hypothesis is true, we'll see how to clean the repository from these phantom files.

**Comment by RCura** [comment] 2016-02-16 00:54
Last modification date :
/msi.gama.core/gaml/gaml/additions : 1 novembre 2015 17:01:29
/irit.gaml.extensions.database/gaml/gaml/additions : 1 novembre 2015 17:01:43

I did delete those 2 gaml folders, and I can now launch Gama master.
I didn't delete the msi.gama.lang.gaml.xtend-gen folder as it worked without, and not sure it's the one I should delete (shouldn't I delete the one in src ?, cf. screenshot )
 
![msigaml](https://cloud.githubusercontent.com/assets/807703/13064086/ca292608-d44f-11e5-9ed1-cf384125a5ee.png)

Anyway, after deleting those 2 folders (and gama now works, yay !), here's the git diff, if that can help spot what's not working with the git repo :

    diff --git a/irit.gaml.extensions.database/.classpath b/irit.gaml.extensions.database/.classpath
    index 03fd0c1..85793b2 100644
    --- a/irit.gaml.extensions.database/.classpath
    +++ b/irit.gaml.extensions.database/.classpath
    @@ -3,6 +3,10 @@
         <classpathentry kind="con" path="org.eclipse.jdt.launching.JRE_CONTAINER"/>
         <classpathentry kind="con" path="org.eclipse.pde.core.requiredPlugins"/>
         <classpathentry excluding="irit/gaml/extensions/database/skills/XmlaTest.java|irit/gaml/extensions/database/skills/MondrianApp.java|irit/gaml/extensions/database/skills/MondrianXmlaApp.java|irit/gaml/extensions/database/skills/MyAPP.java|irit/gaml/extensions/database/skills/MDXApp.java|irit/gaml/extensions/database/skills/QueryLab.java" kind="src" path="src"/>
    -    <classpathentry kind="src" path="gaml"/>
    +    <classpathentry kind="src" path="gaml">
    +        <attributes>
    +            <attribute name="optional" value="true"/>
    +        </attributes>
    +    </classpathentry>
         <classpathentry kind="output" path="bin"/>
     </classpath>
    diff --git a/msi.gama.application/gama1.7.Eclipse3_8_2.product b/msi.gama.application/gama1.7.Eclipse3_8_2.product
    index 38564d8..f45e51f 100644
    --- a/msi.gama.application/gama1.7.Eclipse3_8_2.product
    +++ b/msi.gama.application/gama1.7.Eclipse3_8_2.product
    @@ -269,6 +269,10 @@ openFile
           <feature id="org.eclipse.ecf.filetransfer.ssl.feature"/>
           <feature id="org.eclipse.e4.rcp"/>
           <feature id="org.eclipse.rcp"/>
    +      <feature id="ummisco.gama.feature.models"/>
    +      <feature id="ummisco.gama.feature.dependencies"/>
    +      <feature id="ummisco.gama.feature.opengl.jogl2"/>
    +      <feature id="ummisco.gama.feature.core"/>
        </features>
     
        <configurations>
    diff --git a/msi.gama.core/.classpath b/msi.gama.core/.classpath
    index 0a250ad..811f7d4 100644
    --- a/msi.gama.core/.classpath
    +++ b/msi.gama.core/.classpath
    @@ -3,7 +3,11 @@
         <classpathentry kind="con" path="org.eclipse.jdt.launching.JRE_CONTAINER"/>
         <classpathentry kind="con" path="org.eclipse.pde.core.requiredPlugins"/>
         <classpathentry kind="src" path="src"/>
    -    <classpathentry kind="src" path="gaml"/>
         <classpathentry exported="true" kind="lib" path="schema" sourcepath="schema"/>
    +    <classpathentry kind="src" path="gaml">
    +        <attributes>
    +            <attribute name="optional" value="true"/>
    +        </attributes>
    +    </classpathentry>
         <classpathentry kind="output" path="bin"/>
     </classpath>

**Comment by AlexisDrogoul** [comment] 2016-02-17 10:25
All right. I'm happy it has worked. So we have to deal with:

1) Three generated (in Eclipse language, derived) folders that should not be present in the repository. I suspect there are others, too (which simply do not generate errors as they have not been changed in a while!)
2) Three correct .gitignore files that explicitly exclude them (so that they are not committed by people)
3) An incorrect behavior of GitHub which, despite the .gitignore file, adds them to the clones of the repo (probably because they have been committed **before** the .gitignore file was created).

Does someone ( @gama-platform/committers / @gama-platform/core ) know how to definitely get rid of those phantom folders in the repository ? Thanks in advance for any tip …

**Comment by RCura** [comment] 2016-02-17 10:32
I've just been able to launch gama on my Ubuntu : it was the same issue, but in a lot more of "folders". Just deleted all the gaml folders (together with the xtend-gen), and it runs like a charm.

**Comment by mazarsju** [comment] 2016-02-19 04:51
I removed the folder xtend-gen for good.

I cannot reproduce your error... I just did a clone of the repo un my folder, then open a new eclipse workspace, then "add existing local git repository" from eclipse, and all works perfectly without any error. Can you explain the different steps you have done to have those weird gaml files ?

**Comment by RCura** [comment] 2016-02-19 13:48
Just did a git pull to fetch modifications, and the buggy gaml.additions are back :/
Which means that those files aren't deleted/replaced when pulling modifications, even with a "Project -> Clean... -> Clean all projects".

Any idea how to automatically remove those files/folders when pulling gama ? I tried the usual ways (git reset --hard $HEAD, git reset --hard origin/master, git clean -f -d etc.), but none of those commands properly delete the folders.

**Comment by AlexisDrogoul** [comment] 2016-02-19 17:21
Hi,

It's puzzling. Have you tried completely deleting all the GAMA projects or cloning in a new local repository? So as to be sure that you dont have some files sticking around in your local repo ? I was with @mazarsju  when he tested a fresh cloning and, sure enough, no `gaml` folders were present...

**Comment by mazarsju** [comment] 2016-02-20 02:34
Hi,

Regarding your git commands, the `reset` should not remove the gaml folders, since they are **not** in the git repo. However, a `clean` should erase then. Have you tried with the option `-fx` to remove all **untracked** files ?

Now you told so, it is true that I also have to do a `clean -fx -d` after some pulls, which is not very friendly... I think that since the gaml files are already created, when you do a pull, those files are not created again. I'm gonna investigate...

**Comment by mazarsju** [comment] 2016-02-20 02:48
My insight was wrong : the gamlAdditions files are deleted and built again after a "project/Clean"... It is not the case for you ?

**Comment by mazarsju** [comment] 2016-04-05 05:13
Maybe this one can be close by now, no ? Feel free to reopen it if needed.

**Closed by mazarsju** 2016-04-05 05:13 UTC
Labels: * Workaround, > Bug, Affects Maintainability, Affects Usability, Concerns Development, OS All, Priority Critical, Version Git
