### ISSUE TITLE
10Gb of RAM when using shader & keystone

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#2049] opened 2016-11-16 00:32 UTC
### Steps to reproduce
1. I forgot to close my GAMA for a while and I start to notice strange behavior on my computer...

2. Indeed the memory consumption was a bit crazy (10gb)
<img width="625" alt="screen shot 2016-11-15 at 19 26 10" src="https://cloud.githubusercontent.com/assets/3928502/20329988/a477f6ae-ab69-11e6-8f87-1c767ae98c06.png">

### Expected behavior
It never happened before, we have a theoretical limitation right? 

I think it comes form the usage of the shader, as the keystone is only available with the shader if we want to have demo running for a long time this will be problematic if the memory goes so high.

### System and version 
Current Version

**Comment by AlexisDrogoul** [comment] 2016-12-15 11:50
I've given up trying to understand the memory leak present in that case. To have some more precise measure, could you:

1) Install YourKit and run Gama, from Eclipse, using it.
2) Enable memory profiling if necessary (otherwise just use CPU profiling, it will give basic information on memory)
3) Let your program run overnight
4) Do a garbage collect in GAMA (small trash) and capture a snapshot, after that, in YourKit.
5) Inspect the memory and try to determine which objects are in abnormal number (or share the snapshot somewhere so that I can have a look at it).

**Comment by AlexisDrogoul** [comment] 2017-01-16 10:58
No news from the YourKit experiment ? I have conducted myself small experiments and the level of object creation in the shaders is incredibly high (4 to 5 times more objects than the fixed pipeline). It may be the reason for this behaviour. But I would need more precise numbers from real experiments.

**Comment by agrignard** [comment] 2017-01-17 00:42
Nope no news form the YourKit experiment because I don't have a working license.

Do we have a dedicated licence key for Gama dev? I remember we used to have one.

**Comment by agrignard** [comment] 2017-02-09 22:36
Here is my profiler results. 

So it seems to spend a lot of time in the AbstractTransformer also there is this strange behavior of periodic (t=20s) increase and decrease of the cpu usage and heap space. 

<img width="1617" alt="screen shot 2017-02-09 at 17 29 36" src="https://cloud.githubusercontent.com/assets/3928502/22805866/85e963b8-eeed-11e6-81f0-800a63b1f00c.png">
<img width="1835" alt="screen shot 2017-02-09 at 17 30 04" src="https://cloud.githubusercontent.com/assets/3928502/22805865/85e6b122-eeed-11e6-9937-105054e4c2da.png">

the memory goes crazy also ;-) 
<img width="788" alt="screen shot 2017-02-09 at 17 35 42" src="https://cloud.githubusercontent.com/assets/3928502/22806058/3d81c358-eeee-11e6-8dd5-7a7a59c1db07.png">

**Comment by AlexisDrogoul** [comment] 2017-02-20 19:17
The behaviour depicted above is caused by the creation and garbage of temporary objects. A lot are created in the shaders architecture (most of them for no real reason, as they simply duplicate existing ones). Regarding the increase of memory, I have identified it: post-processing shaders were created and stored in a list which was never garbaged. Keystone on the new shaders architecture is however broken right now (I have still to find sometime to debug it).

**Comment by AlexisDrogoul** [comment] 2017-02-28 19:07
Closing this issue while cleansing the backlog. Please reopen if still needed. The shaders architecture is not maintained for the moment, please use the fixed-pipeline (i.e. normal one) to keystone the screen.

**Closed by AlexisDrogoul** 2017-02-28 19:07 UTC
Labels: > Enhancement, Display OpenGL with Shaders
