### ISSUE TITLE
Weird behaviour for "Accumulate" function

### ISSUE THREAD

**Issue by mazarsju** [gama-platform/gama#1290] opened 2015-11-04 04:14 UTC
Ex : The 2 models in Toy Models / Infection don't work ("cannot evaluate is_infected as the target agent is null"). The loop ```loop hst over: ((myPlace.neighbours + myPlace) accumulate (Host overlapping each))``` returns nil values...

**Comment by ptaillandier** [comment] 2015-11-26 14:15
I tested the Infections models and they seem to work well (the line with the accumulate operator works normally). Do you still have the same issue?

**Comment by mazarsju** [comment] 2015-11-27 04:53
I still have the same issue

**Comment by AlexisDrogoul** [comment] 2015-11-27 05:05
No problem neither. The 2 models run perfectly. Things to try in that case: relaunch GAMA after a clean of all projects in Eclipse; change workspace. Otherwise, I dont really see why this precise operator would fail...

**Comment by mazarsju** [comment] 2015-11-27 07:02
It seems it doesn't work on Windows environment

**Comment by hqnghi88** [comment] 2015-11-27 07:06
Hi,
It doesn't work with my windows 10 pc with follow eclipse console errors:

!ENTRY org.eclipse.ui 4 4 2015-11-27 14:05:29.982
!MESSAGE GamaRuntimeException Cannot evaluate is_infected as the target agent is null

!ENTRY org.eclipse.ui 4 4 2015-11-27 14:05:29.985
!MESSAGE GamaRuntimeException Cannot evaluate is_infected as the target agent is null
!STACK 0
Cannot evaluate is_infected as the target agent is null
	at msi.gama.runtime.exceptions.GamaRuntimeException.warning(GamaRuntimeException.java:79)
	at msi.gama.runtime.exceptions.GamaRuntimeException.warning(GamaRuntimeException.java:92)
	at msi.gaml.operators.System.opGetValue(System.java:71)
	at gaml.additions.GamlAdditions$543.run(GamlAdditions.java:592)
	at msi.gaml.expressions.BinaryOperator.value(BinaryOperator.java:76)
	at msi.gaml.statements.IfStatement.privateExecuteIn(IfStatement.java:127)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:42)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:43)
	at msi.gaml.statements.AbstractStatementSequence.privateExecuteIn(AbstractStatementSequence.java:55)
	at msi.gaml.statements.LoopStatement.loopBody(LoopStatement.java:144)
	at msi.gaml.statements.LoopStatement$Over.runIn(LoopStatement.java:206)
	at msi.gaml.statements.LoopStatement.privateExecuteIn(LoopStatement.java:136)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:42)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:43)
	at msi.gaml.statements.AbstractStatementSequence.privateExecuteIn(AbstractStatementSequence.java:55)
	at msi.gaml.statements.IfStatement.privateExecuteIn(IfStatement.java:127)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:42)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:43)
	at msi.gaml.statements.AbstractStatementSequence.privateExecuteIn(AbstractStatementSequence.java:55)
	at msi.gaml.architecture.reflex.ReflexStatement.privateExecuteIn(ReflexStatement.java:57)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:42)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:43)
	at msi.gaml.architecture.reflex.ReflexArchitecture.executeReflexes(ReflexArchitecture.java:73)
	at msi.gaml.architecture.reflex.ReflexArchitecture.executeOn(ReflexArchitecture.java:64)
	at msi.gama.runtime.AbstractScope.execute(AbstractScope.java:408)
	at msi.gama.metamodel.agent.GamlAgent._step_(GamlAgent.java:189)
	at msi.gama.metamodel.agent.GamlAgent.step(GamlAgent.java:159)
	at msi.gama.runtime.AbstractScope.step(AbstractScope.java:487)
	at msi.gama.metamodel.population.GamaPopulation.step(GamaPopulation.java:144)
	at msi.gama.runtime.AbstractScope.step(AbstractScope.java:487)
	at msi.gama.metamodel.agent.GamlAgent.stepSubPopulations(GamlAgent.java:201)
	at msi.gama.metamodel.agent.GamlAgent._step_(GamlAgent.java:191)
	at msi.gama.kernel.simulation.SimulationAgent._step_(SimulationAgent.java:169)
	at msi.gama.metamodel.agent.GamlAgent.step(GamlAgent.java:159)
	at msi.gama.runtime.AbstractScope.step(AbstractScope.java:487)
	at msi.gama.metamodel.population.GamaPopulation.step(GamaPopulation.java:144)
	at msi.gama.runtime.AbstractScope.step(AbstractScope.java:487)
	at msi.gama.kernel.experiment.AgentScheduler.step(AgentScheduler.java:95)
	at msi.gama.runtime.AbstractScope.step(AbstractScope.java:487)
	at msi.gama.runtime.FrontEndScheduler.step(FrontEndScheduler.java:86)
	at msi.gama.runtime.FrontEndScheduler.run(FrontEndScheduler.java:125)
	at java.lang.Thread.run(Thread.java:745)
ExpandItem created for name 1 occurence in Host0 at cycle 0ÿþCannot evaluate is_infected as the target agent is null
ExpandItem created for name 1 occurence in Host0 at cycle 0ÿþCannot evaluate is_infected as the target agent is null
ExpandItem created for name 1 occurence in Host0 at cycle 0ÿþCannot evaluate is_infected as the target agent is null
ExpandItem created for name 1 occurence in Host0 at cycle 0ÿþCannot evaluate is_infected as the target agent is null
ExpandItem created for name 1 occurence in Host0 at cycle 0ÿþCannot evaluate is_infected as the target agent is null
ExpandItem created for name 2 occurences in 2 agents at cycle 0ÿþCannot evaluate is_infected as the target agent is null
ExpandItem created for name 2 occurences in 2 agents at cycle 0ÿþCannot evaluate is_infected as the target agent is null
ExpandItem created for name 2 occurences in 2 agents at cycle 0ÿþCannot evaluate is_infected as the target agent is null
ExpandItem created for name 2 occurences in 2 agents at cycle 0ÿþCannot evaluate is_infected as the target agent is null
ExpandItem created for name 2 occurences in 2 agents at cycle 0ÿþCannot evaluate is_infected as the target agent is null
Cannot evaluate is_infected as the target agent is null
	at msi.gama.runtime.exceptions.GamaRuntimeException.warning(GamaRuntimeException.java:79)
	at msi.gama.runtime.exceptions.GamaRuntimeException.warning(GamaRuntimeException.java:92)
	at msi.gaml.operators.System.opGetValue(System.java:71)
	at gaml.additions.GamlAdditions$543.run(GamlAdditions.java:592)
	at msi.gaml.expressions.BinaryOperator.value(BinaryOperator.java:76)
	at msi.gaml.statements.IfStatement.privateExecuteIn(IfStatement.java:127)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:42)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:43)
	at msi.gaml.statements.AbstractStatementSequence.privateExecuteIn(AbstractStatementSequence.java:55)
	at msi.gaml.statements.LoopStatement.loopBody(LoopStatement.java:144)
	at msi.gaml.statements.LoopStatement$Over.runIn(LoopStatement.java:206)
	at msi.gaml.statements.LoopStatement.privateExecuteIn(LoopStatement.java:136)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:42)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:43)
	at msi.gaml.statements.AbstractStatementSequence.privateExecuteIn(AbstractStatementSequence.java:55)
	at msi.gaml.statements.IfStatement.privateExecuteIn(IfStatement.java:127)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:42)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:43)
	at msi.gaml.statements.AbstractStatementSequence.privateExecuteIn(AbstractStatementSequence.java:55)
	at msi.gaml.architecture.reflex.ReflexStatement.privateExecuteIn(ReflexStatement.java:57)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:42)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:43)
	at msi.gaml.architecture.reflex.ReflexArchitecture.executeReflexes(ReflexArchitecture.java:73)
	at msi.gaml.architecture.reflex.ReflexArchitecture.executeOn(ReflexArchitecture.java:64)
	at msi.gama.runtime.AbstractScope.execute(AbstractScope.java:408)
	at msi.gama.metamodel.agent.GamlAgent._step_(GamlAgent.java:189)
	at msi.gama.metamodel.agent.GamlAgent.step(GamlAgent.java:159)
	at msi.gama.runtime.AbstractScope.step(AbstractScope.java:487)
	at msi.gama.metamodel.population.GamaPopulation.step(GamaPopulation.java:144)
	at msi.gama.runtime.AbstractScope.step(AbstractScope.java:487)
	at msi.gama.metamodel.agent.GamlAgent.stepSubPopulations(GamlAgent.java:201)
	at msi.gama.metamodel.agent.GamlAgent._step_(GamlAgent.java:191)
	at msi.gama.kernel.simulation.SimulationAgent._step_(SimulationAgent.java:169)
	at msi.gama.metamodel.agent.GamlAgent.step(GamlAgent.java:159)
	at msi.gama.runtime.AbstractScope.step(AbstractScope.java:487)
	at msi.gama.metamodel.population.GamaPopulation.step(GamaPopulation.java:144)
	at msi.gama.runtime.AbstractScope.step(AbstractScope.java:487)
	at msi.gama.kernel.experiment.AgentScheduler.step(AgentScheduler.java:95)
	at msi.gama.runtime.AbstractScope.step(AbstractScope.java:487)
	at msi.gama.runtime.FrontEndScheduler.step(FrontEndScheduler.java:86)
	at msi.gama.runtime.FrontEndScheduler.run(FrontEndScheduler.java:125)
	at java.lang.Thread.run(Thread.java:745)

**Comment by AlexisDrogoul** [comment] 2015-11-27 07:26
Hi,

Which JVM/JDK are you running GAMA on ? Mine is 1.8_025, I suspect Patrick's one is the same (or below). 

Alexis

**Comment by hqnghi88** [comment] 2015-11-27 07:28
Dear Alexis,
Mine is 1.8.0_66
C:\WINDOWS\system32>java -version
java version "1.8.0_66"
Java(TM) SE Runtime Environment (build 1.8.0_66-b18)
Java HotSpot(TM) 64-Bit Server VM (build 25.66-b18, mixed mode)

**Comment by AlexisDrogoul** [comment] 2015-11-27 08:08
OK. I tested it under 1.8.0_66, no changes (i.e. it works well). I wonder if Patrick has installed JTS 1.14, though, as this might represent another difference (I use JTS 1.14 also).

**Comment by ptaillandier** [comment] 2015-11-27 08:09
No, I am using jts 1.13

**Comment by hqnghi88** [comment] 2015-11-28 05:14
Dear Alexis, Patrick,
Does the model work well? I mean the agents change colors and the chart show an changements curve?  I have tried with new workspace and it dont work. As my debugging, the problem come from the casting of right expression of accumulate operator, I must add "[]+" :
((myPlace.neighbours + myPlace) accumulate ([] + Host overlapping each)) 
There is no more exception, but the model still dont work (no transition from S to I).
Could you please confirm the situation?
Cheers.

**Comment by AlexisDrogoul** [comment] 2015-11-28 05:38
I can't confirm anything, as the model is working perfectly well on my computer… I really wonder what's happening. Have there been changes to this model recently ?

Reading your comment, I think the problem probably comes, then, from "overlapping" rather than accumulate. But why would this operator be different on Windows and Mac computers ? Really weird.

**Comment by RCura** [comment] 2015-11-28 12:05
NB : On my WIndows 7 x64 computer, using Gama  1.6.1.201511011755 (a git version from few weeks ago), it works well.
Java is jre1.8.0_51, and I don't find the JTS version.

**Comment by hqnghi88** [comment] 2015-11-29 07:42
Hi Robin,
Could you please help me by adding a write before the loop at line 67
    		loop hst over: ((myPlace.neighbours + myPlace) accumulate (Host overlapping each)) {
to show the result of accumulate operator.

As on my pc, 
     write ((myPlace.neighbours + myPlace) accumulate (Host overlapping each)); 
shows a list for ex: [nil,nil,nil,nil,nil,nil,nil,nil,nil,nil,nil,nil,nil]
and 
     write ((myPlace.neighbours + myPlace) accumulate ([]+Host overlapping each)); 
shows a list of list [[],[],[],[],[282 as Host],[],[],[],[],[434 as Host],[],[],[494 as Host]]
Cheers.

**Comment by AlexisDrogoul** [comment] 2015-11-29 10:18
Hi,

I think there is no problem in 1.6.1 (at least, it has never been reported so far), only in the developer version. There are not a lot of possible explanations regarding why Windows would fail and not MacOS X on an operator that is not related to GUI and that does not rely on native libraries (only Java ones). One could be the encoding of the properties files generated by the annotations in Eclipse (which would, somehow, "scramble" some operators); very unlikely, but I'm a bit out of explanations right now...

**Comment by ptaillandier** [comment] 2015-11-30 15:17
Hi,

I just test the infection models on Windows (Windows 10 - Java  1.8.0_45 64
bits - GAMA developper version Luna (with the current version of the libs)
and they work perfectly. No problem at all with the accumulate operator.

Cheers,

Patrick

2015-11-29 11:18 GMT+01:00 Alexis Drogoul <notifications@github.com>:

**Comment by hqnghi88** [comment] 2015-11-30 17:45
Dear Patrick.
I still have the problem with new downloaded eclipse luna, jdk 1.8.0_45 64b, new checkout from git.
:(
But yes, Alexis was right, it work with Gama release 1.6.1
Cheers.

**Comment by AlexisDrogoul** [comment] 2015-12-04 09:45
@hqnghi88, @ptaillandier  Can you verify the encoding of the file "gaml.properties" in msi.gama.core ? Mine is UTF-8 (as it **should** be by default), Julien's one is "ISO something" and that could provide at least a difference between our environments.

**Comment by hqnghi88** [comment] 2015-12-04 09:59
Hi Alexis,
Mine is ISO-xxxx, some of the others in the project properties are cp1252. I wonder how to have utf-8 "as it should be by default" because i have used new downloaded and checkout. Did it come from the eclipse for windows?

**Comment by AlexisDrogoul** [comment] 2015-12-04 10:06
Yes -- Windows forces an encoding which is not UTF-8. One thing we should put on the developer documentation is to set the workspace default to UTF-8 (Eclipse>Preferences>General>Workspace>Default Encoding). Can you try to do it, then rebuild GAMA (Clean All Projects) so as to regenerate the files, and then launch the model to see if it is the cause ?

**Comment by hqnghi88** [comment] 2015-12-04 10:15
Hi Alexis,
Quickly, Pref->..>default doesnt change the encode of gaml.properties. After a clean, it return tu ISOxxxx, despite its parent (msi.gama.core) is already UTF-8. Have we somewhereelse  can change the default encoding?

**Comment by AlexisDrogoul** [comment] 2015-12-04 11:56
Strange. The file should inherit its encoding from its immediate container. However, I've just committed a new version of the processor which forces the encoding to UTF-8. Can you try with it ? Thanks

**Comment by mazarsju** [comment] 2015-12-04 13:25
To force the default encoding to be UTF-8 :
Window / Preferences / General / Content Types / Text, and I chose UTF-8 as default encoding.

But I changes nothing (at least about this issue).

**Comment by hqnghi88** [comment] 2015-12-04 15:47
Hi,
More precicely, I have to choose .properties files in Julien's suggest and with new push of Alexis. Now, all files are UTF-8 but unfortunately, the status is still not changed.

**Comment by AlexisDrogoul** [comment] 2015-12-04 18:06
OK, so it seems the encoding has nothing to do with this, unfortunately… :( I'm still waiting, in case, for the confirmation from Patrick whether he had UTF-8 or ISOxxx for the properties file on his Windows machine.

So can you try something else: comment out all the displays and let the model run. Do you still have the issue ? This is the only thing I can think of that could differ between two different OSes: a possible (although improbable) feedback of displays on the simulation.

**Comment by ptaillandier** [comment] 2015-12-04 19:52
Sorry, I have to wait next Monday to answer your question...

**Comment by hqnghi88** [comment] 2015-12-05 03:52
Dear Alexis,
As you said, It is really improbable. I have tried with some option in preferences of Gama. So i think Patrick's windows machine would reveal the mystery.
By the way of encoding, i have this ÿþ  in the console when model had exception:

ExpandItem created for name 83 occurences in 7 agents at cycle 0ÿþCannot evaluate is_infected as the target agent is null

Is this normal character when we have set utf-8 encoding files?

**Comment by AlexisDrogoul** [comment] 2015-12-14 09:54
OK. I've committed (37b29891cb58382914fff3cb0777328c8baa09c5) a tentative fix for this infamous bug. Julien has tested it and it seems to work. @hqnghi88, @ptaillandier, can you test it as well  ? Note that I havent fully understood what happens, but it seems that there was, in some configurations a wrong call to the Guava Iterables.concat() function, which exists in two forms (with Iterables and Arrays).

**Comment by ptaillandier** [comment] 2015-12-14 16:10
it was working on my windows computer (win 10) and it still works.

Patrick

2015-12-14 10:54 GMT+01:00 Alexis Drogoul <notifications@github.com>:

**Comment by hqnghi88** [comment] 2015-12-15 05:10
Dear Alexis,
I have test on my 3 lap+desk, 2 one work but there are still 1 don't work (with git reset, switch new workspace). I will investigate the differences between them to find out the reason.
Cheers.

**Closed by hqnghi88** 2015-12-15 05:10 UTC
Labels: > Bug, Concerns GAML, OS Windows, Version Git
