### ISSUE TITLE
Saving using shortcut CTRL + S tries to build workspace but still waiting

### ISSUE THREAD

**Issue by DamPhil** [gama-platform/gama#1240] opened 2015-06-05 07:13 UTC
Hi, i'm trying to save my work on the git version of Gama, and on some sessions, when i do the shortcut CTRL+S to save, this window appears and the building workspace stay at 0%, which make me stop manually the different tasks on the window by clicking the red square button. However, if I do the save using the menu of Gama, nothing appears and it works perfectly.

![screenshot from 2015-06-05 14 09 36](https://cloud.githubusercontent.com/assets/12729999/8001112/b717358c-0b8c-11e5-87e3-1d609473a8e6.png)

Thank you in advance

**Comment by AlexisDrogoul** [comment] 2015-06-06 22:22
Note that the same bug also affects MacOS X.

**Comment by AlexisDrogoul** [comment] 2015-06-12 17:30
I have committed a change that should — normally — fix this issue. Is it the case ?

**Comment by AlexisDrogoul** [comment] 2015-06-25 16:57
Issue #1251 added the fact that this bug is also present on Windows 8.1

**Comment by AlexisDrogoul** [comment] 2015-07-01 07:53
The bug, which seems to have disappeared from MacOS X, but is still present in Windows and Ubuntu, seems to be caused (it's a guess) by https://bugs.eclipse.org/bugs/show_bug.cgi?id=60964, a 10 years old bug in the Eclipse jobs system that has only recently (in Eclipse Mars) been solved, because it was regularly happening in the new parallel XText build process. Since the patch has been applied to Eclipse Mars (and not to XText), I wonder how we can benefit from it without moving to Mars — which seems to cause other problems (https://groups.google.com/forum/?fromgroups#!topic/gama-dev/ARGOM8uaERk).

**Comment by AlexisDrogoul** [comment] 2015-07-01 09:40
Unfortunately, I was able to reproduce it (again) in MacOS X, using the Maelia project as a test (lots of builds, lots of modified resources…). Presumably the "simple" builds did not last long enough on my machine to make me reproduce what Damien and Pierre-Antoine depicted on Ubuntu and Windows.

**Comment by AlexisDrogoul** [comment] 2015-07-02 02:11
I've committed minor changes that solve the problem in MacOS X. Could you please test it ?

**Comment by DamPhil** [comment] 2015-07-02 03:44
Tested, I didn't get it back, but maybe i was lucky during the twenty times... If so, i will repost it ! (Tried with different cases, even during experiment)

**Closed** 2015-07-02 04:30 UTC
Labels: > Bug, Affects Usability, Concerns Interface, OS All, Version Git
