### ISSUE TITLE
Index wiki is no longer accessible

### ISSUE THREAD

**Issue by ElCep** [gama-platform/gama#2242] opened 2017-09-19 15:28 UTC
Hi, 
I don't know if it's an issues or a message on `gama group` but I can not access to function definition from the index wiki page ...

### Actual behavior
`The wiki page took too long to render.`

**Comment by hqnghi88** [comment] 2017-09-20 00:27
Hi,
It seems that markdown of github is not working well. For the moment, you
can use this link https://gama-platform.github.io/wiki/OperatorsAC to
search for the document of operators. And you can post an issue to request
a solution for the wiki page.
Cheers.

-------
HUYNH Quang-Nghi
Ph.D.
Lecturer
GAMA http://gama-platform.org/
College of Information and Communication Technology - Can Tho University
Campus II, 3/2 street, Ninh Kieu district
Can Tho city, Vietnam
[Vietnam] +84909128322

**Comment by AlexisDrogoul** [comment] 2017-09-20 02:45
No, the markdown is ok. The problem is that the page is too long (it is an issue we already had, see #1375). I guess the only solution is to split the operators into 3 pages. @dphilippon ?

**Comment by sriramab** [comment] 2017-09-20 03:52
Meanwhile please use this [link](https://gama-platform.github.io/wiki/Index)

**Comment by ElCep** [comment] 2017-09-20 14:12
Great !

**Comment by sriramab** [comment] 2017-09-26 13:19
After these changes, the link I suggest above no longer works. 
see https://gama-platform.github.io/wiki/Index

Is it by mistake or is this link no maintained?

**Comment by sriramab** [comment] 2017-09-26 13:21
Please see, Also this link is lost https://github.com/gama-platform/gama/wiki/Index

**Comment by AlexisDrogoul** [comment] 2017-09-26 13:59
Works for me now. I think we can (re)close it !

**Closed by AlexisDrogoul** 2017-09-26 13:59 UTC
Labels: In Documentation

**Comment by hqnghi88** [comment] 2017-09-26 14:01
Just for Sriri to know what happened, It was my mistake when rebuild the wiki, my eclipse adjust some spaces to the files, but markdown was not happy with spaces. 
It fixed

**Comment by sriramab** [comment] 2017-09-26 14:05
Thank you, one is working but second is still not working, please see https://gama-platform.github.io/wiki/Index

**Comment by sriramab** [comment] 2017-09-26 14:07
I think this second is important as I read from an issue few months back that Damien had written a script that instantly updates wiki with each commit and this link was proposed, but now is not working (yet). May be I should wait!

**Comment by hqnghi88** [comment] 2017-09-26 14:17
Hello Sriri,
It's magic. Now, both will be updated automatically.
