### ISSUE TITLE
Declaration of Matrices - columns and rows

### ISSUE THREAD

**Issue by ptaillandier** [gama-platform/gama#3155] opened 2021-08-01 01:12 UTC
In GAMA 1.8.2, "matrix([[1,1,1],[2,2,2]])" returns a matrix with a first column [1,1,1] and a second column [2,2,2]. 

I am not totally sure, but I think, in previous versions of GAMA, this gaml expression returns a matrix with for first line [1,1,1] and for second line [2,2,2]. 

The question is thus, is this new "behavior" normal? 

One of the side effect of this change is that there is a bug on the regression example where there is a mix between rows and columns.

**Comment by AlexisDrogoul** [comment] 2021-08-03 17:06
Actually the code (in the GamaXXXMatrix constructors from a list) has not changed since 2015, and loads the matrix from a supposed list of columns, so I do not really understand what can cause this new behaviour and if it is a new behaviour at all. What is the bug in the regression ? One issue, however, is that toString() or serialize() are returning the reverse (list of rows). I will correct this in the next commit.

**Comment by AlexisDrogoul** [comment] 2021-09-19 02:02
It has been corrected, so I guess we can close this issue/question ?

**Closed by AlexisDrogoul** 2021-09-19 02:02 UTC
Labels: >> 🤔 Question, 📃 Concerns GAML, 👍* Fix to be tested
