### ISSUE TITLE
Java access violation when executing old exemples

### ISSUE THREAD

**Issue by mazarsju** [gama-platform/gama#1288] opened 2015-11-02 08:50 UTC
A lot of examples (such as Ant Foraging (Charts examples) - Experiment Ant) crash after a few seconds while running the experiment, with an access violation exception.

**Comment by mazarsju** [comment] 2015-11-02 08:50
NB : I'm in Windows 8, maybe the problem doesn't exist in other OS...

**Comment by AlexisDrogoul** [comment] 2015-11-02 08:58
Would it be possible to have a log to know where this access violation takes place ? 


> Le 2 nov. 2015 à 09:50, mazarsju <notifications@github.com> a écrit :
> 
> A lot of examples (such as Ant Foraging (Charts examples) - Experiment Ant) crash after a few seconds while running the experiment, with an access violation exception.
> 
> —
> Reply to this email directly or view it on GitHub.
> 

--
Senior Researcher, UMI UMMISCO 209, IRD & UPMC, France.
--
alexis.drogoul@gmail.com | http://goo.gl/4ewFdJ
[Vietnam] +84915088155 [France] +33608698845
--
GAMA: http://gama-platform.org

**Comment by mazarsju** [comment] 2015-11-02 09:00
[hs_err_pid4336.txt](https://github.com/gama-platform/gama/files/25144/hs_err_pid4336.txt)

**Comment by mazarsju** [comment] 2015-11-02 09:03
[hs_err_pid5452.txt](https://github.com/gama-platform/gama/files/25145/hs_err_pid5452.txt)

(Better this one, I'm not sure about the first one. This one was after trying to run Ant Foraging (Charts examples) - Experiment Ant.)

**Comment by mazarsju** [comment] 2015-11-09 07:42
It seems like it's more an OpenGL problem : the problem appears when I display an opengl output (example : the Incremental Model 5 works when I delete the map_3D display). I'll try to investigate more deeply the problem.

NB : on an other hand, some experiments using opengl outputs (such as Complex Objects Loading/Objects Loading.gaml) work fine...

**Comment by AlexisDrogoul** [comment] 2015-12-02 05:05
Do you still have the bug present under Windows 10 ? There is maybe a problem of JOGL implementation under Windows 8.

**Comment by mazarsju** [comment] 2015-12-02 05:08
Yes, same problem...

**Comment by AlexisDrogoul** [comment] 2015-12-04 08:16
@hqnghi88 , can you test whether you have the same problem or no on Windows ?

**Comment by hqnghi88** [comment] 2015-12-04 08:40
Dear Alexis,
I cant reproduce this issue, the simulation still now work from the moment that i saw your question (20mns). Windows 10, jdk 8u66, mars1+egit.

**Comment by AlexisDrogoul** [comment] 2015-12-04 08:45
OK. Thanks. What is your video card ? Julien's one is an "AMD RADEON HD 7600M" and I wonder if this issue not specific to his setup.

**Comment by hqnghi88** [comment] 2015-12-04 08:49
Dear Alexis,
I use Nvidia series (GT 705 GT, 750M ). We can test if the issue still occur when graphics card is disable?

**Comment by mazarsju** [comment] 2015-12-04 09:06
Exact, when I disable my graphical card, it works. I'll report the issue in jogamp

**Comment by AlexisDrogoul** [comment] 2015-12-04 09:09
Great. I close the issue, then, but maybe we should put it somewhere in the documentation (Troubleshooting part) ?

**Closed by AlexisDrogoul** 2015-12-04 09:09 UTC
Labels: > Bug, Concerns Simulation, Display OpenGL, OS Windows, Version Git
