### ISSUE TITLE
BufferUnderflowException with some shapefile

### ISSUE THREAD

**Issue by hqnghi88** [gama-platform/gama#3094] opened 2021-04-23 01:13 UTC
Using a simple model (just import shp, create simple agents and display them) in attached zip.

[Test.zip](https://github.com/gama-platform/gama/files/6362036/Test.zip)

When we launch the model, an exception appears in gama:
2 occurrences in 2 agents at cycle 0: Java error: BufferUnderflowException
in create A from: ss ;
BufferUnderflowException: null
java.base/java.nio.DirectDoubleBufferU.get(DirectDoubleBufferU.java:312)
org.geotools.data.shapefile.shp.PolygonHandler.readCoordinates(PolygonHandler.java:308)
org.geotools.data.shapefile.shp.PolygonHandler.read(PolygonHandler.java:139)
org.geotools.data.shapefile.shp.ShapefileReader$Record.shape(ShapefileReader.java:114)
org.geotools.data.shapefile.ShapefileFeatureReader.getGeometry(ShapefileFeatureReader.java:238)
org.geotools.data.shapefile.ShapefileFeatureReader.hasNext(ShapefileFeatureReader.java:181)
msi.gama.util.file.GamaShapeFile.readShapes(GamaShapeFile.java:376)
in agents Simulation 0, main0
I dont have it before ( November 2020) and did not change the model and the data. So probably this come from my data and also the update of jdk.
Gama git 1.8.2
windows 10.

**Comment by AlexisDrogoul** [comment] 2021-04-25 14:20
Main suspect is that the version of GeoTools has changed since then. And it seems to be related to the fact that this ShapeFile "geometry type" is Polygon2.5D, not Polygon or MultiPolygon. I verified it with QGis, exported to a "2D only" Polygon shapefile (see below), and it worked. 
[2D.zip](https://github.com/gama-platform/gama/files/6372147/2D.zip)

**Comment by AlexisDrogoul** [comment] 2021-04-25 14:21
One thing to notice, however, is that the shape file viewer, which also relies on GeoTools obviously, has no problem loading and displaying the file. So there is something in what we do that creates it.

**Comment by AlexisDrogoul** [comment] 2021-04-26 03:01
After more digging, the problem appears to be caused by the fact that the geometries are considered as 3D + M (measure) -- but I don't know why. How did you create this ShapeFile ? 
I've rewritten the reader to better make use of GeoTools utilities (visitors, etc.) but it doesnt change the fact that it is failing on the first attempt to read the coordinates of a feature...

**Comment by hqnghi88** [comment] 2021-04-26 03:29
Dear Alexis,
Probably the origin of that shapefile come from the model Image vectorization, but i just regenerate a new file and it does not have the problem. So mostly i have mistaken in some process with qgis when i editing that shapefile ( i have no idea what is 3D +M or 2.5D in qgis, so may be just my stupidity, no one will create such type of file). OR somehow there has some corruption when both qgis and gama write on 1 file that cause a wrong translate in metadata?

**Comment by AlexisDrogoul** [comment] 2021-04-26 06:09
Hi Nghi,

Seems like it's a known problem in GeoTools for certain files. See for instance https://osgeo-org.atlassian.net/browse/GEOT-6800 (and the related issues). It's supposedly fixed in version 26... and we are at version 25. I will try to check what the fix is and how we can implement it in GAMA.

**Comment by AlexisDrogoul** [comment] 2021-04-26 06:26
There is a fix for GeoTools 26, and two backports to 23 and 24... (https://github.com/geotools/geotools/pulls?page=10&q=is%3Apr) but... nothing for 25. I don't get it ! Why is it so ? Does someone know how backports are decided for GeoTools ?

**Comment by hqnghi88** [comment] 2021-04-29 15:29
I ve new case for the same issue (same exception). This time, with the same shape file, model, but after the commit 93941a99982f53381112c08dd6d1ce87efcf5219 , it reproduce the exception. I dig a big in the change of that commit and found a workaround (just for this case): instead of using FileDataStoreFinder.getDataStore, i reuse the old getDataStore.

			store = getDataStore(file.toURI().toURL());//FileDataStoreFinder.getDataStore(file);
Note that this only work for the new case, the origin data of this issue is till broken and throw the same exception

**Comment by JoshMcCullough** [comment] 2021-08-31 20:39
I really need to get past this issue. I was using v25 so I tried 25.2 and 24.4 but both give the same issue. 

Can anyone confirm which versions include this fix, specifically?

**Comment by AlexisDrogoul** [comment] 2021-09-25 04:24
@ptaillandier @hqnghi88 @JoshMcCullough what's the update on this issue ? Changing the GeoTools version is a bit of a complex task and we'd need to know, first, if this problem still occurs on [GeoTools 26](http://geotoolsnews.blogspot.com/2021/09/geotools-26-rc-release-candidate.html)

**Comment by hqnghi88** [comment] 2021-09-25 05:31
I still have this exception with the model i attached above:
2 occurrences in 2 agents at cycle 0: Java error: BufferUnderflowException
in create A from: ss ;
BufferUnderflowException: null
java.base/java.nio.DirectDoubleBufferU.get(DirectDoubleBufferU.java:312)
org.geotools.data.shapefile.shp.PolygonHandler.readCoordinates(PolygonHandler.java:308)
org.geotools.data.shapefile.shp.PolygonHandler.read(PolygonHandler.java:139)
org.geotools.data.shapefile.shp.ShapefileReader$Record.shape(ShapefileReader.java:114)
org.geotools.data.shapefile.ShapefileFeatureReader.getGeometry(ShapefileFeatureReader.java:238)
org.geotools.data.shapefile.ShapefileFeatureReader.hasNext(ShapefileFeatureReader.java:181)
org.geotools.data.store.ContentFeatureSource.accepts(ContentFeatureSource.java:786)
in agents Simulation 0, main0

**Comment by ptaillandier** [comment] 2021-09-25 07:48
I think, the problem is mainly due to the fact that 2 of our geometries are invalid (you can check with QGIS or OpenJump). I used OpenJump to clean it and it works after.
But it is true that OpenJump, QGIS and the viewer of GAMA are able to read this shapefile... so we should be able to read it as well.

**Comment by ptaillandier** [comment] 2021-09-27 07:43
I committed a workaround. it is not very clean...but considering the invalid data proposed for this issue, it is better than nothing (and enough for the moment).

**Closed by ptaillandier** 2021-09-27 07:43 UTC
Labels: Version 1.8.2
