### ISSUE TITLE
Wrong variable scope inside loops?

### ISSUE THREAD

**Issue by ndgnuh** [gama-platform/gama#3085] opened 2021-04-08 08:19 UTC
**Describe the bug**
Inside loop, variable with the same name as species will refer to *the-species* instead of whatever is being looped over. 

#### This is not just the editor warning. The behavior is **wrong** here. The `prey` inside the loop refers to a species (`species<prey>`), when it should have been some instances of `species<prey>` (`prey[0]`, `prey[1]`...).

**To Reproduce**
Minimum working example
```gaml
// main experiment
model agent_container

import "helper.gaml"

global {
	list<prey> herd;

	init {
		create prey number: 3;
	}

	reflex x {
		write "population: " + prey.population;
		herd <- H.herd1(prey.population);
		write "herd1 result is " + herd;
		herd <- H.herd2(prey.population);
		write "herd2 result is " + herd;
		do pause;
	}
}

species prey {}
experiment name type: gui {}
```

```gaml
// helper.gaml
model util

global {
	helper H;

	init {
		create helper number: 1;
		H <- helper[0];
	}

}

species helper {
	list<agent> herd2 (list<agent> preys) {
		list<agent> ret <- [];
		loop prey over: preys {
			write "agent: " + prey + " of type: " + type_of(prey); // write a species
			ret << prey;
		}

		return ret;
	}

	list<agent> herd1 (list<agent> preys) {
		list<agent> ret <- [];
		loop _oOo_prey_oOo_ over: preys {
			write "agent: " + _oOo_prey_oOo_ + " of type: " + type_of(_oOo_prey_oOo_);
			ret << _oOo_prey_oOo_;
		}

		return ret;
	}

}
```

**Expected behavior**
A normal loop?

**Desktop (please complete the following information):**
 - OS: Linux5.10
 - PC Model: Thinkpad13
 - GAMA version: GAMA_1.8.2_Alpha_withJDK_Linux_03.03.21_ec9bb7cb.zip
 - Java version: bundled with GAMA
 - Graphics cards / Display system: IntelHDGraphics, X11

**Additional context**
The above example is a minimal one, I was doing something else more complex with the `herd` function. This example is the minified version.

**Comment by benoitgaudou** [comment] 2021-04-15 05:27
I admit I would prefer that the compiler shows an error (to  show the user that it is using an already declared variable), rather than overriding the variable...

**Comment by ndgnuh** [comment] 2021-04-16 07:12
I think most other languages do this:

```lua
x = "Not a number" 
for x = 1,3 do
    print(x)
end -- print numbers
print(x) -- print "Not a number"
```

...well, this is not true for Python, but at least it does what you ask in the loop.

**Comment by hqnghi88** [comment] 2021-04-16 07:58
Please describe more about the issue, what wrong in your code? any error or warning should have or misplaced? or wrong expected result when launch simulation? I tried your code and there is already a warning of casting
![image](https://user-images.githubusercontent.com/6105384/114991742-223af580-9ec4-11eb-8e0d-f62f2d97b40c.png)

**Comment by ndgnuh** [comment] 2021-04-16 08:00
In the runtime, the prey is mistaken to be a `species<prey>`, when it should be one of the item inside the the collection I was looping over. In this case, the item should be *one instance* of the `species<prey>`

**Comment by hqnghi88** [comment] 2021-04-16 08:02
> ```lua
> x = "Not a number" 
> for x = 1,3 do
>     print(x)
> end -- print numbers
> print(x) -- print "Not a number"
> ```

what is the meaning? there is some confusion, ambiguous when x did not take the last assign value. At least , a rule must be write somewhere like : for x create a temporal variable. in that case, there is 2 x different. If it is not a tempory var, it should take the last assginment (x = 3) , not  "Not a number" . Anyway , open a discussion if you are interesting.

**Comment by ndgnuh** [comment] 2021-04-16 08:07
That example is lexical scoping, which most languages does. It this case, Gama is doing neither. It use a value defined from *before* the loop, so it's not dynamic, but not create a new variable (with the same name) in side the scope of loop, so it's not lexical.

**Comment by hqnghi88** [comment] 2021-04-16 08:23
OK , got the issue: in the herd2, the loop prey over: preys dont have a warning about "prey" variable is supersede "prey" species.

**Comment by ndgnuh** [comment] 2021-04-16 08:28
No, it not just the warning. The behavior is *wrong* here. The `prey` inside the loop refers to a species (`species<prey>`, when it should have been some instances of `species<prey>` (`prey[0]`, `prey[1]`...)

**Comment by hqnghi88** [comment] 2021-04-16 08:34
OK, thanks, and all that you should explain at the top, in your issue.

**Comment by benoitgaudou** [comment] 2021-04-16 09:00
@ndgnuh in Java the code you showed raises a compilation error (as x is an already defined variable).
I would be in favor of raising an error in  GAMA  too (to show  the user that the variable used  in the loop already exists)

**Comment by ndgnuh** [comment] 2021-04-16 09:05
> @ndgnuh in Java the code you showed raises a compilation error (as x is an already defined variable).
> I would be in favor of raising an error in GAMA too (to show the user that the variable used in the loop already exists)

You meant that Java throw errors when the code is ran? Or the editor shows complain that the code has errors? If the editor complains then it might be another bug, because sometime that happens to me, but when I close the file and open it again, the errors is gone.

Also, I could not try the code on latest version because of #3090

**Comment by benoitgaudou** [comment] 2021-04-16 09:08
In Java, this is a compilation error, so a complain in the editor :-)

**Comment by ndgnuh** [comment] 2021-04-16 09:10
Can you try to close and open the file please? Just to see if it the error complain would be gone or not.

**Comment by AlexisDrogoul** [comment] 2021-04-16 09:34
Neither the lexical nor the runtime scopes are correct here because `prey` is a species name, which is treated in agents ad in the loop statement like a special variable. Other scoping priorities are correctly enforced, but not this one in this specific case. I will issue a fix at some point.

**Comment by AlexisDrogoul** [comment] 2021-04-17 14:31
Hi,

I've digged a bit more and I actually found that the problem is not really a problem of scoping, but a combination of problems which should have normally led to a compilation error if you hadn't been in such a strange configuration (actually, the problem does not belong to `helper.gaml` by itself, as `prey` is only defined in `agent_container`. it is only when it is imported that the problem manifests itself -- and it did it only as a warning, meaning if was not reported in `agent_container`). I changed the warning into an error and also made sure that variables with species names would respect the scope when requested -- although it should not happen anymore now). 

Please test !

Alexis

**Comment by ndgnuh** [comment] 2021-06-17 10:12
Now that the run button issues is resolved, I can test this thing.

When changing `herd2` to this, `prey_` (outside of the loop) got changed to what ever the last element of `preys` is. Is that an expected behavior?

```gaml
	list<agent> herd2 (list<agent> preys) {
		int prey_ <- 0;
		list<agent> ret <- [];
		loop prey_ over: preys {
			write "agent: " + prey_ + " of type: " + type_of(prey_);
			ret << prey_;
		}

		write "Prey_: " + prey_;
		return ret;
	}
```

**Comment by AlexisDrogoul** [comment] 2021-09-03 15:19
Hi, any update on this one, have you been able to test the fix ?

**Comment by AlexisDrogoul** [comment] 2021-09-19 01:50
Closing it now (I've tested it myself in different scenarios). Reopen if it still manifests itself.

**Closed by AlexisDrogoul** 2021-09-19 01:50 UTC
Labels: 👍* Fix to be tested
