### ISSUE TITLE
Problem  launching GAMA from Eclipse (Model Library empty)

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#2739] opened 2019-05-27 10:17 UTC
**Describe the bug**
I am not sure to know if it's a bug but I prefer to report it as we are close to the release.

After an update on Eclipse I try to run GAMA. I can run it however I have no model in the library and this error:

`````
java.lang.NoClassDefFoundError: org/apache/commons/lang/StringUtils
	at msi.gama.lang.gaml.resource.GamlResourceInfoProvider.getInfo(GamlResourceInfoProvider.java:77)
	at msi.gama.lang.gaml.resource.GamlResourceInfoProvider.getInfo(GamlResourceInfoProvider.java:138)
	at msi.gama.util.GAML.getInfo(GAML.java:287)
	at ummisco.gama.ui.metadata.FileMetaDataProvider.createGamlFileMetaData(FileMetaDataProvider.java:443)
	at ummisco.gama.ui.metadata.FileMetaDataProvider.lambda$0(FileMetaDataProvider.java:339)
	at ummisco.gama.ui.metadata.FileMetaDataProvider.getMetaData(FileMetaDataProvider.java:371)
	at ummisco.gama.ui.navigator.contents.ResourceManager.processAddition(ResourceManager.java:277)
	at ummisco.gama.ui.navigator.contents.ResourceManager.visit(ResourceManager.java:438)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:67)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:77)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:77)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:77)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:51)
	at ummisco.gama.ui.navigator.contents.ResourceManager.resourceChanged(ResourceManager.java:232)
	at ummisco.gama.ui.navigator.contents.ResourceManager.lambda$0(ResourceManager.java:87)
	at org.eclipse.ui.internal.PendingSyncExec.run(PendingSyncExec.java:61)
	at org.eclipse.ui.internal.UILockListener.doPendingWork(UILockListener.java:171)
	at org.eclipse.ui.internal.UISynchronizer.lambda$0(UISynchronizer.java:153)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4102)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3769)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1173)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1062)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:566)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at msi.gama.application.Application.start(Application.java:121)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:400)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:661)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:597)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1476)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1449)
java.lang.NoClassDefFoundError: org/apache/commons/lang/StringUtils
	at msi.gama.lang.gaml.resource.GamlResourceInfoProvider.getInfo(GamlResourceInfoProvider.java:77)
	at msi.gama.lang.gaml.resource.GamlResourceInfoProvider.getInfo(GamlResourceInfoProvider.java:138)
	at msi.gama.util.GAML.getInfo(GAML.java:287)
	at ummisco.gama.ui.metadata.FileMetaDataProvider.createGamlFileMetaData(FileMetaDataProvider.java:443)
	at ummisco.gama.ui.metadata.FileMetaDataProvider.lambda$0(FileMetaDataProvider.java:339)
	at ummisco.gama.ui.metadata.FileMetaDataProvider.getMetaData(FileMetaDataProvider.java:371)
	at ummisco.gama.ui.commands.RefreshHandler$2.lambda$0(RefreshHandler.java:128)
	at org.eclipse.core.internal.resources.Resource.lambda$0(Resource.java:85)
	at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:85)
	at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:90)
	at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:90)
	at org.eclipse.core.internal.watson.ElementTreeIterator.iterate(ElementTreeIterator.java:127)
	at org.eclipse.core.internal.resources.Resource.accept(Resource.java:94)
	at org.eclipse.core.internal.resources.Resource.accept(Resource.java:55)
	at ummisco.gama.ui.commands.RefreshHandler$2.runInWorkspace(RefreshHandler.java:124)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:42)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.lang.StringUtils cannot be found by msi.gama.lang.gaml_1.7.0.qualifier
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:511)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:422)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:414)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:153)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 17 more
!SESSION 2019-05-27 12:13:02.297 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.8.0_161
java.vendor=Oracle Corporation
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=en_US
Framework arguments:  -product msi.gama.application.runtime --launcher.defaultAction openFile
Command-line arguments:  -product msi.gama.application.runtime -data /Users/Arno/eclipse-workspace-2019/../runtime-gama.runtime.product -dev file:/Users/Arno/eclipse-workspace-2019/.metadata/.plugins/org.eclipse.pde.core/gama.runtime.product/dev.properties -os macosx -ws cocoa -arch x86_64 -consoleLog -data @noDefault --launcher.defaultAction openFile

!ENTRY org.eclipse.core.jobs 4 2 2019-05-27 12:13:24.569
!MESSAGE An internal error occurred during: "Refreshing the GAMA Workspace".
!STACK 0
java.lang.NoClassDefFoundError: org/apache/commons/lang/StringUtils
	at msi.gama.lang.gaml.resource.GamlResourceInfoProvider.getInfo(GamlResourceInfoProvider.java:77)
	at msi.gama.lang.gaml.resource.GamlResourceInfoProvider.getInfo(GamlResourceInfoProvider.java:138)
	at msi.gama.util.GAML.getInfo(GAML.java:287)
	at ummisco.gama.ui.metadata.FileMetaDataProvider.createGamlFileMetaData(FileMetaDataProvider.java:443)
	at ummisco.gama.ui.metadata.FileMetaDataProvider.lambda$0(FileMetaDataProvider.java:339)
	at ummisco.gama.ui.metadata.FileMetaDataProvider.getMetaData(FileMetaDataProvider.java:371)
	at ummisco.gama.ui.commands.RefreshHandler$2.lambda$0(RefreshHandler.java:128)
	at org.eclipse.core.internal.resources.Resource.lambda$0(Resource.java:85)
	at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:85)
	at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:90)
	at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:90)
	at org.eclipse.core.internal.watson.ElementTreeIterator.iterate(ElementTreeIterator.java:127)
	at org.eclipse.core.internal.resources.Resource.accept(Resource.java:94)
	at org.eclipse.core.internal.resources.Resource.accept(Resource.java:55)
	at ummisco.gama.ui.commands.RefreshHandler$2.runInWorkspace(RefreshHandler.java:124)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:42)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.lang.StringUtils cannot be found by msi.gama.lang.gaml_1.7.0.qualifier
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:511)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:422)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:414)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:153)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 17 more
java.lang.NoClassDefFoundError: org/apache/commons/lang/StringUtils
	at msi.gama.lang.gaml.resource.GamlResourceInfoProvider.getInfo(GamlResourceInfoProvider.java:77)
	at msi.gama.lang.gaml.resource.GamlResourceInfoProvider.getInfo(GamlResourceInfoProvider.java:138)
	at msi.gama.util.GAML.getInfo(GAML.java:287)
	at ummisco.gama.ui.metadata.FileMetaDataProvider.createGamlFileMetaData(FileMetaDataProvider.java:443)
	at ummisco.gama.ui.metadata.FileMetaDataProvider.lambda$0(FileMetaDataProvider.java:339)
	at ummisco.gama.ui.metadata.FileMetaDataProvider.getMetaData(FileMetaDataProvider.java:371)
	at ummisco.gama.ui.commands.RefreshHandler$2.lambda$0(RefreshHandler.java:128)
	at org.eclipse.core.internal.resources.Resource.lambda$0(Resource.java:85)
	at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:85)
	at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:90)
	at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:90)
	at org.eclipse.core.internal.watson.ElementTreeIterator.iterate(ElementTreeIterator.java:127)
	at org.eclipse.core.internal.resources.Resource.accept(Resource.java:94)
	at org.eclipse.core.internal.resources.Resource.accept(Resource.java:55)
	at ummisco.gama.ui.commands.RefreshHandler$2.runInWorkspace(RefreshHandler.java:124)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:42)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.lang.StringUtils cannot be found by msi.gama.lang.gaml_1.7.0.qualifier
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:511)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:422)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:414)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:153)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 17 more
`````

**Comment by AlexisDrogoul** [comment] 2019-05-27 10:32
Duplicate of #2736 ?

**Closed by AlexisDrogoul** 2019-05-27 10:32 UTC
