### ISSUE TITLE
full screen with simulation control

### ISSUE THREAD

**Issue by sriramab** [gama-platform/gama#2282] opened 2017-11-02 12:30 UTC
Hi,

When running a simulation, pressing esc key allows a full screen display. But this display does not have any simulation controls (stop, pause, run). So one has to quit full screen view to be able to use these simulation controls. 

Would it be possible to have at least - pause, run - controls if not the stop or close button?
Or is this already possible?

thank you
Srirama

**Comment by hqnghi88** [comment] 2017-11-02 12:42
Hi Sriri,
shortcut key is already implemented, try some such as Cmd+P, Cmd+S...
it has a post in group (by Alexis)

**Comment by agrignard** [comment] 2017-11-02 18:43
A big big NO for this request as I ask for fullscreen especially to have nothing expect the simulation ! ;-)

The aim of this feature is to have is a real fullscreen without anything, BTW if I want to be picky it's not actually a 100% fullscreen as we see the frame of the window and when you do it from a projector you see a big white rectangle (that you can see also on your desktop screen => issue or it's to picky?

**Comment by AlexisDrogoul** [comment] 2017-11-04 05:02
@sriramab  is right. Apart a few people, who knows how to entrer fullscreen and what to do once you're there ? No indication are given anywhere. 

I've begun something to alleviate for this problem. When you have time, press CMD+T (or CTRL+T) when in fullscreen.

**Comment by agrignard** [comment] 2017-11-04 17:55
As we are in this fullscreen thread, is it a big deal to remove the white frame? I know it sounds like a detail (especially on a screen it's not a big big deal ) but when projecting a simulation on a 3D table the problem is that even with a blackscreen the frame of the projector is displayed because of that.

**Comment by sriramab** [comment] 2017-11-04 20:26
Hmm, well, The idea of my question was from a different perspective. Imagine the following two cases:

1. Browser-GAMA: When GAMA incarnates into the body of a browser, theoretically it is possible to run a model via ipad/tablet/touch-interfaces? If this is true. Then I have no access to shortcut keys. I am completely dependent on what is on screen. 

2. I am exploring GAMA on Microsoft Surface in my Lab, a completely touch interface. again, no access to keyboard shortcuts. 

So in these cases, there needs to be something on the screen for me to touch. And if this is completely true, I envision , a button somewhere on the full screen should give me access to touch open a sliding panel which allows me to a) select displays while in simulation mode. b) a sliding panel to allow simulation controls. And again, if this is true, my preference would be to have buttons at the bottom side where the user/operator is standing. it would be too odd to have these buttons anywhere else as then user will have to stretch arms to reach these buttons and thereby obstructing view of other participants around the touch table.

That was my idea behind the question, but then I could not also find it for normal desktop version and I posted this question :)

**Comment by sriramab** [comment] 2017-11-04 20:29
Alexis, I downloaded the latest build version, but command T on my mac showed me nothing while I was in a full screen simulation mode (with `esc`).

**Comment by AlexisDrogoul** [comment] 2017-11-05 07:23
Hi

Two things :

- I don't see any white frame in my displays. Are you sure you have the
preferences right? There is one about disabling frames.
- regarding the shortcut, I can't reproduce it. It's working smoothly on my
Mac. Be sure to configure full-screen with native mode off and menu bar
disabled. Also you might want to force it with the new preference to have
toolbar on.

Alexis

Le 4 nov. 2017 21:29, "Srirāma Bhamidipāti" <notifications@github.com> a
écrit :

**Comment by agrignard** [comment] 2017-11-06 15:26
Oh indeed I didn't know there was a parameters, so yes indeed if I put it to false it's ok!

What about put it to false by default?

**Comment by agrignard** [comment] 2017-11-15 22:23
I close this issue unless @sriramab reopen it if you still have a problem

**Closed by agrignard** 2017-11-15 22:23 UTC
Labels: > Enhancement, Affects Usability, Concerns Interface
