### ISSUE TITLE
Review the documentation of the file operators

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#2399] opened 2018-04-08 20:26 UTC
### Actual behavior
The documentation of operators related to file need to be improved (in particular because it is not exactly automatically generated from the possible existing methods).

A good example is the csv_file: the complete way to use it (with the type), needs to be documented:
	file data <- csv_file("../includes/exampledata.csv", ",", string, false);

### System and version 
Documentation

**Comment by sriramab** [comment] 2018-04-08 20:40
I agree.

**Comment by AlexisDrogoul** [comment] 2018-07-06 09:58
Closed as a duplicate of #1494, already tracked in #1362

**Closed by AlexisDrogoul** 2018-07-06 09:58 UTC
Labels: > Enhancement, In Documentation
