### ISSUE TITLE
Pedestrian Plugin (and potentially other) shouldn't be available on 1.8.2

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#3144] opened 2021-07-21 11:33 UTC
**Describe the bug**
Using 1.8.2 and working on a project requiring the Pedestrain  skills, I though I had to instal this plugins but it is now embeded

**To Reproduce**
1. Install the pedestrian plugins
2. Restart Gama

**Expected behavior**
Normal

**Screenshots**
Stay stuck on the refreshing workspace even when creating a new workspace

<img width="1792" alt="Screenshot 2021-07-21 at 12 40 29" src="https://user-images.githubusercontent.com/3928502/126481997-cc7d025b-0713-495a-897b-a2f415cdb82e.png">

I guess we shoudl find a way to to propose it in the list of available plugin for Gama 1.8.2

**Desktop (please complete the following information):**
 - OS: Mac OS Catalina

**Additional context**

**Comment by hqnghi88** [comment] 2021-08-01 03:48
It's probably the incompatible of version, experimental root repository is for 1.8.1. I should release a sub repo for 1.8.2. I will let you know soon

**Comment by AlexisDrogoul** [comment] 2021-09-09 11:13
Duplicate of #2962. No fix yet but it will come sooner or later when the versioning of GAMA will be better.

**Closed by AlexisDrogoul** 2021-09-09 11:13 UTC
Labels: Version 1.8.2
