### ISSUE TITLE
NPE : null image data, with a new workspace

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#3016] opened 2020-07-31 09:14 UTC
**Describe the bug**

When running GAMA on a new workspace,  in the Eclipse console some errors appear.
(without any visible on  the GAMA side).
This does not appear if the workspace  already exists.

**To Reproduce**
1. Run GAMA Git version
2. Choose a new folder as workspace (to have  a very new  workspace)
3. Look at the Eclipse  console:

```
Adding object pool: Execution Context
Adding object pool: Agent Execution Context
> GAMA building GAML artefacts in : 1034ms
Adding object pool: Envelope 3D
java.lang.NullPointerException
	at msi.gama.common.util.ImageUtils.toCompatibleImage(ImageUtils.java:209)
	at ummisco.gama.ui.metadata.ImageDataLoader.getImageData(ImageDataLoader.java:165)
	at ummisco.gama.ui.metadata.FileMetaDataProvider.createImageFileMetaData(FileMetaDataProvider.java:462)
	at ummisco.gama.ui.metadata.FileMetaDataProvider.lambda$0(FileMetaDataProvider.java:339)
	at ummisco.gama.ui.metadata.FileMetaDataProvider.getMetaData(FileMetaDataProvider.java:377)
	at ummisco.gama.ui.commands.RefreshHandler$3.lambda$0(RefreshHandler.java:171)
	at org.eclipse.core.internal.resources.Resource.lambda$0(Resource.java:85)
	at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:85)
	at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:90)
	at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:90)
	at org.eclipse.core.internal.watson.ElementTreeIterator.iterate(ElementTreeIterator.java:127)
	at org.eclipse.core.internal.resources.Resource.accept(Resource.java:94)
	at org.eclipse.core.internal.resources.Resource.accept(Resource.java:55)
	at ummisco.gama.ui.commands.RefreshHandler$3.runInWorkspace(RefreshHandler.java:167)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:42)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
null image data
java.lang.NullPointerException
	at msi.gama.common.util.ImageUtils.toCompatibleImage(ImageUtils.java:209)
	at ummisco.gama.ui.metadata.ImageDataLoader.getImageData(ImageDataLoader.java:165)
	at ummisco.gama.ui.metadata.FileMetaDataProvider.createImageFileMetaData(FileMetaDataProvider.java:462)
	at ummisco.gama.ui.metadata.FileMetaDataProvider.lambda$0(FileMetaDataProvider.java:339)
	at ummisco.gama.ui.metadata.FileMetaDataProvider.getMetaData(FileMetaDataProvider.java:377)
	at ummisco.gama.ui.navigator.contents.ResourceManager.processAddition(ResourceManager.java:277)
	at ummisco.gama.ui.navigator.contents.ResourceManager.visit(ResourceManager.java:438)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:67)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:77)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:77)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:77)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:51)
	at ummisco.gama.ui.navigator.contents.ResourceManager.resourceChanged(ResourceManager.java:232)
	at ummisco.gama.ui.navigator.contents.ResourceManager.lambda$0(ResourceManager.java:87)
	at org.eclipse.ui.internal.PendingSyncExec.run(PendingSyncExec.java:61)
	at org.eclipse.ui.internal.UILockListener.doPendingWork(UILockListener.java:171)
	at org.eclipse.ui.internal.UISynchronizer.lambda$0(UISynchronizer.java:153)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4102)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3769)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1173)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1062)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:566)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at msi.gama.application.Application.start(Application.java:128)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:400)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:661)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:597)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1476)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1449)
null image data
```

**Desktop (please complete the following information):**
 - OS: macOS Catalina
 - GAMA version: git

**Comment by AlexisDrogoul** [comment] 2021-09-03 18:07
I would bet it is an effect of your strange TIFF files ... or other malformed image files. I have improved the error reporting to at least mention the file name, but there's nothing we can really do.

**Comment by AlexisDrogoul** [comment] 2021-09-20 05:17
I cant reproduce this bug, even by following the steps above. Only possibility would be that you have exotic file formats in your own copy of the models library... But with the stock one, nothing is reported and no error appears when computing the metadata (with "Display Metadata in Navigator" enabled, of course). So I close it -- reopen it if it still happens, and give in that case more details about your own installation.

**Closed by AlexisDrogoul** 2021-09-20 05:17 UTC
Labels: >> 😱 Bug, Version Git, ❌ * Not reproducible
