### ISSUE TITLE
Memory leak in GAMA

### ISSUE THREAD

**Issue by romainreuillon** [gama-platform/gama#1272] opened 2015-09-23 13:17 UTC
After executing several a model with several set of parameter GAMA fills all heap space. Object retained seems to be linked to GAMA geometries. The number of GamaPoint objects never stops growing despite the MoleExperiment has been disposed. 

![heap](https://cloud.githubusercontent.com/assets/1270995/10045808/9fc872ae-6205-11e5-96f1-d6f28567e876.png)

Here is the stack by which a point is retained:
![stack](https://cloud.githubusercontent.com/assets/1270995/10045884/136e9670-6206-11e5-93ee-64b785262a83.png)

**Comment by ptaillandier** [comment] 2015-09-23 14:19
Hi,

Just a question: do you get the same result if you run different models
(and not only different parameter set) - I do not know if it is easy to
test with OpenMole....

Another question, which model and which parameters did you test?

Cheers,

Patrick

2015-09-23 15:17 GMT+02:00 Romain Reuillon <notifications@github.com>:

**Comment by romainreuillon** [comment] 2015-09-23 14:42
Hi,

it is for the same model (gaml file) but for several experiments from the OpenMOLE point of view. However OpenMOLE calls ```MoleSimulationLoader.loadModel``` for each set of parameter values (ie run of the GamaTask), so I guess it is a new model each time from the GAMA point of view. It also calls the dispose method one the experiment and on the model after each run.

The code actually calling Gama is in the method process of [this class](https://github.com/openmole/gama-plugin/tree/6-dev/org.openmole.plugin.task.gama/src/main/scala/org/openmole/plugin/task/gama).

Romain

**Comment by romainreuillon** [comment] 2015-09-23 16:20
You can download the heap [here](http://web.iscpif.fr/~reuillon/heap.bin)

**Comment by reyman** [comment] 2015-10-19 15:21
Hi @romainreuillon, which `gaml` model do you use ? 
A toy model from gama library ?

**Comment by romainreuillon** [comment] 2015-10-19 15:25
Yes I used this model: https://github.com/openmole/openmole-market/blob/6-dev/gama/predatorPrey.gaml

**Comment by reyman** [comment] 2015-10-20 14:00
With Romain we explore the heap.bin, `GAMAPoint` are retain by `GamaShape`, referenced by SImulationAgent, referenced by a `Scope`, referenced by the global scheduler `GAMA.controller.getScheduler()`

To avoid this kind of memory leak, could we instanciate one local scheduler (no global variable) by simulation ? Otherwise, do you have any idea how to clean between two simulation/step in the headless mode ?

**Comment by AlexisDrogoul** [comment] 2015-10-20 15:01
Hi,

Having a global controller and scheduler, and having a « current » simulation agent referenced by them, should not have any influence on a memory leak, as long as the simulation object is correctly disposed each time it is relaunched by the experiment. This is (I guess) the difference between the headless version and the GUI version. Unfortunately, in headless mode, I have never been able to correctly trace what is happening when a simulation is disposed, as there are too many objects that interfere. 

Probably Nicolas can help on this matter (as we already removed a memory leak some time ago together by debugging the headless version).

Cheers
Alexis




> Le 20 oct. 2015 à 21:00, Rey <notifications@github.com> a écrit :
> 
> With Romain we explore the heap.bin, GAMAPoint are retain by GamaShape, referenced by SImulationAgent, referenced by a Scope, referenced by the global scheduler GAMA.controller.getScheduler()
> 
> To avoid this kind of memory leak, could we instanciate one local scheduler (no global variable) by simulation ? Otherwise, do you have any idea how to clean between two simulation/step in the headless mode ?
> 
> —
> Reply to this email directly or view it on GitHub.
> 

--
Senior Researcher, UMI UMMISCO 209, IRD & UPMC, France.
--
alexis.drogoul@gmail.com | http://goo.gl/4ewFdJ
[Vietnam] +84915088155 [France] +33608698845
--
GAMA: http://gama-platform.org

**Comment by reyman** [comment] 2015-10-20 15:57
Ok, maybe in the next day i try to explore and trace (and draw?) the succesive call of function. 

I suppose that the `clean()` or the `dispose()` method is perhaprs not correctly called from OpenMole plugin ? 

```java
	@Override
	public long step() {
		this.currentExperiment.getCurrentSimulation().step(this.getScope());
		return currentStep++;
	}

	@Override
	public void dispose() {
		this.currentExperiment.dispose();
	}

```

**Comment by reyman** [comment] 2015-10-21 16:59
Hi,

I'm not sure but, when i retrace the call from multiple function `dispose()` in headless, i see that `dispose()` method is not declared for `msi.gama.metamodel.shape.GamaPoint`

Into `dispose()` of `ExperimentPlan` , the `agent.dispose()` call `dispose()` of an `ExperimentAgent` 

Into this `dispose()` of  `ExperimentAgent` we have a : 
- `super.dispose()` which call `GAMLAgent.dispose()` 
- and `dispose()` called on `getSimulation()`  call a `dispose()` from agent with `IShape` interface 
- `super.dispose()` return a `dispose()` from AbstractSpecies

I don't see a call on `GamaPoint dispose()` method in this `dispose()` of `ExperimentAgent`, and `msi.gama.metamodel.shape.GamaPoint dispose()` is not declared.

Or as we can see in @romainreuillon picture, the `GamaPoint` is equal to 14% of instances.

Do you think the leak can be here ?

**Comment by reyman** [comment] 2015-10-28 16:20
Hi,

Good news, after some session of Gama code reading, i finally found a radical solution to close the experiment, and remove the memory leak.

In moleExperiment class into `msi.gama.headless.openmole`, i simply replace old `dispose()` by : 

```java
	@Override
	public void dispose() {
		GAMA.controller.closeExperiment();
		}
```

But there is also a bad news for an usage with OpenMOLE, the problem is not with multithreading managed by Gama, but when the multithreading is managed by OpenMOLE. 

Actually, if i understand well the code, the headless mode use an unique `FrontEndController` **static** global object. In `Gama` public class  (link [here](https://github.com/gama-platform/gama/blob/3340e108dbac45e9d060900096edf59273d1dfbb/msi.gama.core/src/msi/gama/runtime/GAMA.java)) we have :

'''java
	public final static FrontEndController controller = new FrontEndController(new FrontEndScheduler());
  '''

When OpenMOLE launch multiple Gama instance (multithreading managed by openmole) in a single JVM on a single node (like one local computer with 4 processors). 

But, this global FrontEndController objet is shared by all the instance into JVM, [right](http://stackoverflow.com/questions/686079/in-java-are-static-class-members-shared-among-programs)  ? So Houston, we have a problem, any call of `loadCurrentExperiment(...)` inject a new object `ExperimentPlan` into the shared `GAMA.controller`  (ie the global object `FrontEndController`), and overwrite if it exists the precedent object `ExperimentPlan` ...

Actually, with this code, behaviors of design of experiments are probably *totally imprevisible*.

One (bad?) solution is to use the actual controllers object stored in the same class `Gama` (link [here](https://github.com/gama-platform/gama/blob/3340e108dbac45e9d060900096edf59273d1dfbb/msi.gama.core/src/msi/gama/runtime/GAMA.java)). It contains a `final static Map<String, FrontEndController> controllers`  I suppose that each of this controller stored is linked to only one ExperimentPlan in multithreading use case ? Any other idea ?

**Comment by AlexisDrogoul** [comment] 2015-10-29 11:52
Hi Sebastien,

Good job (for the first part) ! closeExperiment() is a bit rude, but it certainly does the job. Regarding OpenMole, I'm not sure I fully understand. In one JVM, I can have several instances of Gama, that are living their own lives in their own context. I can, for instance, launch several instances of Gama on my computer without them sharing anything else than the workspace (if they use the same), and they will be running in their own process. 

But the fact that I do not understand it does not mean the problem does not exist and I guess you have verified that the exact same Controller object is actually used in all the instances of Gama you launch on this JVM ?

The `controllers`variable could probably be used if you have a unique reference to each of the running experiments. It has been defined by Nghi (@hqnghi88) to store sub-models (in the case of co-modeling, i.e. running several models together), and he is probably the only one able to tell you if it could be used safely or not for your purpose. I am however more or less sure that it relies somehow on the existence of a working `controller`. 

Another solution could be to redefine `controller`as a ThreadLocal< FrontEndController> static variable. I know it would probably break a number of existing things, but it would probably harmless (once the direct accesses to Gama.controller are corrected) for a single instance of GAMA (writing this, I actually wonder if it would be true: maybe you have to somehow identify the master process of the current Gama instance and use this as a key to get the current controller; could it be done in a clean way ? It would mean having a proper getController() method, and testing in it which process the current thread belongs to before returning the correct controller…). 

BTW, I will be in Paris next week so we can take some time together to have a closer look (for ex. on Wednesday afternoon).

Cheers
Alexis

**Comment by reyman** [comment] 2015-11-04 10:29
Hi, 
I make some test yesterday using the workflow provided in [market](https://github.com/openmole/openmole-market/tree/6-dev/gama)

It's impossible to run multithreaded version of `GamaTask` due to this unique shared `controller`. It run only with one thread : 

```scala
val env = LocalEnvironment(1)
exploration -< Strain(Strain(replications) -< (gama on env) >- average) hook csvHook 
```

with `LocalEnvironment` superior to 1, error and behavior are imprevisible. Experiment crash.

Next week i take some time to continue my exploration in gama headless code, and try to implement one of solution proposed by @AlexisDrogoul

Best.
SR.

**Comment by AlexisDrogoul** [comment] 2015-12-05 03:58
I come back to this issue. If I understand correctly, OpenMole loads the experiments in the same JVM, but also using the same ClassLoader ? Wouldn't it be much safer and cleaner — and not only for this issue —  to at least use a different ClassLoader to load each instance of the same application (be it NetLogo, Gama or others) ?

**Comment by romainreuillon** [comment] 2015-12-05 09:15
We use OSGi and equinox, meaning that there is one bundle by classloader. It is not possible in an OSGi application to load twice the same bundle with the same id and version. The clean way would be to get rid of the mutable global variables in GAMA, it is well known to be a pain for concurrent application as well as for software architecture in general.

**Comment by AlexisDrogoul** [comment] 2015-12-05 10:42
OK. To be more precise, it means that you only have one OSGi container and bus running on the JVM (and only one JVM running on each machine) ?

**Comment by romainreuillon** [comment] 2015-12-05 10:44
OpenMOLE is composed of many OSGi bundles running all in a single OSGi bus.

**Comment by AlexisDrogoul** [comment] 2015-12-14 06:50
I have committed (in c200c6b09467a48542e18938db8bdef45a1054fd) a first approach towards getting rid of the global controller (with one controller per experiment). It should work, although I'm not completely sure it will not create new problems in memory management (there is a slight risk that experiments can be retained in memory). So it needs to be more extensively tested than the few tests I made by myself. Nicolas (@gnoubi), could you generate a version like you used to do and test the headless operations, since I'm not sure of how you handle the disposal of experiments ?

**Comment by reyman** [comment] 2015-12-14 08:31
@AlexisDrogoul @gnoubi That's a great news ! I also try to re generate a release to use with gama openmole in the next days.

**Comment by AlexisDrogoul** [comment] 2016-01-27 02:26
Both this issue and #1270 need to be tested for the first beta. Any chance to do it quickly — for instance @gnoubi ?

**Comment by reyman** [comment] 2016-01-27 07:20
i try on my side,  and we probably can plannify à meeting with @gnoubi to
discuss openmole gama plugin during February or march.

Le mer. 27 janv. 2016 03:26, Alexis Drogoul <notifications@github.com> a
écrit :

**Comment by gnoubi** [comment] 2016-01-27 08:19
the #1272

was done last week. a GIS model was loaded and closed several times. After few bug fixes, Memory inspector showed nothing with the new version of gama. Now we have to check it with openMole. A meeting will be organized with Sebastien Rey

I am going to close the issue


-- 
Nicolas Marilleau
UMI 209 UMMISCO Institut de Recherche pour le Développement
Chercheur invité DISC/ Femto-ST Université de Franche-Comté

32 rue Henri Varagnat
93143 Bondy Cedex
tel : 01.48.02.79.01
mobile : 06.88.33.49.06

**Comment by gnoubi** [comment] 2016-01-27 08:22
a GIS model was loaded and closed several times. After few bug fixes, Memory inspector showed nothing with the new version of gama. Now we have to check it with openMole. A meeting will be organized with Sebastien Rey

**Closed by gnoubi** 2016-01-27 08:22 UTC
Labels: > Bug, Concerns Batch, Version Git
