### ISSUE TITLE
Freeze at restart after I forced GAMA to stop (corrupted workspace ?)

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#2382] opened 2018-04-02 05:45 UTC
### Steps to reproduce
1. After GAMA has freezed, I had to kill it / force it to stop.

2. Restart GAMA on the same workspace

### Expected behavior
Run properly

### Actual behavior
GAMA freezes at:
```
macbook-pro-de-ben:MacOS ben$ ./Gama 
Bad value: "${target.nl}" for NL. Using system default.
>GAMA version 1.7.0.201803290307 loading...
>GAMA models library version: .built_in_models_1522321189000
```

Note that when I restart GAMA with a new workspace it works well.

### System and version 
Which version of GAMA, JDK, OS ... (if necessary, copy Help>Installation Details>Configuration in GAMA)

**Comment by hqnghi88** [comment] 2018-04-02 07:52
Dear Benoit,
Any chance to have the reproducing steps for the first gama freezed? I have no idea to do with a corrupted workspace, if we launch with -clean, does it help? At least it would not freeze as same as create new workspace but we need to readd projects.

**Comment by benoitgaudou** [comment] 2018-04-02 08:54
Hi,
A good technic to make GAMA freeze:
on MAC, run a model with a grid (in java2D) and 2 display charts.
In the Preferences, Displays,
for the preference :
"Delay in ms between the opening of views (....)" put  the value to 0.2 for
example (or smaller).

It should make GAMA freeze after a few number of relaunch of the model.

Benoit

2018-04-02 9:52 GMT+02:00 HUYNH Quang-Nghi <notifications@github.com>:

**Comment by hqnghi88** [comment] 2018-04-02 14:07
Well, is it a metaphor "grid and 2 display charts" for SIR_comodel? ;) Please, can you export your preference (as a gaml model i think). Thank you toomuch for that .

**Comment by benoitgaudou** [comment] 2018-04-02 17:22
Hi,

What a magic trick that you can get your preferences as a GAML model :-)

Notice that I set, so that I can avoid so freezes of GAMA when I run my
model.
    //Delay in ms between the opening of views (increase to avoid freezes
of Java2D displays)
    gama.pref_display_delay_views <- 1000;


And not, it is not the SIR_comodel I was talking about :-)
Just a simple Cabbage-Goat-Wolf model (Prey-predator) I was working on for
the training session.
I attach it, it should hava a java2D+ 2 chart displays... and was the cause
of some GAMA freeze this afternoon.

Thank you

Benoit




2018-04-02 16:07 GMT+02:00 HUYNH Quang-Nghi <notifications@github.com>:

**Comment by hqnghi88** [comment] 2018-04-02 17:28
Dear Benoit,
The magic is below the preference dialog, it is the export button. It was really a problem for that threshold of delay, it is written as a warning message in that preference. So i think  , to avoid the corruption, we then do not allow to set delay below 2ms (2ms is depend on power of cpu o think, it becomes too quickly for 2018). Anyway i ll try to create corruption to see further moves.

**Comment by benoitgaudou** [comment] 2018-04-03 04:10
Hi Nghi,

I do not know if it can help you, but please find attached a recent
workspace I corrupted.
I also attached my preferences.gaml.

Notice that I was able to freeze my GAMA, even with this preference :

    //Delay in ms between the opening of views (increase to avoid freezes
of Java2D displays)
    gama.pref_display_delay_views <- 1000;

Benoit

2018-04-02 19:28 GMT+02:00 HUYNH Quang-Nghi <notifications@github.com>:

**Comment by AlexisDrogoul** [comment] 2018-04-03 04:24
@benoitgaudou There are no attached files to your comment.

**Comment by AlexisDrogoul** [comment] 2018-04-03 04:25
@benoitgaudou BTW, have you tried to set this preference to zero (seems to work better on Macs).

**Comment by hqnghi88** [comment] 2018-04-03 04:26
[wsGamaOxyRel.zip](https://github.com/gama-platform/gama/files/1870195/wsGamaOxyRel.zip)

[preferences.zip](https://github.com/gama-platform/gama/files/1870197/preferences.zip)
Here there are, from private email

**Comment by AlexisDrogoul** [comment] 2018-04-03 04:40
Seems that the class that makes everything freeze in the case of a corrupted workspace is SimulationStateProvider, due to an osgi error ("Unable to acquire the state change lock for the module") probably caused by the force quit of GAMA (remaining .lock files and .fileDataTable files, among other things). This is annoying to say the least...

**Comment by AlexisDrogoul** [comment] 2018-04-03 04:58
One solution (suggested somewhere for Eclipse) might be to disable entirely the locking / unlocking of osgi modules by adding to Gama.ini the option ` -Dosgi.locking=none` ... Could be worth the try ?

**Comment by hqnghi88** [comment] 2018-04-03 05:01
It works with that instruction. Will we add it permanently in .product?

**Comment by AlexisDrogoul** [comment] 2018-04-03 07:00
Actually, I don't know the consequences of setting this setting to `none`.

**Comment by AlexisDrogoul** [comment] 2018-04-03 09:28
@hqnghi88 You can always go ahead, I haven't found anything on Internet regarding the problems caused (or prevented) by this option. If anyone has some clue ...

**Comment by AlexisDrogoul** [comment] 2018-06-01 12:41
Does this problem still happen with the locking disabled ? Otherwise, we can probably close the issue.

**Comment by benoitgaudou** [comment] 2018-06-01 12:45
I do not have a freeze of GAMA.
So GAMA can restart after it has been forced to stop.
The only point is that in the first relaunch on the same workspace after I
had to kill GAMA, all the views have errors.
I need to restart GAMA , and everything is fine.

Benoit

2018-06-01 14:41 GMT+02:00 Alexis Drogoul <notifications@github.com>:

**Closed** 2018-06-02 05:40 UTC
Labels: > Bug, Affects Usability, OS OSX, Version 1.8 preRelease
